cyfronet-fid/sat4envi

s4e-web/src/app/app.component.ts, s4e-web/src/app/map/map.component.ts
Remove the definition of the projection from app.component.ts and revert
map.component to web mercator.
Change base map to OSM tiles.
Change layers from type Tile to Image, to load a single image at once
instead loading a number of tiles.
Fixes #54.
=> Revert using EPSG:3413

README.md
Instruction has been fixed, due to the fact that originally `mvn package` will fail for sure because no test database server is running.
=> Fix readme for setting up development environment

s4e-backend/src/main/java/pl/cyfronet/s4e/controller/LoginController.java, s4e-backend/src/main/java/pl/cyfronet/s4e/security/JWTTokenService.java, s4e-backend/src/test/java/pl/cyfronet/s4e/security/JWTTokenServiceTest.java
Modify signature of JWTTokenService::generateClaimsJws, which accepts
Authentication object now, which is necessary to extract authorities.
Closes: #52.
=> [#52] Include authorities in JWS claims

s4e-backend/pom.xml, s4e-backend/src/main/java/pl/cyfronet/s4e/SwaggerConfig.java
In 2.9.2 the example responses and params are not populated. To use this
feature the unreleased 3.0.0-SNAPSHOT has to be used.
Not the best idea to use a snapshot, but hopefully the 3.0.0 will be
released in not so long future...
=> Upgrade to springfox 3.0.0-SNAPSHOT

s4e-backend/pom.xml, s4e-backend/src/main/java/pl/cyfronet/s4e/I18nConfig.java, s4e-backend/src/main/java/pl/cyfronet/s4e/LoggingMailSender.java, s4e-backend/src/main/java/pl/cyfronet/s4e/SwaggerConfig.java, s4e-backend/src/main/java/pl/cyfronet/s4e/ThreadConfig.java, s4e-backend/src/main/java/pl/cyfronet/s4e/bean/EmailVerification.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/AppUserController.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/request/LoginRequest.java, s4e-backend/src/main/java/pl/cyfronet/s4e/data/repository/EmailVerificationRepository.java, s4e-backend/src/main/java/pl/cyfronet/s4e/event/OnEmailConfirmedEvent.java, s4e-backend/src/main/java/pl/cyfronet/s4e/event/OnRegistrationCompleteEvent.java, s4e-backend/src/main/java/pl/cyfronet/s4e/event/OnResendRegistrationTokenEvent.java, s4e-backend/src/main/java/pl/cyfronet/s4e/ex/AsyncUncaughtExceptionHandlerImpl.java, s4e-backend/src/main/java/pl/cyfronet/s4e/ex/ErrorHandler.java, s4e-backend/src/main/java/pl/cyfronet/s4e/ex/ErrorHandlerHelper.java, s4e-backend/src/main/java/pl/cyfronet/s4e/ex/RegistrationTokenExpiredException.java, s4e-backend/src/main/java/pl/cyfronet/s4e/listener/EmailVerificationListener.java, s4e-backend/src/main/java/pl/cyfronet/s4e/service/AppUserService.java, s4e-backend/src/main/java/pl/cyfronet/s4e/service/EmailVerificationService.java, s4e-backend/src/main/resources/db/migration/V3__add_email_verification_table.sql, s4e-backend/src/main/resources/messages_pl_PL.properties, s4e-backend/src/test/java/pl/cyfronet/s4e/GreenMailSupplier.java, s4e-backend/src/test/java/pl/cyfronet/s4e/LoggingMailSenderTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/controller/AppUserControllerTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/controller/LoginControllerTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/listener/EmailVerificationListenerTest.java, s4e-backend/src/test/resources/application-test.properties
Add token based email verification. An AppUser is created with field
enabled=false, and it can be activated using the token sent by mail.
The logic of sending emails is decoupled from the controller to async
event listeners.
Create LoggingMailSender, which outputs email contents to log.
For testing I introduced GreenMail, which is used to verify appropriate
emails are sent.
The email contents are put in messages_pl_PL.properties.
=> [#28] Email verification

s4e-backend/src/main/java/pl/cyfronet/s4e/Constants.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/ConfigController.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/response/ConfigResponse.java, s4e-backend/src/main/resources/application-development.properties, s4e-backend/src/test/java/pl/cyfronet/s4e/controller/ConfigControllerTest.java, s4e-backend/src/test/resources/application-test.properties
For now, geoserverUrl, geoserverWorkspace and backendDateFormat are
exposed in the response.
=> [#88] Add configuration endpoint

s4e-backend/src/test/java/pl/cyfronet/s4e/controller/AppUserControllerTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/controller/LoginControllerTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/controller/PlaceControllerTest.java
Seems better to use an out of the box solution than a manual setup in @BeforeEach.
The mechanism is first used in ConfigControllerTest in #89.
Also, I removed AsyncUncaughtExceptionHandlerImpl, which was unused in AppUserControlerTest.
=> Use @AutoConfigureMockMvc mechanism in controller tests

README.md, s4e-backend/pom.xml, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/AppUserController.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/ConfigController.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/response/ConfigResponse.java, s4e-backend/src/main/java/pl/cyfronet/s4e/db/SeedDevelopment.java, s4e-backend/src/main/java/pl/cyfronet/s4e/ex/ErrorHandler.java, s4e-backend/src/main/java/pl/cyfronet/s4e/ex/ErrorHandlerHelper.java, s4e-backend/src/main/java/pl/cyfronet/s4e/ex/RecaptchaException.java, s4e-backend/src/main/resources/application-development.properties, s4e-backend/src/test/java/pl/cyfronet/s4e/controller/AppUserControllerTest.java, s4e-backend/src/test/resources/application-test.properties
Add dependency to recaptcha-spring-boot-starter, which handles
sending request to the Google reCAPTCHA service.
The RecaptchaValidator is called in the AppUserController::register,
validating the received param `g-recaptcha-response`.
In case of validator error appropriate error codes are returned in
field `recaptcha`.
For tests the validator test mode is enabled, and in development it
uses the always-returning-true key-set which is recommended for tests in
reCAPTCHA FAQ.
Add field `recaptchaSiteKey` to the `/api/v1/config` response.
Fixes: #120.
=> [#120] reCAPTCHA backend

README.md, s4e-backend/src/main/java/pl/cyfronet/s4e/db/seed/SeedPlaces.java, s4e-backend/src/main/java/pl/cyfronet/s4e/db/seed/SeedProducts.java, s4e-backend/src/main/java/pl/cyfronet/s4e/db/seed/SeedUsers.java
Split SeedDevelopment to SeedUsers and SeedProducts, which are
independent.
Moreover, allow to turn the seeds on in profiles other than development
by setting appropriate profile `run-seed-<name>`.
=> [#136] Reorganize seeds and allow to run them on demand

pom.xml, s4e-backend/pom.xml
spring-boot-starter 2.1.5.RELEASE -> 2.1.7.RELEASE
jjwt 0.10.6 -> 0.10.7
junit 5.4.2 -> 5.5.1
mockito 2.28.2 -> 3.0.0
recaptcha-starter 2.3.0 -> 2.3.1
=> Backend dependencies update - 2019.08

.gitignore, README.md, backend-development.env, backend-production.env.template, docker-compose.yml, s4e-backend/src/main/resources/application-production.properties
Copy the development profile variables to production.
They should be overridden when running the containers though.
In docker-compose.yml set system properties for s4e-backend with env_file.
The path leading to the file can be customized by setting BACKEND_ENV_PATH.
Create a default, development env_file `backend-development.env` and
a template for production use `backend-production.env.template`.
=> Production profile properties and their customization in docker-compose

s4e-backend/src/main/java/pl/cyfronet/s4e/AuthorizationServerConfiguration.java, s4e-backend/src/main/java/pl/cyfronet/s4e/Constants.java, s4e-backend/src/main/java/pl/cyfronet/s4e/bean/RefreshToken.java, s4e-backend/src/main/java/pl/cyfronet/s4e/data/repository/RefreshTokenRepository.java, s4e-backend/src/main/java/pl/cyfronet/s4e/security/PersistingJwtTokenStore.java, s4e-backend/src/main/resources/db/migration/V7__add_refresh_token_table.sql, s4e-backend/src/test/java/pl/cyfronet/s4e/security/PersistingJwtTokenStoreTest.java
Create RefreshToken entity which represents created refresh tokens.
Create the PersistingJwtTokenStore which stores created refresh tokens
and verifies if it exists when reading.
The newly created store delegates other actions to the JwtTokenStore
instance.
For now I haven't created any tests for that, they should be added.
They should verify if a token can be revoked by removing a db record.
=> Persist refresh tokens in TokenStore

README.md, resources/geoserver/.gitignore, s4e-backend/src/main/java/pl/cyfronet/s4e/db/seed/SeedProducts.java, s4e-backend/src/main/java/pl/cyfronet/s4e/geoserver/op/GeoServerOperations.java, s4e-backend/src/main/java/pl/cyfronet/s4e/geoserver/sync/GeoServerSynchronizer.java
Rework the SeedProducts to enable multiple data set support. For now
only two are available, so I don't introduce any extra abstraction over
the choice mechanism. However, I introduce a parameterized product
generation.
Improve GeoServerOperations timeout handling, which is now set to 60s
and can be customized in case of problems.
The GeoServerOperations::layerExists didn't work as expected, I now
catch the NotFound exception and translate it to false output.
Remove unused GeoServerSychronizer methods.
Closes: #200.
=> [#200] Products seed for s4e-demo data set

docker-compose.yml, s4e-backend/src/main/java/pl/cyfronet/s4e/db/seed/SeedProducts.java, s4e-backend/src/test/java/pl/cyfronet/s4e/geoserver/op/GeoServerOperationsIntegrationTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/service/GeoServerServiceIntegrationTest.java
I changed the version of the GeoServer docker image in
docker-compose.yml to reflect the version scheme.
Moreover, the improved image has PRG vector layer names without
Polish diacritics, so the encoding hacks aren't required anymore.
This PR requires https://github.com/cyfronet-fid/docker-geoserver/pull/1 to be merged, or at least the new image version has to be released.
Fixes: #104.
=> [#104] Use improved GeoServer docker image

s4e-backend/pom.xml, s4e-backend/src/main/java/pl/cyfronet/s4e/LoggingMailSender.java, s4e-backend/src/main/java/pl/cyfronet/s4e/listener/EmailVerificationListener.java, s4e-backend/src/main/java/pl/cyfronet/s4e/listener/GroupListener.java, s4e-backend/src/main/java/pl/cyfronet/s4e/listener/PasswordListener.java, s4e-backend/src/main/java/pl/cyfronet/s4e/service/MailService.java, s4e-backend/src/main/resources/mail/account-activated.html, s4e-backend/src/main/resources/mail/confirm-email.html, s4e-backend/src/main/resources/mail/group-add-member.html, s4e-backend/src/main/resources/mail/group-remove-member.html.html, s4e-backend/src/main/resources/mail/password-reset.html, s4e-backend/src/main/resources/mail/share-link.html, s4e-backend/src/test/java/pl/cyfronet/s4e/listener/EmailVerificationListenerTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/listener/GroupListenerTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/listener/PasswordListenerTest.java
Add HTML counterparts of plain-text email-templates.
Modify the LoggingMailSender to handle multipart messages.
To omit implementing MIME logic, I use Apache Commons Email library.
Closes: #311.
=> [#311] HTML email templates

s4e-backend/src/main/java/pl/cyfronet/s4e/controller/response/AppUserResponse.java, s4e-web/src/app/state/profile/profile.model.ts, s4e-web/src/app/state/profile/profile.query.spec.ts, s4e-web/src/app/state/profile/profile.query.ts, s4e-web/src/app/state/profile/profile.service.spec.ts, s4e-web/src/app/state/profile/profile.service.ts, s4e-web/src/app/state/profile/profile.store.spec.ts, s4e-web/src/app/state/profile/profile.store.ts, s4e-web/src/app/state/session/session.model.ts, s4e-web/src/app/state/session/session.query.ts, s4e-web/src/app/state/session/session.service.ts, s4e-web/src/app/utils/auth-guard/auth-guard.service.spec.ts, s4e-web/src/app/utils/auth-guard/auth-guard.service.ts, s4e-web/src/app/utils/initializer/config.service.ts, s4e-web/src/app/views/map-view/map-view.component.html, s4e-web/src/app/views/map-view/map-view.component.spec.ts, s4e-web/src/app/views/map-view/map-view.component.ts, s4e-web/src/app/views/settings/guards/is-manager/is-manager.guard.spec.ts, s4e-web/src/app/views/settings/guards/is-manager/is-manager.guard.ts, s4e-web/src/app/views/settings/settings.component.html, s4e-web/src/app/views/settings/settings.component.ts, s4e-web/src/app/views/settings/settings.routes.ts
Hide institutions management in settings for users who have management roles, hide ZK dropdown for users who have `memberZK` flag
* Create user who have `memberZK` flag and log in, dropdown should be visible.
* Navigate to settings with user without any group roles - only profile should be visible
* Navigate to settings with user with management group role - all options should be available
=> Extend "Get user profile" endpoint with extra data

s4e-backend/pom.xml, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/ShareLinkController.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/request/ShareLinkRequest.java, s4e-backend/src/main/java/pl/cyfronet/s4e/event/OnShareLinkEvent.java, s4e-backend/src/main/java/pl/cyfronet/s4e/listener/GroupListener.java, s4e-backend/src/main/java/pl/cyfronet/s4e/service/MailService.java, s4e-backend/src/main/resources/mail/share-link.html, s4e-backend/src/main/resources/mail/share-link.txt, s4e-backend/src/main/resources/messages_pl_PL.properties, s4e-backend/src/test/java/pl/cyfronet/s4e/controller/ShareLinkControllerTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/listener/GroupListenerTest.java
Add caption, description and thumbnail fields to `/share-link` endpoint.
Also, rename link to path.
Rework the way the request parameters are handled and passed to the
event listener.
Exclude an unnecessary junit-vintage dependency from
spring-boot-starter-test.
Closes: #321.
=> [#321] Add extra share link fields

.github/workflows/maven.yml, backend-gh-e2e.env, docker-compose.yml, package-lock.json, s4e-backend/src/test/java/pl/cyfronet/s4e/controller/AppUserControllerTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/controller/PasswordControllerTest.java, s4e-web/nginx-e2e.conf, s4e-web/package-lock.json, s4e-web/package.json
Depend on the containers from our docker-compose instead of using gh-actions services. This includes changing e2e run script in package.json, but also s4e-web container definition in docker-compose.yml is updated to allow custom config file specification. (Custom config is required, as when not all proxied locations are present (in the case of e2e: minio, geoserver) then nginx fails to start.)
Remove npm dependencies, which were required by the preexisting solution.
Fix few problems in tests. One that didn't initialize GreenMail where actually used, and another with a log call from debugging.
Fixes: #351.
=> Improve gh-actions workflow (tests, e2e tests, plumbing)

CHANGELOG.md, s4e-web/package-lock.json, s4e-web/package.json, s4e-web/src/app/utils/miscellaneous/miscellaneous.spec.ts, s4e-web/src/app/utils/miscellaneous/miscellaneous.ts, s4e-web/src/app/views/map-view/map-view.component.ts, s4e-web/src/app/views/map-view/zk/save-config-modal/save-config-modal.component.html, s4e-web/src/scss/_modal.scss
The images in save view and share view are now being resized as per #341 specification.
This means that they all have uniform size (which will make them show better on the saved views modal, as well as require less bandwidth and storage space.
Closes: #341
=> [#341] Image resize

CHANGELOG.md, docker-compose.yml, resources/geoserver/s3.properties, s4e-backend/src/main/resources/application-development.properties, s4e-backend/src/main/resources/application-production.properties, s4e-backend/src/test/resources/application-test.properties
The updated GeoServer uses a patched GeoTools version, so that
ImageMosaic+S3Geotiff works.
The endpoint is set to `mailto`, so that an s3geotiff location is a
correct URL, e.g. `mailto://bucket/key`. The protocol part here only
differentiates endpoint configurations, so it doesn't matter if the rest
isn't a correct email address.
Part of #371.
=> Update GeoServer to 1.2.0-GS2.16.2 and correct GS endpoint name

CHANGELOG.md, docker-compose.yml
@kmarszalek: take this into account when pushing IM to GS
@wziajka: there will be new properties in production: GEOSERVER_JNDI_*
Closes: #378.
=> [#378] Update GeoServer image to 1.3.0-GS2.16.2, which has JNDI support

s4e-web/cypress/integration/product-navigation.spec.ts, s4e-web/src/app/views/map-view/map-view.component.scss, s4e-web/src/app/views/map-view/map-view.component.ts, s4e-web/src/app/views/map-view/map/map.component.scss, s4e-web/src/app/views/map-view/search-results/search-results.component.html, s4e-web/src/app/views/map-view/search-results/search-results.component.scss, s4e-web/src/app/views/map-view/state/map/map.model.ts, s4e-web/src/app/views/map-view/state/search-results/search-results.service.spec.ts, s4e-web/src/app/views/map-view/state/search-results/search-results.service.ts, s4e-web/src/app/views/map-view/view-manager/view-manager.component.html, s4e-web/src/app/views/map-view/view-manager/view-manager.component.scss, s4e-web/src/app/views/map-view/view-manager/view-manager.component.ts
* Update map store on selection
Selected search result is saved to `StateSearchResults.selectedLocation` but map is observing `Map.view` which is not changed.
In this PR I added Map.view update to `setSelectedPlace` which works but is not very clean - `SearchResultsService` has to known about projection and zoom level mapping.
=> [#337] Selecting search result should change map

CHANGELOG.md, s4e-web/package.json, s4e-web/projects/notifications/src/lib/components/general-notification/general-notification.component.spec.ts, s4e-web/src/app/views/map-view/zk/configuration/state/configuration.service.spec.ts, s4e-web/src/app/views/map-view/zk/configuration/state/configuration.service.ts, s4e-web/src/tsconfig.spec.json
* Fix notification in jest tests (this is important, importing anything from `notifications` module in tests crashed them) it is fixed now
* Add notification for successful share configuration
Closes: #435
=> [#435] Notifications for share configuration

CHANGELOG.md, s4e-backend/src/main/java/pl/cyfronet/s4e/bean/AppRole.java, s4e-backend/src/main/java/pl/cyfronet/s4e/bean/AppUser.java, s4e-backend/src/main/java/pl/cyfronet/s4e/bean/EmailVerification.java, s4e-backend/src/main/java/pl/cyfronet/s4e/bean/Institution.java, s4e-backend/src/main/java/pl/cyfronet/s4e/bean/Legend.java, s4e-backend/src/main/java/pl/cyfronet/s4e/bean/PRGOverlay.java, s4e-backend/src/main/java/pl/cyfronet/s4e/bean/PasswordReset.java, s4e-backend/src/main/java/pl/cyfronet/s4e/bean/Place.java, s4e-backend/src/main/java/pl/cyfronet/s4e/bean/Product.java, s4e-backend/src/main/java/pl/cyfronet/s4e/bean/Scene.java, s4e-backend/src/main/java/pl/cyfronet/s4e/bean/Schema.java, s4e-backend/src/main/java/pl/cyfronet/s4e/bean/SldStyle.java, s4e-backend/src/main/java/pl/cyfronet/s4e/bean/UserRole.java, s4e-backend/src/main/java/pl/cyfronet/s4e/bean/WMSOverlay.java, s4e-backend/src/main/java/pl/cyfronet/s4e/bean/audit/CreationAndModificationAudited.java, s4e-backend/src/main/java/pl/cyfronet/s4e/bean/audit/CreationAudited.java, s4e-backend/src/main/java/pl/cyfronet/s4e/config/PersistenceConfig.java, s4e-backend/src/main/resources/db/migration/V33__add_auditing_columns.sql, s4e-backend/src/test/java/pl/cyfronet/s4e/db/AuditingTest.java
Schema and UserRole don't have modification auditing, because they are immutable by design.
In the Audited.*By fields, I only optionally log user's name, providing looser coupling, allowing for user deletion, for example.
So far, the auditable fields are not reflected in the API responses. We may not need it, or want to expose it to all parties.
Closes: #202.
=> [#202] Audit selected entitites

CHANGELOG.md, README.md, docker-compose-test.yml, docker-compose.yml, resources/geoserver/.gitignore, resources/geoserver/s3-test.properties, resources/geoserver/s3.properties
Apart from the GeoServer version update, I changed the way of setting S3 credentials: now they are specified as envvars for the container.
@wojt: How do you feel about this way of setting S3 credentials?
@danielkryska: See especially the README.md, have I described it clearly enough?
=> Update geoserver image to fiddev/geoserver:1.4.0-GS2.17.0

CHANGELOG.md, README.md, s4e-backend/src/main/java/pl/cyfronet/s4e/db/seed/SchemaScanner.java, s4e-backend/src/main/java/pl/cyfronet/s4e/db/seed/SeedProducts.java, s4e-backend/src/main/java/pl/cyfronet/s4e/geoserver/op/GeoServerOperations.java, s4e-backend/src/main/java/pl/cyfronet/s4e/properties/SeedProperties.java, s4e-backend/src/main/java/pl/cyfronet/s4e/service/SceneStorage.java, s4e-backend/src/main/java/pl/cyfronet/s4e/sync/PrefixScanner.java, s4e-backend/src/main/java/pl/cyfronet/s4e/sync/step/VerifyAllArtifactsExist.java, s4e-backend/src/main/java/pl/cyfronet/s4e/sync/step/metadata/IngestS3Path.java, s4e-backend/src/main/java/pl/cyfronet/s4e/util/ResourceReader.java, s4e-backend/src/main/resources/db/migration/V34__drop_scene_product_id_timestamp_key_unique.sql, s4e-backend/src/main/resources/schema/s4e-sync-1/MSG.metadata.v1.json, s4e-backend/src/main/resources/schema/s4e-sync-1/MSG.scene.v1.json, s4e-backend/src/main/resources/schema/s4e-sync-1/Sentinel-1.metadata.v1.json, s4e-backend/src/main/resources/schema/s4e-sync-1/Sentinel-1.scene.v1.json, s4e-backend/src/main/resources/schema/s4e-sync-1/Sentinel-2.metadata.v1.json, s4e-backend/src/main/resources/schema/s4e-sync-1/Sentinel-2.scene.v1.json, s4e-backend/src/test/java/pl/cyfronet/s4e/sync/PrefixScannerIntegrationTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/sync/SceneAcceptorIntegrationTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/sync/step/VerifyAllArtifactsExistTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/sync/step/metadata/IngestS3PathTest.java
The PR contains some refactoring prior to introducing the actual functionality.
The synchronization itself is a thin layer using PrefixScanner and SceneAcceptor and is not extracted to a separate class for now.
There is no endpoint for running this sort of synchronization. It should come with other endpoints for managing Schemas and Products, I guess.
Load the schemas from resources and create products which base on them in SeedProducts.
Then, PrefixScanner is used to enumerate all the keys under each product prefix.
The number of loaded scenes per product is controlled by an extra property: `seed.products.s4e-sync-1.limit`.
Keys must come without a leading slash, although we require the leading
slash in scene file to allow for relative path handling.
Execute a HeadObjectRequest in …
=> [#439] Add s4e-sync-1 dataset

.gitignore, CHANGELOG.md, s4e-web/.gitignore, s4e-web/cypress/integration/profile.spec.ts, s4e-web/projects/notifications/src/lib/state/notification.store.ts, s4e-web/src/app/app.module.ts, s4e-web/src/app/app.routes.ts, s4e-web/src/app/state/common-state.module.ts, s4e-web/src/app/state/session/session.service.ts, s4e-web/src/app/views/login/login.component.html, s4e-web/src/app/views/logout/logout.component.spec.ts, s4e-web/src/app/views/logout/logout.component.ts, s4e-web/src/app/views/logout/logout.module.ts, s4e-web/src/app/views/map-view/map-view.component.html, s4e-web/src/app/views/map-view/map-view.component.ts, s4e-web/src/app/views/settings/settings.component.html, s4e-web/src/app/views/settings/settings.component.ts
- logout can be done by navigating to link `/logout`
- when log out button clicked, a user should be navigated to `/login` page
- Storage error (after login, logout, login and moving to `/settings/profile`) have been repaired
=> [#445] Add /logout routing and clear storage on logout (inconsistent state of storage)

CHANGELOG.md, s4e-backend/pom.xml, s4e-backend/src/test/java/pl/cyfronet/s4e/SwaggerTest.java
Moreover, add a test which verifies, that OpenAPI is returning 200.
Fixes: #467.
=> [#467] Update springdoc-openapi to 1.3.9

CHANGELOG.md, s4e-backend/src/main/java/pl/cyfronet/s4e/bean/Scene.java, s4e-backend/src/main/java/pl/cyfronet/s4e/bean/WMSOverlay.java, s4e-backend/src/main/java/pl/cyfronet/s4e/data/repository/PRGOverlayRepository.java, s4e-backend/src/main/java/pl/cyfronet/s4e/data/repository/SceneRepository.java, s4e-backend/src/main/java/pl/cyfronet/s4e/db/seed/SeedProducts.java, s4e-backend/src/main/java/pl/cyfronet/s4e/sync/ScenePersister.java, s4e-backend/src/main/resources/db/migration/V36__add_scene_key_column_to_scene_table.sql, s4e-backend/src/test/java/pl/cyfronet/s4e/SceneTestHelper.java, s4e-backend/src/test/java/pl/cyfronet/s4e/TestDbHelper.java, s4e-backend/src/test/java/pl/cyfronet/s4e/TestGeometryHelper.java, s4e-backend/src/test/java/pl/cyfronet/s4e/controller/SceneControllerTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/db/DbTimestampTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/geoserver/op/GeoServerOperationsIntegrationTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/geoserver/op/SeedProductsTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/service/GeoServerServiceIntegrationTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/service/GeoServerServiceTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/service/SceneServiceTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/service/SearchServiceTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/sync/QueueReceiverIntegrationTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/sync/SceneAcceptorIntegrationTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/sync/ScenePersisterTest.java
I add scene.scene_key unique column, which identifies each Scene. It is consulted when receiving a scene file update to determine if we have to update a record or create a new one.
This addition forces updates in Scene bootstraping in tests and seeds.
Apart from that, refactor Scene and Product creation in tests in a separate commit, as there was a lot of repetition there. Also, fix WMSOverlay table name and several other improvements.
Closes: #469.
=> Handle Scene updates

CHANGELOG.md, gs-gateway/pom.xml, pom.xml, s4e-backend/pom.xml, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/GroupController.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/InstitutionController.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/PlaceController.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/SavedViewController.java, s4e-web/pom.xml
Include json-path explicitly in s4e-backend/pom.xml, otherwise
com.jayway.jsonpath.spi.mapper.MappingProvider isn't found in AmqpConfig::messageConverter.
It sets setUseProjectionForInterfaces(true), which in turn depends on the MappingProvider.
This was in caused by moving from openapi-data-rest dependency to
openapi-webmvc-core. The former forced dependency on spring-data-rest,
which is unnecessary in our case. However, it caused the problem
described in the paragraph above.
Apart from this, I moved plugin versions from s4e-web to
pluginManagement in parent module.
=> Backend dependencies update - 2020.06

CHANGELOG.md, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/validation/Base64Validator.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/validation/ContentTypeValidator.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/validation/ImageDimensionsValidator.java, s4e-backend/src/test/java/pl/cyfronet/s4e/controller/validation/ContentTypeValidatorTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/controller/validation/ImageDimensionsValidatorTest.java
Regardless if the emblem is required or not, Validators shouldn't throw NPEs in case incoming value is null.
Closes: #491.
=> [#491] Allow null in custom validators

CHANGELOG.md, s4e-backend/src/main/java/pl/cyfronet/s4e/db/seed/SchemaScanner.java, s4e-backend/src/main/java/pl/cyfronet/s4e/db/seed/SeedProducts.java
SchemaScanner::scan used operations restricted to filesystem, however,
Spring provides classpath resource resolution methods applicable here,
which I use.
Morever, using parallel stream is problematic in conjunction with
ServiceLoader.
It seems, that threads spawned by a parallel stream are independent from
the ones created by a ThreadPool, they inherit another classloader,
which doesn't see SPI loaded classes (in our case JsonProviderImpl).
I solve this by registering tasks one by one and waiting afterwards.
Closes: #570
=> [#570] Fix schema scanning and parallel seeding when running from a jar

CHANGELOG.md, s4e-backend/src/main/java/pl/cyfronet/s4e/geoserver/op/GeoServerOperations.java, s4e-backend/src/main/resources/geoserver/mosaic.properties
Previously, levels were set to a high value, and there was quality loss due to that.
Also, some layers were shifted horizontally, setting heterogeneous property fixes the problem.
Closes: #603.
=> [#603] Set GeoServer mosaic levels and heterogeneous properties

CHANGELOG.md, s4e-backend/src/main/resources/db/migration/V39__add_scene_timestamp_index.sql
Add a B-tree index on `scene.timestamp`, as without it `SceneService::getAvailabilityDates` performance degraded when many Scenes were present in the table.
Closes: #610.
=> [#610] Improve scene time filtering performance

CHANGELOG.md, s4e-backend/src/main/java/pl/cyfronet/s4e/admin/sync/PrefixScanner.java, s4e-backend/src/main/java/pl/cyfronet/s4e/admin/sync/api/AdminSyncJobController.java, s4e-backend/src/main/java/pl/cyfronet/s4e/admin/sync/api/CreateSyncJobRequest.java, s4e-backend/src/main/java/pl/cyfronet/s4e/admin/sync/api/ErrorsResponse.java, s4e-backend/src/main/java/pl/cyfronet/s4e/admin/sync/api/RunningDetailsMapper.java, s4e-backend/src/main/java/pl/cyfronet/s4e/admin/sync/api/SyncJobMapper.java, s4e-backend/src/main/java/pl/cyfronet/s4e/admin/sync/api/SyncJobResponse.java, s4e-backend/src/main/java/pl/cyfronet/s4e/admin/sync/task/ChunkedRunner.java, s4e-backend/src/main/java/pl/cyfronet/s4e/admin/sync/task/SyncJob.java, s4e-backend/src/main/java/pl/cyfronet/s4e/admin/sync/task/SyncJobManager.java, s4e-backend/src/main/java/pl/cyfronet/s4e/admin/sync/task/SyncJobStore.java, s4e-backend/src/main/java/pl/cyfronet/s4e/config/SyncJobsConfig.java, s4e-backend/src/main/java/pl/cyfronet/s4e/db/seed/SeedProducts.java, s4e-backend/src/main/java/pl/cyfronet/s4e/properties/SyncJobsProperties.java, s4e-backend/src/test/java/pl/cyfronet/s4e/admin/sync/PrefixScannerIntegrationTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/admin/sync/api/AdminSyncJobControllerIntegrationTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/admin/sync/task/ChunkedRunnerTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/admin/sync/task/SyncJobManagerTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/admin/sync/task/SyncJobStoreTest.java
The synchronization system is divided into three main parts:
- SyncJobManager: manages jobs state, running operation and details,
- ChunkedRunner: processes a stream of Runnables in chunks,
- SyncJobStore: maintains a list of jobs.
The idea behind using ChunkedRunner is not to load all the scenes keys
into memory, as they can be loaded in chunks while maintaining
parallelism.
During the operation of a job it maintains its state, which is exposed
under GET endpoint - in this way it's possible to monitor the operation
of the job.
For example, it could fail for all keys - in that case it can be
cancelled, and the problem investigated.
All the acceptor Errors are stored in the job for inspection.
The jobs are not persisted to DB, and are the state of a specific
instance of backend.
Memory can …
=> [#621] Add admin Scenes synchronization endpoints

CHANGELOG.md, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/InvitationController.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/request/InvitationResendInvitation.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/response/BasicInvitationResponse.java, s4e-backend/src/main/java/pl/cyfronet/s4e/data/repository/InvitationRepository.java, s4e-backend/src/main/java/pl/cyfronet/s4e/service/InvitationService.java, s4e-backend/src/test/java/pl/cyfronet/s4e/InvitationHelper.java, s4e-backend/src/test/java/pl/cyfronet/s4e/controller/InvitationControllerTest.java, s4e-web/src/app/views/settings/people/invitation-form/invitation-form.component.spec.ts, s4e-web/src/app/views/settings/people/invitation-form/invitation-form.component.ts, s4e-web/src/app/views/settings/people/person-list/person-list.component.ts, s4e-web/src/app/views/settings/people/state/invitation/invitation.factory.spec.ts, s4e-web/src/app/views/settings/people/state/invitation/invitation.model.ts, s4e-web/src/app/views/settings/people/state/invitation/invitation.service.spec.ts, s4e-web/src/app/views/settings/people/state/invitation/invitation.service.ts
**IMPORTANT!!! Includes changes of #643 !!!**
- Delete old invitation before creating new one
- Change endpoints to operate on invitations as unique of institution slug and email (UI and Backend)
Closes #660
=> [#660] Fix resending invitations and refactor endpoints to not operate on tokens

CHANGELOG.md, README.md, gs-gateway/pom.xml, gs-gateway/src/main/resources/application.properties, pom.xml, s4e-backend/pom.xml, s4e-backend/src/main/java/pl/cyfronet/s4e/LoggingMailSender.java, s4e-backend/src/main/resources/application.properties
Enable info, health and prometheus endpoints without authorization as
they don't contain sensitive information.
Generate git and build info during build, for /actuator/info to present.
Implement a noop LoggingMailSender::testConnection, so that
/actuator/health endpoint reports correct status in development.
Closes: #689.
=> [#689] Enable actuator endpoints

CHANGELOG.md, s4e-web/cypress/integration/settings/settings-breadcrumbs.spec.ts, s4e-web/cypress/integration/settings/settings-dashboard.spec.ts, s4e-web/cypress/page-objects/settings/settings-add-institution-form.po.ts, s4e-web/cypress/page-objects/settings/settings-breadcrumbs.po.ts, s4e-web/cypress/page-objects/settings/settings-dashboard.po.ts, s4e-web/cypress/page-objects/settings/settings-side-nav.po.ts, s4e-web/src/app/views/settings/admin-dashboard/admin-dashboard.component.html, s4e-web/src/app/views/settings/breadcrumb/breadcrumb.component.html, s4e-web/src/app/views/settings/dashboard/dashboard.component.html, s4e-web/src/app/views/settings/manage-institutions/institution-list/institution-list.component.ts, s4e-web/src/app/views/settings/settings.component.html
Dashboards (sanity check)
* Dashboards contain correct tiles
* User can access the appropriate dashboard according to his/her permissions/roles
Breadcrumb
* Should check breadcrumb generation for different users
Institution list
* ~~Should remove an institution~~ (bug: [Fix] DELETE on institution in API #709)
Closes #453
=> [#453] E2E tests for Settings

.gitignore, CHANGELOG.md, s4e-backend/src/main/java/pl/cyfronet/s4e/service/ProductCategoryService.java, s4e-backend/src/test/java/pl/cyfronet/s4e/service/ProductCategoryServiceTest.java
what happens?
Generated url is incorrect (double backslash and slash before file extension) static/categories//ico_earth/.svg
What will happen?
Generated url will look like: static/categories/ico_earth.svg
=> [Hotfix] Categories url builder for S3 icons

CHANGELOG.md, s4e-web/cypress/integration/settings/settings-user-profile.spec.ts, s4e-web/cypress/page-objects/settings/settings-institution-profile.po.ts, s4e-web/cypress/page-objects/settings/settings-user-profile.po.ts, s4e-web/src/app/state/session/session.query.ts, s4e-web/src/app/views/settings/guards/is-manager/is-manager.guard.ts, s4e-web/src/app/views/settings/intitution-profile/institution-profile.component.html, s4e-web/src/app/views/settings/intitution-profile/institution-profile.component.spec.ts, s4e-web/src/app/views/settings/intitution-profile/institution-profile.component.ts, s4e-web/src/app/views/settings/profile/profile.component.html, s4e-web/src/app/views/settings/profile/profile.component.spec.ts, s4e-web/src/app/views/settings/profile/profile.component.ts, s4e-web/src/app/views/settings/profile/profile.module.ts, s4e-web/src/app/views/settings/settings.routes.ts, s4e-web/src/app/views/settings/state/institution/institution.query.ts
- Separate user profile to tiles: user details, institutions user administrate, institutions where the user is a member
- Add show more, if there are more institutions than 3 and redirect to institutions list on click
- Redirect to institution profile on click on it (member can see institution details without action buttons and children institution) 
e2e
- Member shouldn't see action buttons and list of children institutions
- User should have the possibility to go to the institution profile
Closes #598
Beneath tasks will be continue in **UI rights system for different types of users #722**
- ~~Show rights to institutions in list~~
- ~~Hide from institution member actions buttons when go to institution profile~~
- ~~Add return to `mój profil` on institution profile page when visiting as …
=> [#598] Dynamic institutions name in settings panel

CHANGELOG.md, s4e-backend/src/main/java/pl/cyfronet/s4e/bean/Product.java
- [fix] set category from the request while creating a new product
What has happened?
For DB
Hibernate has replaced category with the default one while creating a new record.
For UI
All products are in this same category no matter of products seeds categories.
=> [Fix] Products seeds categories

CHANGELOG.md, s4e-backend/src/main/java/pl/cyfronet/s4e/service/SceneService.java, s4e-backend/src/main/resources/db/migration/V50__add_scene_timestamp_index.sql
I accidentally removed the index when renormalizing DB schema, affecting
query performance.
Enforce deterministic ordering when timestamps are equal.
Closes: #735.
=> Recreate DB index on scene.timestamp

CHANGELOG.md, docker-compose-test.yml, docker-compose.yml
This version contains `resources/minio/local-dataset-1` contents, needed
for new seeds to work.
Categories icons and legends are present there too.
Closes: #737.
=> [#737] Upgrade minio image to 1.2.0

CHANGELOG.md, docker-compose-test.yml, docker-compose.yml, pom.xml, s4e-backend/pom.xml, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/validation/JsonStringValidator.java, s4e-backend/src/main/java/pl/cyfronet/s4e/sync/Prototype.java, s4e-backend/src/main/java/pl/cyfronet/s4e/sync/ScenePersister.java, s4e-backend/src/main/java/pl/cyfronet/s4e/sync/context/JsonFileContext.java, s4e-backend/src/main/java/pl/cyfronet/s4e/sync/step/LoadProduct.java, s4e-backend/src/main/java/pl/cyfronet/s4e/sync/step/LoadSchemaOfCorrectType.java, s4e-backend/src/main/java/pl/cyfronet/s4e/sync/step/LoadValidatedJson.java, s4e-backend/src/main/java/pl/cyfronet/s4e/sync/step/VerifyAllArtifactsExist.java, s4e-backend/src/main/java/pl/cyfronet/s4e/sync/step/metadata/IngestFootprint.java, s4e-backend/src/test/java/pl/cyfronet/s4e/SchemaTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/sync/ScenePersisterTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/sync/step/LoadProductTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/sync/step/LoadSchemaOfCorrectTypeTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/sync/step/LoadValidatedJsonTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/sync/step/VerifyAllArtifactsExistTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/sync/step/metadata/IngestFootprintTest.java
Update postgis docker image to 13-3.0 as new postgresql version has been
released.
Update of justify and joy to new major versions required switching to
jakarta.json-api from javax.json, which is carried out throughout the
code.
Keep current GeoTools version until hibernate-spatial is compatible with
JTS 1.17.x (it introduces a breaking API change).
Make git-commit-id-plugin more forgiving: don't fail if .git directory
isn't available and don't fetch repo information.
=> Backend dependencies update - 2020-10

CHANGELOG.md, s4e-web/cypress.json, s4e-web/src/app/views/settings/dashboard/dashboard.component.html, s4e-web/src/app/views/settings/dashboard/dashboard.component.spec.ts, s4e-web/src/app/views/settings/dashboard/dashboard.component.ts, s4e-web/src/app/views/settings/intitution-profile/institution-profile.component.html, s4e-web/src/app/views/settings/intitution-profile/institution-profile.component.spec.ts, s4e-web/src/app/views/settings/intitution-profile/institution-profile.component.ts, s4e-web/src/app/views/settings/manage-institutions/add-institution/add-institution.component.scss, s4e-web/src/app/views/settings/manage-institutions/institution-list/institution-list.component.html, s4e-web/src/app/views/settings/manage-institutions/institution-list/institution-list.component.ts, s4e-web/src/app/views/settings/manage-institutions/parent-institution-modal/parent-institution-modal.component.spec.ts, s4e-web/src/app/views/settings/manage-institutions/parent-institution-modal/parent-institution-modal.component.ts, s4e-web/src/app/views/settings/profile/profile.component.html, s4e-web/src/app/views/settings/settings.component.html, s4e-web/src/app/views/settings/settings.component.ts, s4e-web/src/app/views/settings/state/institution/institution.query.ts
Functionalities tested on zkAdmin with additional institution Zarządzanie kryzysowe - Mazowieckie as a member (can be added from super admin account)
- When the user has only a member role in a selected institution in sidebar search
- Disable Ludzie button in settings sidebar
- Disable Zarządzaj ludźmi button in settings dashboard
- Hide dodaj dziecko action and list of children in institution profile
- Setting an institutions list
- Hide delete action when the user isnt super admin
- Hide edit action when the user has only member role to a specific institution
- Settings institution profile
- Hide action of children for which the user has only member role
Closes #722
=> [#722] Hide actions in settings by institution roles

.github/workflows/maven.yml, CHANGELOG.md
Replaces use of set-path command in github actions with using configuration file, which mitigates GHSA-mfwh-5m23-j46w.
The set-path command has been marked as deprecated and will be removed in upcoming github actions versions.
Fixes: #762.
=> [#762] Fix GHSA-mfwh-5m23-j46w github actions vulnerability

CHANGELOG.md, gs-gateway/src/main/java/pl/cyfronet/gsg/security/LayerSecurityGatewayFilter.java, gs-gateway/src/test/java/pl/cyfronet/gsg/security/LayerSecurityGatewayFilterTest.java
Add the missed requirement of an EUMETSAT license, that scenes with
hourly time resolution are available without license regardless of
ordinary temporal constraints.
Closes: #776.
=> [#776] Allow accessing on the hour EUMETSAT scenes in gs-gateway

CHANGELOG.md, s4e-backend/src/scripts/seed.sh
Moreover, redirect categories creating request result to $temp_file, so
that it's not output when there is no error and handled well when there
is one.
Closes: #774.
=> [#774] Output info about bucket and schemas in seed.sh

docker-compose-test.yml, docker-compose.yml
This image update apart from GeoServer update brings two changes:
- enabling of a low-level S3 cache,
- possible fix of the rectangular artifacts in WMS output.
Fixes #564 and provides basis for further cache optimization in #700.
=> Update GeoServer image to 1.5.0-GS2.18.0

s4e-backend/src/main/resources/db/migration/V54__set_default_to_eumetsat_license_fields.sql
The migration V53__add_eumetsat_license_fields.sql didn't set the
eumetsat_license field, leaving it effectively null after migration.
Reset the fields to false explicitly.
Fixes: #816.
=> [#816] Add missing eumetsat_license values

s4e-backend/src/main/java/pl/cyfronet/s4e/bean/AppUser.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/request/RegisterRequest.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/response/AppUserResponse.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/validation/CountryCode.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/validation/CountryCodeValidator.java, s4e-backend/src/main/java/pl/cyfronet/s4e/db/seed/SeedUsers.java, s4e-backend/src/main/resources/db/migration/V55__add_appuser_domain_usage_country_fields.sql, s4e-backend/src/main/resources/messages_pl_PL.properties, s4e-backend/src/test/java/pl/cyfronet/s4e/controller/AppUserControllerTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/controller/validation/CountryCodeValidatorTest.java
Add domain, usage and country fields to app_user table, handle them
during registration and return them in user info.
Make the fields optional for now, so that front-end can be developed in
the meantime.
Closes: #835.
=> [#835] Add scientific domain to AppUser

docker-compose-test.yml, docker-compose.yml, gs-gateway/Dockerfile, gs-gateway/pom.xml, pom.xml, s4e-backend/Dockerfile, s4e-backend/pom.xml
Spring boot 2.4.0-RC1 version, to hop on the new version before going to
production. I haven't noticed any regressions, except gs-gateway, which
needs to use 2.4.0-M4 for now.
Caffeine has version management in spring-boot, so it's not necessary to manage its version independently.
lombok-mapstruct-binding dependency is required since Lombok 1.18.16 for cooperation with MapStruct.
=> Dependencies update - 2020.11

s4e-backend/src/main/java/pl/cyfronet/s4e/properties/FileStorageProperties.java, s4e-backend/src/main/java/pl/cyfronet/s4e/properties/MailProperties.java, s4e-backend/src/main/java/pl/cyfronet/s4e/properties/S3Properties.java, s4e-backend/src/main/java/pl/cyfronet/s4e/service/InstitutionService.java, s4e-backend/src/main/java/pl/cyfronet/s4e/service/ProductCategoryService.java, s4e-backend/src/main/java/pl/cyfronet/s4e/service/SavedViewService.java, s4e-backend/src/test/java/pl/cyfronet/s4e/controller/SavedViewControllerTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/service/ProductCategoryServiceTest.java, s4e-backend/src/test/resources/application-test.properties
Separate static bucket name from path prefix, as they may differ.
Add validation of several properties for more robust configuration.
Fixes: #855.
=> [#855] Improve property validation and handle custom static path

s4e-backend/src/main/java/pl/cyfronet/s4e/config/AmqpConfig.java, s4e-backend/src/main/java/pl/cyfronet/s4e/data/repository/SceneRepository.java, s4e-backend/src/main/java/pl/cyfronet/s4e/service/SceneService.java, s4e-backend/src/main/java/pl/cyfronet/s4e/sync/NotificationDispatcher.java, s4e-backend/src/main/java/pl/cyfronet/s4e/sync/QueueReceiver.java, s4e-backend/src/test/java/pl/cyfronet/s4e/sync/QueueReceiverIntegrationTest.java
Add a NotificationDispatcher with the eventType based handling logic,
which includes removing a scene for s3:ObjectDeleted:Delete eventType.
Warnings are raised on purpose to make problems with queue configuration
easier to find.
Closes: #858
=> [#858] Handle delete S3 object notifications

s4e-web/src/app/views/map-view/map-view.component.ts, s4e-web/src/app/views/map-view/state/product/product.service.spec.ts, s4e-web/src/app/views/map-view/state/product/product.service.ts, s4e-web/src/app/views/map-view/state/scene/scene.service.spec.ts, s4e-web/src/app/views/map-view/state/scene/scene.service.ts, s4e-web/src/app/views/map-view/state/scene/scene.store.service.ts, s4e-web/src/app/views/map-view/state/scene/timeline.service.spec.ts, s4e-web/src/app/views/map-view/state/scene/timeline.service.ts, s4e-web/src/app/views/map-view/timeline/timeline.component.html, s4e-web/src/app/views/map-view/timeline/timeline.component.scss, s4e-web/src/app/views/map-view/timeline/timeline.component.spec.ts, s4e-web/src/app/views/map-view/timeline/timeline.component.ts, s4e-web/src/app/views/map-view/view-manager/view-manager.component.spec.ts, s4e-web/src/app/views/map-view/view-manager/view-manager.component.ts, s4e-web/src/environments/environment.common.ts
Where to find feature?
1. Go to `/map`
2. Turn on any of products
3. Click button `Na żywo` near timeline
- Add checkbox on `/map` page to display the latest scenes of the product (send a request for new scenes every 15 minutes)
- Reload the latest scene on the map, when new occur
- When live mode is turn on ask if user is sure while
- changing between products
- trying to change scene (by hour/date or on time axis)
Closes #799
=> [#799] Add live scene loading

s4e-web/src/app/views/settings/intitution-profile/institution-profile.component.html, s4e-web/src/app/views/settings/state/institution/institution.service.ts
- Skip incorrect transformation of list into tree (this issue was blocker while GETing insitutions)
- Go to people of certain institution in /settings/institution (redirect to a wrong institution people)
=> [Hotfix] Invitations flow

s4e-backend/src/main/java/pl/cyfronet/s4e/geoserver/op/GeoServerOperations.java
For some reason GeoServer started to return 404 instead of 500 for a
non-existent tile layer in gh-actions pipelines causing two tests to
fail:
GeoServerOperationsIntegrationTest$TileLayers.shouldCreateAndDeleteTileLayer
GeoServerServiceIntegrationTest.shouldAddStoreAndLayer
Make the existence checking methods in GeoServerOperations return false
on any error status code instead of throwing runtime exceptions.
Fixes: #906.
=> [#906] Account for GeoServer inconsistency in not found handling

s4e-backend/src/main/java/pl/cyfronet/s4e/api/OSearchController.java, s4e-backend/src/main/java/pl/cyfronet/s4e/config/SecurityConfig.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/SearchController.java, s4e-backend/src/main/java/pl/cyfronet/s4e/data/repository/SceneRepositoryExt.java, s4e-backend/src/main/java/pl/cyfronet/s4e/data/repository/SceneRepositoryImpl.java, s4e-backend/src/main/java/pl/cyfronet/s4e/data/repository/query/PreparedStatementBuilder.java, s4e-backend/src/main/java/pl/cyfronet/s4e/data/repository/query/QueryBuilder.java, s4e-backend/src/main/java/pl/cyfronet/s4e/data/repository/query/QueryBuilderImpl.java, s4e-backend/src/main/java/pl/cyfronet/s4e/data/repository/query/QueryDecorator.java, s4e-backend/src/main/java/pl/cyfronet/s4e/data/repository/query/QueryEnding.java, s4e-backend/src/main/java/pl/cyfronet/s4e/service/SearchService.java, s4e-backend/src/test/java/pl/cyfronet/s4e/api/OSearchControllerTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/controller/SearchControllerTest.java
endpoint /count for front-end and API 
works like search but with fewer parameters.
both endpoints return count(number-long) for query(q=? or params)
Closes #907
=> [#907] Add endpoint count for front-search and API

s4e-backend/src/main/java/pl/cyfronet/s4e/admin/license/AdminCreateLicenseGrantRequest.java, s4e-backend/src/main/java/pl/cyfronet/s4e/admin/license/AdminLicenseGrantController.java, s4e-backend/src/main/java/pl/cyfronet/s4e/admin/license/AdminLicenseGrantMapper.java, s4e-backend/src/main/java/pl/cyfronet/s4e/admin/license/AdminLicenseGrantResponse.java, s4e-backend/src/main/java/pl/cyfronet/s4e/admin/license/AdminUpdateLicenseGrantRequest.java, s4e-backend/src/main/java/pl/cyfronet/s4e/admin/license/LicenseGrantService.java, s4e-backend/src/main/java/pl/cyfronet/s4e/bean/LicenseGrant.java, s4e-backend/src/main/java/pl/cyfronet/s4e/config/SecurityConfig.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/LicenseGrantController.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/response/LicenseGrantResponse.java, s4e-backend/src/main/java/pl/cyfronet/s4e/data/repository/InstitutionRepository.java, s4e-backend/src/main/java/pl/cyfronet/s4e/data/repository/LicenseGrantRepository.java, s4e-backend/src/main/java/pl/cyfronet/s4e/ex/BindingResultException.java, s4e-backend/src/main/java/pl/cyfronet/s4e/ex/ErrorHandler.java, s4e-backend/src/main/java/pl/cyfronet/s4e/ex/ErrorHandlerHelper.java, s4e-backend/src/main/java/pl/cyfronet/s4e/ex/LicenseGrantException.java, s4e-backend/src/main/java/pl/cyfronet/s4e/ex/QueryException.java, s4e-backend/src/main/java/pl/cyfronet/s4e/ex/product/ProductValidationException.java, s4e-backend/src/main/java/pl/cyfronet/s4e/license/LicensePermissionEvaluator.java, s4e-backend/src/main/java/pl/cyfronet/s4e/license/types/PrivateLicense.java, s4e-backend/src/main/java/pl/cyfronet/s4e/license/types/WritableLicense.java, s4e-backend/src/main/java/pl/cyfronet/s4e/security/AppUserDetailsService.java, s4e-backend/src/main/java/pl/cyfronet/s4e/security/SecurityConstants.java, s4e-backend/src/main/resources/db/migration/V59__add_owner_to_license_grant_table.sql, s4e-backend/src/main/resources/messages_pl_PL.properties, s4e-backend/src/test/java/pl/cyfronet/s4e/admin/license/AdminLicenseGrantControllerTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/controller/LicenseGrantControllerTest.java
Add endpoints for management of LicenseGrants, so that admin can manage
the grants from admin API and institution admin can manage read access
only.
Improve handling of BindingResult errors - introduce a single interface
which differentiates exceptions with such information.
Add WritableLicense interface, which is meant to be implemented by
licenses which can be managed using grants.
Closes: #773.
=> [#773] Add private product access management

s4e-web/src/app/utils/error-interceptor/error.interceptor.ts, s4e-web/src/app/views/map-view/sentinel-search/search-result-modal/search-result-modal.component.html, s4e-web/src/app/views/map-view/sentinel-search/search-result-modal/search-result-modal.component.ts, s4e-web/src/app/views/map-view/sentinel-search/search-results/search-results.component.html, s4e-web/src/app/views/map-view/sentinel-search/search-results/search-results.component.ts, s4e-web/src/app/views/map-view/sentinel-search/sentinel-search.component.html, s4e-web/src/app/views/map-view/sentinel-search/sentinel-search.component.ts, s4e-web/src/app/views/map-view/state/sentinel-search/sentinel-search.model.ts, s4e-web/src/app/views/map-view/state/sentinel-search/sentinel-search.query.spec.ts, s4e-web/src/app/views/map-view/state/sentinel-search/sentinel-search.query.ts, s4e-web/src/app/views/map-view/state/sentinel-search/sentinel-search.service.spec.ts, s4e-web/src/app/views/map-view/state/sentinel-search/sentinel-search.service.ts, s4e-web/src/app/views/map-view/state/sentinel-search/sentinel-search.store.ts
* Handle anonymous user handling of search result download
* Preserve sentinel search params between page reloads and link pasting
1. As an anonymous user search for sentinel scenes and click download button
2. you should be redirected to login page with notification informing you about the fact that those resources are only for authorized users
3. Refresh page (this will ensure that this feature does not depend on JS in memory page state)
3. log in
4. you should be redirected back to map with search drawer open
5. click download, the file should download
Repeat those steps for download button in the search result metadata modal.
Closes: #928
=> [#928] Handle anonymous user trying to download files

README.md, s4e-backend/src/main/java/pl/cyfronet/s4e/config/SecurityConfig.java, s4e-backend/src/main/resources/application-production.properties, s4e-backend/src/main/resources/application.properties, s4e-backend/src/test/java/pl/cyfronet/s4e/SwaggerTest.java, s4e-web/src/app/views/apihowto/apihowto.component.html, s4e-web/src/app/views/apihowto/apihowto.component.scss
The docs are accessible either by
- /api/v1/docs: OpenAPIv3 json,
- /api/v1/docs.yaml: OpenAPIv3 yaml,
- /api/v1/docs.html: swagger-ui.
Update API how-to description.
Closes: #943.
=> Expose OpenAPI docs

s4e-backend/src/main/java/pl/cyfronet/s4e/config/SecurityConfig.java, s4e-backend/src/main/java/pl/cyfronet/s4e/properties/SceneArtifactsProperties.java, s4e-backend/src/main/resources/application.properties, s4e-backend/src/test/java/pl/cyfronet/s4e/controller/SceneControllerTest.java
Add property `scene.artifacts.internal-download-whitelist` with a set of
Scene artifact names which will be open for unauthenticated users to
download (doesn't apply to private Products).
Closes: #945.
=> [#945] Whitelist selected artifact download

s4e-web/src/app/views/map-view/sentinel-search/search-result-modal/search-result-modal.component.html, s4e-web/src/app/views/map-view/sentinel-search/search-result-modal/search-result-modal.component.scss, s4e-web/src/app/views/map-view/sentinel-search/search-result-modal/search-result-modal.component.ts, s4e-web/src/app/views/map-view/sentinel-search/search-results/search-results.component.html, s4e-web/src/app/views/map-view/sentinel-search/search-results/search-results.component.scss, s4e-web/src/app/views/map-view/sentinel-search/search-results/search-results.component.spec.ts, s4e-web/src/app/views/map-view/sentinel-search/sentinel-search.component.ts, s4e-web/src/app/views/map-view/state/sentinel-search/sentinel-search.factory.spec.ts, s4e-web/src/app/views/map-view/state/sentinel-search/sentinel-search.model.ts, s4e-web/src/app/views/map-view/state/sentinel-search/sentinel-search.service.spec.ts, s4e-web/src/app/views/map-view/state/sentinel-search/sentinel-search.service.ts
* Add thumbnails to sentinel search results & to details metadata
* Add artifacts table with download buttons to details modal
Currently the artifact download api requires authorized user. So searching when anonymous will show blank images, but there is an issue #945 and after it is resolved that part of the feature should naturally work.
Closes: #931
=> [#931] Artifact download and image thumbnails to sentinel results

s4e-backend/src/main/java/pl/cyfronet/s4e/service/AppUserService.java, s4e-backend/src/test/java/pl/cyfronet/s4e/controller/AppUserControllerTest.java
rewrite removeRoles. dont use service, just delete every userrole directly.
user with multiple roles should be forgotten.
closes #964
=> [#964] Fix forget-me endpoint

s4e-web/src/app/views/map-view/map-view.component.ts, s4e-web/src/app/views/map-view/state/map/map.model.ts, s4e-web/src/app/views/map-view/state/map/map.query.ts, s4e-web/src/app/views/map-view/state/map/map.service.ts
* When user closes description this is persisted in the local storage,
so that subsequent page reloads preserve that state
=> Product description is shown by default

README.md, s4e-backend/src/main/java/pl/cyfronet/s4e/db/seed/SeedUsers.java, s4e-backend/src/main/java/pl/cyfronet/s4e/service/AppUserMapper.java, s4e-backend/src/test/java/pl/cyfronet/s4e/controller/AppUserControllerTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/controller/ExpertHelpControllerTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/controller/ShareLinkControllerTest.java
It makes it easier to access products managed by a user for example.
It could also replace the output of users/me.roles, but needs more
parsing.
Add a property seed.users.force, which, if set to true, will force
regardless of any user existence in the DB.
=> Return actual authorities in /users/me and don't force re-seed users by default

s4e-backend/src/main/java/pl/cyfronet/s4e/admin/sync/api/ErrorsResponse.java, s4e-backend/src/main/java/pl/cyfronet/s4e/admin/sync/api/RunningDetailsMapper.java
Serializing an Exception for each Error causes the produced response to
be unwieldy in certain cases.
Fixes: #1009.
=> [#1009] Stringify SyncJob ErrorsResponse cause

backend-e2e.env, backend-production.env.template, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/ConfigController.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/response/ConfigResponse.java, s4e-backend/src/main/java/pl/cyfronet/s4e/properties/OsmProperties.java, s4e-backend/src/main/resources/application-development.properties, s4e-backend/src/test/java/pl/cyfronet/s4e/controller/ConfigControllerTest.java, s4e-backend/src/test/resources/application-test.properties, s4e-web/src/app/app.configuration.spec.ts, s4e-web/src/app/app.configuration.ts, s4e-web/src/app/views/map-view/map/map.component.spec.ts, s4e-web/src/app/views/map-view/map/map.component.ts
Add property osm.url, that configures the OSM url used by front-end to
fetch tiles.
This allows fetching tiles from other domain or several domains, for
example if `osm.url={a-c}.osm/...` then a.osm, b.osm, c.osm domains
will be used.
Closes: #1005.
=> [#1005] Make OSM url configurable

s4e-backend/src/main/java/pl/cyfronet/s4e/controller/AuthController.java, s4e-backend/src/main/java/pl/cyfronet/s4e/properties/JwtProperties.java, s4e-backend/src/test/java/pl/cyfronet/s4e/controller/AuthControllerTest.java, s4e-web/nginx-e2e.conf, s4e-web/nginx.conf
Depending on the property jwt.cookie.domain the cookie's domain is
either fetched from header Host (in case the property is null or blank)
and set to the value from the property otherwise.
Closes: #1006.
=> [#1006] Set domain for authorization cookie

s4e-backend/src/main/resources/db/migration/V65__performance.sql
Generate s3path on insert to scene table and mark the generating
functions as parallel safe, so that query planner can generate parallel
plans with them.
Recreate the scene views structure, removing the unnecessary
scene_extended view on the way.
Closes: #1019.
=> [#1019] Improve GetCapabilities performance

s4e-backend/src/main/java/pl/cyfronet/s4e/service/MailService.java
Populate the header's value based on Spring MailProperties, so it is
consistent with auto-configuration of the JavaMailSender.
Leaving the field empty causes some SMTP servers to reject such requests.
Fixes: #1017.
=> [#1017] Set From outgoing mail header

gs-gateway/src/main/resources/application.properties, s4e-web/nginx-e2e.conf, s4e-web/nginx.conf
The spring-cloud-gateway by default appends the domains on the path, but
GeoServer doesn't handle multi-valued headers, leading to bad domain,
e.g. `<outside-domain>:443,gs-gateway:8090` instead of just
`<outside-domain>:443`.
Closes: #1025.
=> [#1025] Disable GS-Gateway X-Forwarded headers handling

s4e-backend/src/main/java/pl/cyfronet/s4e/admin/scene/AdminSceneMapper.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/SceneController.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/mapper/SceneMapper.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/response/SceneResponse.java, s4e-backend/src/test/java/pl/cyfronet/s4e/controller/SceneControllerTest.java
Move mapping operations to a separate mapper.
Add polygon to SceneResponse, its mapping and a test for correct
operation.
Promote a footprint mapping exception to WARN log call in
AdminSceneMapper, as it's an erroneous behaviour which should be caught.
Use the same log level in new SceneMapper footprint mapping.
Correct the field order in SceneResponse to match with the Scene bean.
Closes: #1022.
=> [#1022] Add polygon to SceneResponse

s4e-backend/src/main/java/pl/cyfronet/s4e/data/repository/PasswordResetRepository.java, s4e-backend/src/main/java/pl/cyfronet/s4e/service/PasswordService.java, s4e-backend/src/test/java/pl/cyfronet/s4e/service/PasswordServiceTest.java
Don't remove a ResetPassword if it exists on re-request.
Fixes: #1030.
=> [#1030] Allow resending password reset token

s4e-backend/src/main/java/pl/cyfronet/s4e/admin/scene/AdminSceneMapper.java, s4e-backend/src/main/java/pl/cyfronet/s4e/api/SearchApiParams.java, s4e-backend/src/main/java/pl/cyfronet/s4e/api/SearchConverter.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/mapper/SceneMapper.java, s4e-backend/src/main/java/pl/cyfronet/s4e/data/repository/query/QueryBuilderImpl.java, s4e-backend/src/main/java/pl/cyfronet/s4e/util/GeometryUtil.java, s4e-backend/src/test/java/pl/cyfronet/s4e/TestGeometryHelper.java, s4e-backend/src/test/java/pl/cyfronet/s4e/api/OSearchControllerTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/controller/SceneControllerTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/data/repository/query/QueryBuilderTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/sync/SceneAcceptorIntegrationTest.java, s4e-web/src/app/views/apihowto/apihowto.component.html
In endpoints always return and require coordinates in EPSG:4326 lat/long
order.
Update apihowto to include this.
Internally, leave long/lat in some cases (metadata for example).
Always return coordinates with 5 significant digits: it corresponds to
around 1m of precision, which is more than necessary in our case.
Improve parsing of geometry params in OSearch API.
Fixes: #1034.
=> [#1034] Homogenize lat/long order

s4e-backend/src/main/java/pl/cyfronet/s4e/data/repository/SceneRepositoryImpl.java, s4e-backend/src/main/java/pl/cyfronet/s4e/data/repository/SceneRowMapper.java, s4e-backend/src/main/java/pl/cyfronet/s4e/data/repository/query/PreparedStatementBuilder.java
A checked exception cannot be thrown from a PreparedStatementBuilder, so
I wrap a QueryException in IAE, and unwrap it later on.
Fixes: #1043.
=> [#1043] Use current connection when executing scene search requests

s4e-backend/src/main/java/pl/cyfronet/s4e/data/repository/SceneRepositoryImpl.java, s4e-backend/src/main/java/pl/cyfronet/s4e/data/repository/SceneRowMapper.java, s4e-backend/src/main/java/pl/cyfronet/s4e/data/repository/query/PreparedStatementBuilder.java
Backport of #1045.
A checked exception cannot be thrown from a PreparedStatementBuilder, so
I wrap a QueryException in IAE, and unwrap it later on.
=> [v16.2.x] [#1043] Use current connection when executing scene search requests

s4e-backend/src/main/java/pl/cyfronet/s4e/bean/Product.java, s4e-backend/src/main/java/pl/cyfronet/s4e/bean/Scene.java, s4e-backend/src/test/java/pl/cyfronet/s4e/admin/product/AdminProductControllerTest.java
This avoids running costly triggers when relevant fields aren't updated.
Fixes: #1050.
=> [#1050] Use @DynamicUpdate for Product and Scene

gs-gateway/src/main/resources/logback.xml, gs-gateway/src/main/resources/sentry.properties, s4e-backend/src/main/resources/logback.xml, s4e-backend/src/main/resources/sentry.properties
The sentry.properties files are not necessary, and only generate
stacktraces in runtime. If removed, Sentry issues a log entry at WARN
level anyway.
Set a logback timestamp pattern which complies with ISO8601, see e.g. SO
https://stackoverflow.com/a/23096247/1778478 for more info (beware
though, as there's an error in this SO answer - the fraction of a
second should be dot (.) and not comma (,) delimited).
Fixes: #716.
=> [#716] Remove sentry.properties and correct log timestamp pattern

s4e-backend/seed-configs/seed-1/products.json, s4e-backend/src/main/java/pl/cyfronet/s4e/config/QueryConfig.java, s4e-backend/src/main/java/pl/cyfronet/s4e/data/repository/query/QueryBuilderImpl.java, s4e-backend/src/main/java/pl/cyfronet/s4e/data/repository/query/QueryDecorator.java, s4e-backend/src/main/java/pl/cyfronet/s4e/data/repository/query/QueryEnding.java, s4e-backend/src/main/java/pl/cyfronet/s4e/data/repository/query/QueryGeometry.java, s4e-backend/src/main/java/pl/cyfronet/s4e/data/repository/query/QueryNumber.java, s4e-backend/src/main/java/pl/cyfronet/s4e/data/repository/query/QueryProductType.java, s4e-backend/src/main/java/pl/cyfronet/s4e/data/repository/query/QueryText.java, s4e-backend/src/main/java/pl/cyfronet/s4e/data/repository/query/QueryTime.java, s4e-backend/src/main/java/pl/cyfronet/s4e/search/SentinelSearchConfigSupplier.java, s4e-backend/src/main/resources/db/migration/V66__drop_idx_product_type.sql, s4e-backend/src/test/java/pl/cyfronet/s4e/api/OSearchControllerTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/controller/SearchControllerTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/data/repository/query/QueryBuilderTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/service/SearchServiceTest.java
Switch to using Product.name by modifying the issued query.
Move handling of the parameter from QueryText to a new QueryProductType
class.
Drop the index on metadata_content.product_type, as it's no longer used
in search queries.
Pre-build the static select and count queries in static initializer of
QueryBuilderImpl.
Implement various IDE suggested code improvements.
Consolidate query creation, so that all appended portions start with a
space, in this way there's no need to leave trailing spaces in some
places.
Use f_cast_isots instead of directly using to_timestamp, removing the
duplication of the date format and using the same function which on
which index is created.
Closes: #1039.
=> [#1039] Search based on Product.name instead of metadata.product_type

s4e-backend/src/main/java/pl/cyfronet/s4e/api/ODataController.java, s4e-backend/src/test/java/pl/cyfronet/s4e/SceneTestHelper.java, s4e-backend/src/test/java/pl/cyfronet/s4e/api/ODataControllerTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/api/OSearchControllerTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/controller/SearchControllerTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/service/SearchServiceTest.java
Before, a NoSuchElementException was thrown in such case, resulting in
500 status code.
Fixes: #1066.
In a separate commit I refactor the SceneTestHelper to directly create Scene and MetadataContent JsonNodes, so that it's easier to manipulate it in tests later.
=> [#1066] Return 404 if an artifact with zip extension is missing

s4e-backend/src/main/java/pl/cyfronet/s4e/service/MailService.java
In development profile, this results in a IAE thrown from
MimeMessageHelper::setFrom, so instead refrain from setting the header
in such case.
Fixes: #1071.
=> [#1071] Don't set From header if null in MailService

s4e-backend/src/main/java/pl/cyfronet/s4e/sync/NotificationDispatcher.java, s4e-backend/src/main/java/pl/cyfronet/s4e/sync/QueueReceiver.java, s4e-backend/src/test/java/pl/cyfronet/s4e/sync/NotificationDispatcherTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/sync/QueueReceiverTest.java
Attempt to catch all RuntimeExceptions in QueueReceiver and handle nulls
in NotificationDispatcher to avoid getting stuck in an endless loop.
Fixes: #1074.
=> [#1074] Better null and runtime exception handling in Scene registration

README.md, s4e-backend/src/main/java/pl/cyfronet/s4e/Constants.java, s4e-backend/src/main/java/pl/cyfronet/s4e/security/AppUserDetailsService.java, s4e-backend/src/test/java/pl/cyfronet/s4e/security/AppUserDetailsServiceTest.java
Add LICENSE_EUMETSAT to user's authorities if she already has an
authority from an eumetsat_authority_whitelist DB property.
In case no such property is defined then default to
ROLE_MEMBER_ZK and ROLE_MEMBER_PAK.
By using the property the role range can be narrowed down.
Closes: #1103.
=> [#1103] Add EUMETSAT license if user already has a defined authority

.github/workflows/draft-release.yml, .github/workflows/e2e.yml, .github/workflows/test.yml, gs-gateway/Dockerfile, gs-gateway/pom.xml, pom.xml, s4e-backend/Dockerfile, s4e-backend/pom.xml
Bump sentry to 1.7.30, although current Sentry suggests 1.7.5.
Judging from sentry-java changelog, minor versions introduced no
breaking changes.
Switch to ubuntu-20.04 flavour as it's being rolled-out to ubuntu-latest
anyway and we could suffer an unexpected update.
=> Dependencies and workflow flavour update - 2021.02

s4e-backend/src/main/java/pl/cyfronet/s4e/LoggingMailSender.java, s4e-backend/src/main/java/pl/cyfronet/s4e/properties/MailProperties.java, s4e-backend/src/main/resources/application-development.properties
The property is named: `mail.logging-mail-sender.enable`, and by default
it is set to false (only in profile development, true).
The LogginMailSender may be undesirable in development profile when
running e2e tests (and you want to connect to an actual SMTP server).
Switching to profile production in e2e tests leads to timeouts in some
difficult to correct places and it may be a topic for further
optimization.
Closes: #1111.
=> [#1111] Make LoggingMailSender registration configurable by a property

README.md, s4e-backend/src/main/resources/application-development.properties, s4e-backend/src/main/resources/application.properties
It doesn't disable itself when @EnableRabbit is not set, it has to be
configured manually.
Fixes: #1113.
=> [#1113] Disable RabbitHealthIndicator by default

s4e-backend/src/main/java/pl/cyfronet/s4e/api/SearchConverter.java, s4e-backend/src/test/java/pl/cyfronet/s4e/api/OSearchControllerTest.java
Require the orderby field to have two space-separated segments, ignore
it otherwise to avoid NPE.
Fixes: #1099.
=> [#1099] Handle incorrect input of orderby in SearchConverter

s4e-backend/src/main/java/pl/cyfronet/s4e/security/JwtAuthenticationFilter.java, s4e-backend/src/test/java/pl/cyfronet/s4e/SecurityTest.java
As JJWT checks for token blankness, it causes an internal error status
code to be returned for the end user, instead of just treating it as
missing authorization.
Fixes: #1100.
=> [#1100] Handle blank bearer token in JwtAuthenticationFilter

s4e-backend/pom.xml, s4e-backend/src/main/java/pl/cyfronet/s4e/Application.java, s4e-backend/src/main/java/pl/cyfronet/s4e/admin/sync/task/SyncJobManager.java, s4e-backend/src/main/java/pl/cyfronet/s4e/bean/SyncRecord.java, s4e-backend/src/main/java/pl/cyfronet/s4e/config/AmqpConfig.java, s4e-backend/src/main/java/pl/cyfronet/s4e/config/QueryConfig.java, s4e-backend/src/main/java/pl/cyfronet/s4e/config/SceneSynchronizationConfig.java, s4e-backend/src/main/java/pl/cyfronet/s4e/config/SecurityConfig.java, s4e-backend/src/main/java/pl/cyfronet/s4e/config/SyncJobsConfig.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/SyncRecordController.java, s4e-backend/src/main/java/pl/cyfronet/s4e/data/repository/SyncRecordRepository.java, s4e-backend/src/main/java/pl/cyfronet/s4e/sync/ContextRecorder.java, s4e-backend/src/main/java/pl/cyfronet/s4e/sync/Error.java, s4e-backend/src/main/java/pl/cyfronet/s4e/sync/LoggingAcceptor.java, s4e-backend/src/main/java/pl/cyfronet/s4e/sync/NotificationDispatcher.java, s4e-backend/src/main/java/pl/cyfronet/s4e/sync/PipelineFactory.java, s4e-backend/src/main/java/pl/cyfronet/s4e/sync/SceneAcceptorImpl.java, s4e-backend/src/main/java/pl/cyfronet/s4e/sync/context/Context.java, s4e-backend/src/main/java/pl/cyfronet/s4e/sync/step/metadata/Persist.java, s4e-backend/src/main/resources/db/migration/V70__add_sync_log_table.sql, s4e-backend/src/test/java/pl/cyfronet/s4e/TestDbHelper.java, s4e-backend/src/test/java/pl/cyfronet/s4e/TestJwtUtil.java, s4e-backend/src/test/java/pl/cyfronet/s4e/admin/sync/task/SyncJobManagerTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/sync/NotificationDispatcherTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/sync/QueueReceiverIntegrationTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/sync/SceneAcceptorIntegrationTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/sync/log/SyncRecordControllerTest.java
Use QueryDSL to expose a flexible search endpoint.
Add an authority OP_SYNC_RECORD_READ to allow access to this endpoint,
it can be assigned to a user by an admin.
Admin can also delete records by an arbitrary search query.
Populate records in SyncRecorder.
To get all the necessary data I had to modify the Context to accommodate
extra data.
Closes: #1096.
=> [#1096] Add SyncRecordController to expose synchronization history

README.md, s4e-backend/src/main/java/pl/cyfronet/s4e/Constants.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/ConfigController.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/response/ConfigResponse.java, s4e-backend/src/main/java/pl/cyfronet/s4e/db/seed/SeedHelpdeskConfig.java, s4e-backend/src/main/java/pl/cyfronet/s4e/helpdesk/HelpdeskConfigSupplier.java, s4e-backend/src/test/java/pl/cyfronet/s4e/controller/ConfigControllerTest.java
The properties can be defined by setting `helpdesk_config` DB property
in the format `<key>=<value>(,<key>=<value>)+`.
In development seed its value in SeedHelpdeskConfig.
Fixes: #1121.
=> [#1121] Expose helpdesk properties in configuration response

s4e-backend/src/main/java/pl/cyfronet/s4e/api/ODataController.java, s4e-backend/src/main/java/pl/cyfronet/s4e/api/ResponseExtender.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/mapper/SceneMapper.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/response/SceneResponse.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/response/SearchResponse.java, s4e-backend/src/main/java/pl/cyfronet/s4e/util/ZipArtifact.java, s4e-backend/src/test/java/pl/cyfronet/s4e/util/ZipArtifactTest.java
Add the hasZipArtifact field to responses, so that front-end can use it to determine if it can call the generic download endpoint without 404 risk.
Closes: #1137.
=> [#1137] Add hasZipArtifact field to scene responses

s4e-backend/src/main/java/pl/cyfronet/s4e/config/OpenApiConfig.java, s4e-backend/src/main/resources/application.properties
As per https://github.com/springdoc/springdoc-openapi/pull/1079, when
using group configs the customizers have to be specified in the
GroupedOpenApi bean declarations.
Since we depend on the QueryDsl customizer, the group configs had to be
moved to the java config from properties.
=> Expand QueryDsl endpoint argument to OpenAPI parameters

README.md, s4e-backend/src/main/java/pl/cyfronet/s4e/Constants.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/ConfigController.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/response/ConfigResponse.java, s4e-backend/src/main/java/pl/cyfronet/s4e/db/seed/SeedAnalyticsConfig.java, s4e-backend/src/main/java/pl/cyfronet/s4e/kvconfig/KeyValueConfigSupplier.java, s4e-backend/src/test/java/pl/cyfronet/s4e/controller/ConfigControllerTest.java
This is an extension based on the preexisting implementation for the
helpdesk configuration.
If we are to extend the set of keys further it could make sense to
generalize the solution.
=> [#1144] Expose analytics properties in configuration response

gs-gateway/pom.xml, pom.xml, s4e-backend/src/main/java/pl/cyfronet/s4e/geoserver/op/GeoServerOperations.java
Unirest 4 removes the socket timeout property, only the connect timeout
is supported.
=> Dependencies update - 2021.03

s4e-backend/src/main/java/pl/cyfronet/s4e/service/PasswordService.java, s4e-backend/src/test/java/pl/cyfronet/s4e/controller/PasswordControllerTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/service/PasswordServiceTest.java
Fixed by enabling user during password reset.
Closes #1107
=> [#1107] Fix reset password for not enabled user

s4e-web/src/app/views/map-view/map-view.component.ts, s4e-web/src/app/views/map-view/sentinel-search/search-results/search-results.component.html, s4e-web/src/app/views/map-view/sentinel-search/search-results/search-results.component.spec.ts
- QuickLook image background at /map/sentinel-search (after search) is centered
and cover whole div (fix the issue when Quicklook is mostly black icon)
- now on the first product selection loaded scene will be displayed
Closes #1168, #1149
=> [#1168][#1149] Fix quicklook image visibility, fix not loading scene on first product selection

s4e-backend/src/main/java/pl/cyfronet/s4e/sync/NotificationDispatcher.java, s4e-backend/src/test/java/pl/cyfronet/s4e/sync/NotificationDispatcherTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/sync/QueueReceiverIntegrationTest.java
Ceph in some cases generates s3:ObjectCreated:Copy notifications, even
though :Post would be more appropriate (probably when overwriting an
object).
Handle the incorrect event to accommodate for this behaviour and not
have to run sync manually in such cases.
Closes: #1189.
=> [#1189] Handle s3:ObjectCreated:Copy S3 notifications

README.md, gs-gateway/src/main/java/pl/cyfronet/gsg/counter/GetMapRequestCounterFilter.java, gs-gateway/src/test/java/pl/cyfronet/gsg/counter/GetMapRequestCounterFilterTest.java
This is to ignore monitoring calls from zabbix.
=> Allow to disable metrics for certain GetMap requests

.github/workflows/e2e.yml, .github/workflows/test.yml, .mvn/wrapper/maven-wrapper.properties, README.md, backend-development.env, backend-e2e.env, backend-production.env.template, gs-gateway/Dockerfile, gs-gateway/pom.xml, gs-gateway/src/main/java/pl/cyfronet/gsg/GsGatewayApplication.java, gs-gateway/src/main/resources/logback.xml, pom.xml, s4e-backend/.gitignore, s4e-backend/Dockerfile, s4e-backend/pom.xml, s4e-backend/src/main/java/pl/cyfronet/s4e/Application.java, s4e-backend/src/main/java/pl/cyfronet/s4e/api/SearchConverter.java, s4e-backend/src/main/resources/application-development.properties, s4e-backend/src/main/resources/application-production.properties, s4e-backend/src/main/resources/application.properties, s4e-backend/src/main/resources/logback.xml, s4e-backend/src/test/resources/application-test.properties
Activate sentry performance logging.
Bump log4j to 2.15.0 until the bump isn't present in spring boot.
Update to java 17.
=> Dependency updates 2021-12
