cyfronet-fid/sat4envi

README.md, s4e-web/src/app/common.module.ts, s4e-web/src/app/constants.ts, s4e-web/src/app/map/granule-view.model.ts, s4e-web/src/app/map/map.component.html, s4e-web/src/app/map/map.component.ts, s4e-web/src/app/map/view-manager.component.html, s4e-web/src/app/products/granule.model.ts, s4e-web/src/app/products/product.model.ts, s4e-web/src/app/products/product.service.ts
The models in angular had to be updated to match the ones returned by
backend.
=> Make angular app use product and granules endpoint of backend app

s4e-backend/src/main/java/pl/cyfronet/s4e/bean/Overlay.java, s4e-backend/src/main/java/pl/cyfronet/s4e/bean/PRGOverlay.java, s4e-backend/src/main/java/pl/cyfronet/s4e/bean/SldStyle.java, s4e-backend/src/main/java/pl/cyfronet/s4e/bean/WMSOverlay.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/OverlayController.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/response/PRGOverlayResponse.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/response/WMSOverlayResponse.java, s4e-backend/src/main/java/pl/cyfronet/s4e/data/repository/PRGOverlayRepository.java, s4e-backend/src/main/java/pl/cyfronet/s4e/data/repository/WMSOverlayRepository.java, s4e-backend/src/main/java/pl/cyfronet/s4e/service/PRGOverlayService.java, s4e-backend/src/main/java/pl/cyfronet/s4e/service/WMSOverlayService.java
=> #39 Overlay data model

README.md, pom.xml, s4e-backend/Dockerfile
#74 
@jswk @michal-szostak 
it seems that it's easier than i thought :)
=> [#74] Update JAVA version to 11

README.md, docker-compose.yml, s4e-backend/src/main/java/pl/cyfronet/s4e/service/GeoServerOperations.java, s4e-web/src/app/views/map-view/state/overlay/overlay.service.spec.ts, s4e-web/src/app/views/map-view/state/overlay/overlay.service.ts
See commit messages for more info.
@michal-szostak: have a look at the front-end part, especially the test
@kmarszalek: try running the app with docker-compose now, works for me
Fixes: #93
=> Fix docker after backend geoserver link creation

s4e-backend/src/main/java/pl/cyfronet/s4e/controller/PasswordController.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/request/PasswordResetRequest.java
Fixed endpoint.
Removed password validation from bean and unnecessary logic from controller.
=> [#126] Refactor reset password endpoint

s4e-backend/src/main/java/pl/cyfronet/s4e/controller/OverlayController.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/PlaceController.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/ProductController.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/ProductTypeController.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/WebhooksController.java
=> Swagger for old endpoints

s4e-web/.gitignore, s4e-web/package-lock.json, s4e-web/src/app/app.constants.ts, s4e-web/src/app/app.module.ts, s4e-web/src/app/app.routes.ts, s4e-web/src/app/common/share.module.ts, s4e-web/src/app/components/form-error/form-error.component.html, s4e-web/src/app/components/form-error/form-error.component.spec.ts, s4e-web/src/app/components/form-error/form-error.component.ts, s4e-web/src/app/components/form-error/form-error.module.ts, s4e-web/src/app/utils/error-interceptor/error.interceptor.ts, s4e-web/src/app/utils/error-keys/error-keys.pipe.spec.ts, s4e-web/src/app/utils/error-keys/error-keys.pipe.ts, s4e-web/src/app/utils/miscellaneous/miscellaneous.ts, s4e-web/src/app/views/map-view/state/product/product.factory.spec.ts, s4e-web/src/app/views/map-view/state/product/product.service.spec.ts, s4e-web/src/app/views/register/register.component.html, s4e-web/src/app/views/register/register.component.spec.ts, s4e-web/src/app/views/register/register.component.ts, s4e-web/src/app/views/register/register.module.ts, s4e-web/src/app/views/register/state/register.model.ts, s4e-web/src/app/views/register/state/register.query.ts, s4e-web/src/app/views/register/state/register.service.spec.ts, s4e-web/src/app/views/register/state/register.service.ts
* Add registration view with error validation
* Add Server error handling
* Add generic Form error component
* Add persitable errors to store, so they survive page reload
in dev mode
Closes: #115
=> [#115] Registration UI, connect API error responses

backend-development.env, backend-production.env.template, s4e-backend/src/main/resources/application-development.properties, s4e-backend/src/main/resources/application-production.properties, s4e-backend/src/test/resources/application-test.properties, s4e-web/package.json, s4e-web/src/app/app.configuration.spec.ts, s4e-web/src/app/app.configuration.ts, s4e-web/src/app/app.constants.ts, s4e-web/src/app/app.module.ts, s4e-web/src/app/utils/date-converter/date-converter.spec.ts, s4e-web/src/app/utils/date-converter/date-converter.ts, s4e-web/src/app/utils/initializer/config.service.spec.ts, s4e-web/src/app/utils/initializer/config.service.ts, s4e-web/src/app/utils/initializer/init.service.spec.ts, s4e-web/src/app/utils/initializer/init.service.ts, s4e-web/src/app/utils/miscellaneous/miscellaneous.spec.ts, s4e-web/src/app/views/map-view/map/map.component.spec.ts, s4e-web/src/app/views/map-view/map/map.component.ts, s4e-web/src/app/views/map-view/state/overlay/overlay.query.spec.ts, s4e-web/src/app/views/map-view/state/overlay/overlay.query.ts, s4e-web/src/app/views/map-view/state/overlay/overlay.service.spec.ts, s4e-web/src/app/views/map-view/state/overlay/overlay.service.ts, s4e-web/src/app/views/map-view/state/product/product.factory.spec.ts, s4e-web/src/app/views/map-view/state/product/product.service.spec.ts
- Create IConfigration interface
- Create init service to load configuration from backend
- Use APP_INITIALIZER to load config at startup
- Fix outsideBaseUrl to point to wms
=> [#88] Configuration endpoint in s4e-web

s4e-backend/src/main/java/pl/cyfronet/s4e/AuthorizationServerConfiguration.java, s4e-backend/src/main/java/pl/cyfronet/s4e/security/PersistingJwtTokenStore.java
=> [#149] fix circular dependency, set names for tokenStore beans

s4e-backend/src/main/java/pl/cyfronet/s4e/AuthorizationServerConfiguration.java
=> [#172] Allow to set token timeouts by properties

s4e-backend/src/main/java/pl/cyfronet/s4e/data/repository/PlaceRepository.java, s4e-backend/src/main/java/pl/cyfronet/s4e/service/PlaceService.java, s4e-backend/src/test/java/pl/cyfronet/s4e/controller/PlaceControllerTest.java
=> [#187] Make Place search case insensitive

s4e-web/README.md, s4e-web/angular.json, s4e-web/package-lock.json, s4e-web/package.json, s4e-web/pom.xml, s4e-web/src/app/app.routes.ts, s4e-web/src/app/state/session/session.service.ts, s4e-web/src/app/views/map-view/map-view.component.html, s4e-web/src/app/views/map-view/map-view.component.ts, s4e-web/src/app/views/map-view/view-manager/view-manager.component.html, s4e-web/src/app/views/map-view/view-manager/view-manager.component.ts, s4e-web/src/app/views/register/register.component.html, s4e-web/src/environments/environment.hmr.private.ts, s4e-web/src/environments/environment.prod.private.ts, s4e-web/src/environments/environment.ts
* depending on the configuration used (and by extension environment
variable) base map route will be disabled and will required logged
in user
To build restricted access front end use following command:
**production**
`npm run build-private`
**running development server**
`npm run start-private`
This PR still requires adding easy to switch way via POM - @kmarszalek, it would be great if you could handle it.
This kind of feature is rather hard to test as it requires running different compilation schemes. Because of that the tests were skipped, especially because it is only a temporary feature.
Closes: #189
=> [#189] Secure all views except login

s4e-web/package-lock.json, s4e-web/package.json, s4e-web/src/app/app.configuration.spec.ts, s4e-web/src/app/app.configuration.ts, s4e-web/src/app/utils/date-converter/date-converter.spec.ts, s4e-web/src/app/utils/date-converter/date-converter.ts, s4e-web/src/app/utils/initializer/config.service.spec.ts, s4e-web/src/app/utils/initializer/config.service.ts, s4e-web/src/app/utils/miscellaneous/miscellaneous.spec.ts
* move to moment js, which handles UTC dates much better than date-fms
If the travis / github pipeline tests do not fail for frontend then it means that the fix was successful
Closes: #192
=> [#192] DateConverter tests fail

s4e-backend/src/main/java/pl/cyfronet/s4e/Constants.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/ConfigController.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/response/ConfigResponse.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/response/ProductResponse.java, s4e-backend/src/test/java/pl/cyfronet/s4e/controller/ConfigControllerTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/controller/ProductControllerTest.java
* Remove dateFormat from config endpoint output
* Return a ZonedDateTime in ProductController
Closes: #194.
=> Zoned date format

pom.xml, s4e-backend/pom.xml, s4e-backend/src/test/java/pl/cyfronet/s4e/controller/LoginControllerTest.java
Also, add maven enforcer plugin to ensure correct maven version is used.
=> Backend dependencies update - 2019.10

s4e-backend/src/main/java/pl/cyfronet/s4e/controller/ProductController.java, s4e-backend/src/main/java/pl/cyfronet/s4e/data/repository/ProductRepository.java, s4e-backend/src/main/java/pl/cyfronet/s4e/service/ProductService.java, s4e-backend/src/test/java/pl/cyfronet/s4e/controller/ProductControllerTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/service/ProductServiceTest.java
=> [#208] Add option to filter products by date

s4e-web/src/app/utils/utils.module.ts, s4e-web/src/app/views/activate/state/activate.store.ts, s4e-web/src/app/views/map-view/map-view.component.html, s4e-web/src/app/views/map-view/map-view.component.ts, s4e-web/src/app/views/map-view/map.module.ts, s4e-web/src/app/views/map-view/map/map.component.ts, s4e-web/src/app/views/map-view/search-results/search-results.component.html, s4e-web/src/app/views/map-view/search-results/search-results.component.scss, s4e-web/src/app/views/map-view/search-results/search-results.component.spec.ts, s4e-web/src/app/views/map-view/search-results/search-results.component.ts, s4e-web/src/app/views/map-view/state/search-results/guid.service.ts, s4e-web/src/app/views/map-view/state/search-results/search-result.model.ts, s4e-web/src/app/views/map-view/state/search-results/search-results.query.spec.ts, s4e-web/src/app/views/map-view/state/search-results/search-results.query.ts, s4e-web/src/app/views/map-view/state/search-results/search-results.service.spec.ts, s4e-web/src/app/views/map-view/state/search-results/search-results.service.ts, s4e-web/src/app/views/map-view/state/search-results/search-results.store.spec.ts, s4e-web/src/app/views/map-view/state/search-results/search-results.store.ts, s4e-web/src/app/views/map-view/view-manager/view-manager.component.html, s4e-web/src/app/views/map-view/view-manager/view-manager.component.scss, s4e-web/src/app/views/map-view/view-manager/view-manager.component.ts
* Query backend for places
* Display results in SearchResultComponent
* Mark selected place with pin
Closes #100
=> [#100] Places search front-end

s4e-backend/src/main/java/pl/cyfronet/s4e/controller/GroupController.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/request/CreateGroupRequest.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/request/UpdateGroupRequest.java, s4e-backend/src/main/java/pl/cyfronet/s4e/service/InstitutionService.java, s4e-backend/src/test/java/pl/cyfronet/s4e/controller/GroupControllerTest.java
enhance post and put for group.
added list of members emails.
added creation of default group during institution creation
=> [#168] Enhance payload for POST and PUT Group

s4e-backend/src/main/java/pl/cyfronet/s4e/SwaggerConfig.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/ProductController.java, s4e-backend/src/main/java/pl/cyfronet/s4e/converter/StringToYearMonthConverter.java, s4e-backend/src/main/java/pl/cyfronet/s4e/data/repository/ProductRepository.java, s4e-backend/src/main/java/pl/cyfronet/s4e/service/ProductService.java, s4e-backend/src/test/java/pl/cyfronet/s4e/controller/ProductControllerTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/data/repository/ProductRepositoryTest.java
=> [#209] Add endpoint to return dates with data available per product type

s4e-backend/src/main/java/pl/cyfronet/s4e/db/seed/SeedProducts.java
=> [#224] Seed 5 PRG overlay layers instead of a single one

s4e-backend/src/main/java/pl/cyfronet/s4e/db/seed/SeedProducts.java
=> [#228] Update product type names in s4e-demo dataset

s4e-backend/src/main/java/pl/cyfronet/s4e/controller/AppUserController.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/GroupController.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/InstitutionController.java, s4e-backend/src/test/java/pl/cyfronet/s4e/controller/AppUserControllerTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/controller/GroupControllerTest.java
- add @PreAuthorize("isAuthenticated()") annotations and tests adjustment
changes with configuration of  groupControllerTest required for multiple mockMvc.perform methods inside one @Test method. should be refactored in scope of #220.
=> [#169] Secure endpoints for Institutions, Groups and Profile

s4e-backend/src/main/java/pl/cyfronet/s4e/I18nConfig.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/GroupController.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/request/CreateGroupRequest.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/request/UpdateGroupRequest.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/validation/GroupNameValid.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/validation/GroupNameValidator.java, s4e-backend/src/main/java/pl/cyfronet/s4e/service/InstitutionService.java, s4e-backend/src/main/resources/messages_pl_PL.properties, s4e-backend/src/test/java/pl/cyfronet/s4e/controller/GroupControllerTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/service/GroupServiceTest.java
check if name does not starts with double underscore or is not '__default__'
=> [#169] Add group name validation

s4e-web/package-lock.json, s4e-web/package.json, s4e-web/src/app/utils/initializer/config.service.ts, s4e-web/src/app/views/map-view/map-view.component.html, s4e-web/src/app/views/map-view/map-view.component.ts, s4e-web/src/app/views/map-view/map.module.ts, s4e-web/src/app/views/map-view/state/product-type/product-type.model.ts, s4e-web/src/app/views/map-view/state/product-type/product-type.query.ts, s4e-web/src/app/views/map-view/state/product-type/product-type.service.ts, s4e-web/src/app/views/map-view/state/product-type/product-type.store.ts, s4e-web/src/app/views/map-view/state/product/product.service.spec.ts, s4e-web/src/app/views/map-view/state/product/product.service.ts, s4e-web/src/app/views/map-view/timeline/timeline.component.html, s4e-web/src/app/views/map-view/timeline/timeline.component.scss, s4e-web/src/app/views/map-view/timeline/timeline.component.spec.ts, s4e-web/src/app/views/map-view/timeline/timeline.component.ts, s4e-web/src/scss/styles.scss
* Add calendar module for styling
* Timeline scrollable, calendar design fixed
Closes: #157
=> [#157]  Handle Many Days Data & Calendar

s4e-web/src/app/state/session/session.service.ts, s4e-web/src/app/utils/s4e-date/s4e-date.pipe.ts, s4e-web/src/app/views/map-view/map-view.component.ts, s4e-web/src/app/views/map-view/map/map.component.ts, s4e-web/src/app/views/map-view/state/overlay/overlay.model.ts, s4e-web/src/app/views/map-view/state/overlay/overlay.query.spec.ts, s4e-web/src/app/views/map-view/state/overlay/overlay.query.ts, s4e-web/src/app/views/map-view/state/overlay/overlay.service.ts, s4e-web/src/app/views/map-view/state/overlay/overlay.store.ts, s4e-web/src/app/views/map-view/state/product-type/product-type.service.ts
Overlay fix - by default none of them is visible, and they can be unactivated.
Also - now application fetches overlays from server instead of static data
Closes: #102
=> [#102] overlay display and handling

s4e-backend/src/main/java/pl/cyfronet/s4e/controller/AppUserController.java, s4e-backend/src/main/java/pl/cyfronet/s4e/service/AppUserService.java, s4e-backend/src/test/java/pl/cyfronet/s4e/controller/AppUserControllerTest.java
@jswk we didnt get the use case with multiple groups, it crashed :(
=> [#169] Fix add User to institution with groups

s4e-web/src/app/utils/miscellaneous/generic-form.component.ts, s4e-web/src/app/views/map-view/map-view.component.html, s4e-web/src/app/views/map-view/map-view.component.ts, s4e-web/src/app/views/map-view/map.module.ts, s4e-web/src/app/views/map-view/state/product-type/product-type.query.ts, s4e-web/src/app/views/map-view/state/product-type/product-type.service.ts, s4e-web/src/app/views/map-view/state/product-type/product-type.store.ts, s4e-web/src/app/views/map-view/timeline/timeline.component.html, s4e-web/src/app/views/map-view/timeline/timeline.component.scss, s4e-web/src/app/views/map-view/timeline/timeline.component.ts, s4e-web/src/app/views/settings/people/person-form/person-form.component.ts, s4e-web/src/app/views/settings/people/person-list/person-list.component.html, s4e-web/src/app/views/settings/people/person-list/person-list.component.ts, s4e-web/src/scss/_datepicker.scss, s4e-web/src/scss/_panel.scss, s4e-web/src/scss/styles.scss
Fixes for the following small bugs and issues which have been discovered prior to the release of milestone 2:
* Calendar icon / button does not work on first page load
* Calendar styles go crazy after visiting settings/groups or settings/people
* CRUD forms sometimes have issues with internal state stored in store
* Datepicker should display days where products are available
Closes: #244
=> [#244] fixes after milestone 2

s4e-backend/src/main/java/pl/cyfronet/s4e/bean/Group.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/AppUserController.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/request/UpdateUserGroupsRequest.java, s4e-backend/src/main/java/pl/cyfronet/s4e/data/repository/GroupRepository.java, s4e-backend/src/main/java/pl/cyfronet/s4e/service/GroupService.java, s4e-backend/src/test/java/pl/cyfronet/s4e/controller/AppUserControllerTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/service/GroupServiceTest.java
endpoint for update groups for user in institution, batch operation.
=> 168 improvments

s4e-web/src/app/modal/components/modal-outlet/modal-outlet.component.scss, s4e-web/src/app/views/map-view/map-view.component.html, s4e-web/src/app/views/map-view/map-view.component.scss, s4e-web/src/app/views/map-view/map-view.component.spec.ts, s4e-web/src/app/views/map-view/map-view.component.ts, s4e-web/src/app/views/map-view/map/map.component.html, s4e-web/src/app/views/map-view/map/map.component.ts, s4e-web/src/app/views/map-view/state/map/map.model.ts, s4e-web/src/app/views/map-view/state/map/map.service.ts
* Add dropdown for ZK to MapViewComponent
* Add tests to MapViewComponent
* Change z-index of modals, to make them always on top
Closes #254
=> [#254] Drop Down for ZK

s4e-web/src/app/views/map-view/map-view.component.html, s4e-web/src/app/views/map-view/map-view.component.ts, s4e-web/src/app/views/map-view/map/map.component.spec.ts, s4e-web/src/app/views/map-view/map/map.component.ts, s4e-web/src/app/views/map-view/state/map/map.model.ts, s4e-web/src/app/views/map-view/state/map/map.query.ts, s4e-web/src/app/views/map-view/state/map/map.service.ts, s4e-web/src/app/views/map-view/state/map/map.store.spec.ts, s4e-web/src/app/views/map-view/state/map/map.store.ts
* Save map center position and zoom in store
* Set zoom level depending on search result type (miasto/wies)
Closes #251
=> [#251] Connect map state to store

s4e-backend/src/main/java/pl/cyfronet/s4e/bean/Product.java, s4e-backend/src/main/java/pl/cyfronet/s4e/bean/SavedView.java, s4e-backend/src/main/java/pl/cyfronet/s4e/bean/package-info.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/SavedViewController.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/SceneController.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/request/CreateSavedViewRequest.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/response/SavedViewResponse.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/response/SceneResponse.java, s4e-backend/src/main/java/pl/cyfronet/s4e/data/repository/SavedViewRepository.java, s4e-backend/src/main/java/pl/cyfronet/s4e/ex/ErrorHandler.java, s4e-backend/src/main/java/pl/cyfronet/s4e/service/SavedViewService.java, s4e-backend/src/main/java/pl/cyfronet/s4e/util/TimeHelper.java, s4e-backend/src/main/resources/db/migration/V16__add_saved_view_table.sql, s4e-backend/src/test/java/pl/cyfronet/s4e/TestDbHelper.java, s4e-backend/src/test/java/pl/cyfronet/s4e/TestJwtUtil.java, s4e-backend/src/test/java/pl/cyfronet/s4e/controller/SavedViewControllerTest.java, s4e-backend/src/test/resources/application-test.properties
- Create entity SavedView and accompanying classes with API level tests.
- Create table saved_view in the db.
- Move jsonb hibernate type definition to package-info. There are now two entities which use it, so it seems appropriate.
- Introduce TimeUtil that handles conversion of LocalDateTime to ZonedDateTime.
- Correct ErrorHandler method names.
First stage of the #272 implementation.
=> [#272] Add SavedView functionality (excluding thumbnail storage)

.gitignore, README.md
How to test
------
Follow the provided description in `README.md` and evaluate if it serves the purpose.
Closes: #256.
=> [#256] Docker-compose customization description and ignored files update

s4e-backend/src/main/java/pl/cyfronet/s4e/MethodSecurityConfig.java, s4e-backend/src/main/java/pl/cyfronet/s4e/SecurityConfig.java, s4e-backend/src/main/java/pl/cyfronet/s4e/bean/AppRole.java, s4e-backend/src/main/java/pl/cyfronet/s4e/bean/AppUser.java, s4e-backend/src/main/java/pl/cyfronet/s4e/bean/Institution.java, s4e-backend/src/main/java/pl/cyfronet/s4e/bean/UserRole.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/AppUserController.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/GroupController.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/InstitutionController.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/SavedViewController.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/request/CreateChildInstitutionRequest.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/request/CreateGroupRequest.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/request/CreateUserWithGroupsRequest.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/request/UpdateGroupRequest.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/request/UpdateUserGroupsRequest.java, s4e-backend/src/main/java/pl/cyfronet/s4e/data/repository/UserRoleRepository.java, s4e-backend/src/main/java/pl/cyfronet/s4e/security/AppUserDetails.java, s4e-backend/src/main/java/pl/cyfronet/s4e/security/AppUserDetailsService.java, s4e-backend/src/main/java/pl/cyfronet/s4e/security/CustomMethodSecurityExpressionHandler.java, s4e-backend/src/main/java/pl/cyfronet/s4e/security/CustomMethodSecurityExpressionRoot.java, s4e-backend/src/main/java/pl/cyfronet/s4e/service/AppUserService.java, s4e-backend/src/main/java/pl/cyfronet/s4e/service/GroupService.java, s4e-backend/src/main/java/pl/cyfronet/s4e/service/InstitutionService.java, s4e-backend/src/main/java/pl/cyfronet/s4e/service/UserRoleService.java, s4e-backend/src/main/resources/db/migration/V22__add_parent_institution_field.sql, s4e-backend/src/main/resources/db/migration/V23__add_app_user_admin_and_ZK_member_fields.sql, s4e-backend/src/test/java/pl/cyfronet/s4e/TestJwtUtil.java, s4e-backend/src/test/java/pl/cyfronet/s4e/controller/AppUserControllerTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/controller/GroupControllerTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/service/GroupServiceTest.java
- implemented CustomSecurityExpression
- authorized rest endpoints
- refactored tests
- add parent field in Institution
- add endpoint for INST_ADMIN to create a child Institution
- add UserRoleService with add/remove methods
- Enrich REST API with UserRole batch operations on user
=> [#169] Add custom security expression

s4e-backend/src/main/java/pl/cyfronet/s4e/controller/ShareLinkController.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/request/ShareLinkRequest.java, s4e-backend/src/main/java/pl/cyfronet/s4e/event/OnShareLinkEvent.java, s4e-backend/src/main/java/pl/cyfronet/s4e/listener/GroupListener.java, s4e-backend/src/main/resources/mail/share-link.txt, s4e-backend/src/main/resources/messages_pl_PL.properties, s4e-backend/src/test/java/pl/cyfronet/s4e/listener/GroupListenerTest.java
it waits for UserRole PR to be merged.
input:
- link to share without hostname
- list of emails
only ZKMembers can access this endpoint
backend have properties with front base host
=> 249 share link

s4e-backend/src/main/java/pl/cyfronet/s4e/controller/SavedViewController.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/SceneController.java, s4e-backend/src/test/java/pl/cyfronet/s4e/controller/SavedViewControllerIntegrationTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/controller/SavedViewControllerTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/controller/SceneControllerTest.java, s4e-web/src/app/views/map-view/state/product/product.service.ts, s4e-web/src/app/views/map-view/state/scene/scene.service.spec.ts, s4e-web/src/app/views/map-view/state/scene/scene.service.ts
- change all endpoints to dash-case notation (kebab-case)
=> [#296] Unified dash-case rest endpoints

.mvn/wrapper/maven-wrapper.properties, pom.xml, s4e-backend/pom.xml, s4e-backend/src/main/java/pl/cyfronet/s4e/Application.java, s4e-backend/src/main/java/pl/cyfronet/s4e/SecurityConfig.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/GroupController.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/InstitutionController.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/PlaceController.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/SavedViewController.java, s4e-web/pom.xml
Update HttpSecurity usage to new lambda style.
Use newly introduced @PageableAsQueryParam in endpoints, which use Pageable.
=> Backend dependencies update - 2020.01

s4e-web/src/app/views/map-view/map-view.component.html, s4e-web/src/app/views/map-view/map-view.component.scss, s4e-web/src/app/views/map-view/map-view.component.spec.ts, s4e-web/src/app/views/reset-password/reset-password.component.html, s4e-web/src/app/views/reset-password/reset-password.component.scss, s4e-web/src/assets/images/ico_bolt.svg, s4e-web/src/assets/images/ico_close.svg, s4e-web/src/scss/_auth.scss
New UI for ZK dropdown,
UI template for static pages before login, here - reset password
=> [#301] dropdown zk

s4e-backend/src/main/java/pl/cyfronet/s4e/bean/AppUser.java, s4e-backend/src/main/java/pl/cyfronet/s4e/bean/Group.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/UserRoleController.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/request/CreateUserRoleRequest.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/request/DeleteUserRoleRequest.java, s4e-backend/src/main/java/pl/cyfronet/s4e/db/seed/SeedUsers.java, s4e-backend/src/main/java/pl/cyfronet/s4e/service/UserRoleService.java, s4e-backend/src/test/java/pl/cyfronet/s4e/controller/UserRoleControllerTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/service/UserRoleServiceTest.java
- add endpoint to give/take user a role
=> [#169] Seeds with roles and institution

s4e-web/package-lock.json, s4e-web/package.json, s4e-web/src/app/app.module.ts, s4e-web/src/app/utils/initializer/config.service.ts, s4e-web/src/app/utils/rxjs/observable.ts, s4e-web/src/app/views/map-view/map-view.component.html, s4e-web/src/app/views/map-view/map-view.component.scss, s4e-web/src/app/views/map-view/map-view.component.spec.ts, s4e-web/src/app/views/map-view/map-view.component.ts, s4e-web/src/app/views/map-view/map.module.ts, s4e-web/src/app/views/map-view/map/map.component.ts, s4e-web/src/app/views/map-view/state/map/map.model.ts, s4e-web/src/app/views/map-view/state/map/map.query.spec.ts, s4e-web/src/app/views/map-view/state/map/map.service.spec.ts, s4e-web/src/app/views/map-view/state/map/map.service.ts, s4e-web/src/app/views/map-view/state/map/map.store.spec.ts, s4e-web/src/app/views/map-view/state/overlay/overlay.factory.spec.ts, s4e-web/src/app/views/map-view/state/overlay/overlay.service.ts, s4e-web/src/app/views/map-view/state/product/product.service.ts, s4e-web/src/app/views/map-view/state/product/product.store.ts, s4e-web/src/app/views/map-view/state/scene/scene.service.spec.ts, s4e-web/src/app/views/map-view/state/scene/scene.service.ts, s4e-web/src/app/views/map-view/timeline/timeline.component.html, s4e-web/src/app/views/map-view/timeline/timeline.component.ts, s4e-web/src/app/views/settings/groups/group-form/group-form.component.ts, s4e-web/src/app/views/settings/groups/group-list/group-list.component.ts, s4e-web/src/app/views/settings/people/person-form/person-form.component.ts, s4e-web/src/app/views/settings/people/person-list/person-list.component.ts, s4e-web/src/app/views/settings/state/institution.service.ts, s4e-web/src/main.ts
Synchronisation between URL's query params, store and interactive map
Move / zoom map around, change visible layers & products. Copy URL, open new private window and paste URL there - the map, layers, product in the new window should be set to be the same as in the old one.
[Closes #252]
=> [#252] Sync params with url

.github/workflows/maven.yml, README.md, s4e-web/cypress/integration/sanity.spec.ts, s4e-web/cypress/plugins/cy-ts-preprocessor.js, s4e-web/cypress/plugins/index.js, s4e-web/package-lock.json, s4e-web/package.json
* Add sanity e2e tests
* Fix spring-boot:run README.md reference
Closes #333
=> [#333] Add sanity e2e tests

s4e-backend/pom.xml, s4e-backend/src/test/java/pl/cyfronet/s4e/controller/AppUserControllerTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/controller/GroupControllerTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/data/repository/AppUserRepositoryTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/security/JWTTokenServiceTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/service/AppUserServiceTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/service/GroupServiceTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/service/InstitutionServiceTest.java
- add dependency hamcrest-optional in test scope
- refactor test with isPresent end isEmpty
=> [#222] Add hamcrest-optional to backend tests

s4e-web/src/app/views/map-view/map-view.component.html, s4e-web/src/app/views/map-view/map-view.component.scss, s4e-web/src/app/views/map-view/map-view.component.spec.ts, s4e-web/src/app/views/map-view/map-view.component.ts
Added button to download current scene's original file, if no scene is selected the button is inactive
Closes #342
=> [#342] Add download link for original file in current scene

s4e-backend/src/main/java/pl/cyfronet/s4e/controller/PasswordController.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/request/PasswordChangeRequest.java, s4e-backend/src/main/java/pl/cyfronet/s4e/data/repository/PasswordResetRepository.java, s4e-backend/src/main/java/pl/cyfronet/s4e/service/PasswordService.java, s4e-backend/src/test/java/pl/cyfronet/s4e/TestDbHelper.java, s4e-backend/src/test/java/pl/cyfronet/s4e/controller/AppUserControllerTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/controller/ConfigControllerTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/controller/GroupControllerTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/controller/PasswordControllerTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/controller/PlaceControllerTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/controller/ProductControllerTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/controller/SavedViewControllerTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/service/PasswordServiceTest.java
- add deleting preexisting token while requesting a new one
- add token expiry verification
- add tests
- removed unnecessary content type in tests on get endpoints
=> [#315] Reset password handlig fix

s4e-backend/src/main/java/pl/cyfronet/s4e/controller/GroupController.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/InstitutionController.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/PasswordController.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/SavedViewController.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/ShareLinkController.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/UserRoleController.java, s4e-backend/src/test/java/pl/cyfronet/s4e/TestJwtUtil.java
- fix 403 instead of 200 failing reason
=> [#315] Fix failing tests

s4e-web/src/app/views/map-view/sentinel-search/sentinel-search.component.html, s4e-web/src/app/views/map-view/sentinel-search/sentinel-search.component.scss, s4e-web/src/app/views/map-view/sentinel-search/sentinel-search.component.ts, s4e-web/src/app/views/map-view/state/sentinel-search/sentinel-search.model.ts, s4e-web/src/app/views/map-view/state/sentinel-search/sentinel-search.service.ts
Add working download link to sentinel search result
=> [#360] Stub Download

CHANGELOG.md, s4e-backend/src/main/java/pl/cyfronet/s4e/bean/AppUser.java, s4e-backend/src/main/java/pl/cyfronet/s4e/bean/EmailVerification.java, s4e-backend/src/main/java/pl/cyfronet/s4e/bean/Group.java, s4e-backend/src/main/java/pl/cyfronet/s4e/bean/Institution.java, s4e-backend/src/main/java/pl/cyfronet/s4e/bean/PasswordReset.java, s4e-backend/src/main/java/pl/cyfronet/s4e/bean/Product.java, s4e-backend/src/main/java/pl/cyfronet/s4e/bean/Scene.java, s4e-backend/src/main/resources/db/migration/V24__add_fk_constraint_app_user_to_password_reset_table.sql, s4e-backend/src/main/resources/db/migration/V25__add_fk_constraint_app_user_to_email_verification_table.sql, s4e-backend/src/main/resources/db/migration/V26__fix_constraints_on_product_and_scene_table.sql, s4e-backend/src/test/java/pl/cyfronet/s4e/TestDbHelper.java, s4e-backend/src/test/java/pl/cyfronet/s4e/controller/PasswordControllerTest.java
- add ON DELETE CASCADE to app_user on password_reset
- add ON DELETE CASCADE to app_user on email_verification
- fix constraint names on product and scene tables
- removed unnecessary code from TestDBHelper
=> [#358] Fix cascades and constraints

CHANGELOG.md, s4e-backend/src/main/java/pl/cyfronet/s4e/bean/Product.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/response/BasicProductResponse.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/response/ProductResponse.java, s4e-backend/src/main/java/pl/cyfronet/s4e/db/seed/SeedProducts.java, s4e-backend/src/main/resources/db/migration/V27__add_display_name_field.sql, s4e-backend/src/test/java/pl/cyfronet/s4e/controller/ProductControllerTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/controller/SceneControllerTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/db/DbTimestampTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/service/GeoServerServiceIntegrationTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/service/GeoServerServiceTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/service/SceneServiceTest.java, s4e-web/src/app/views/map-view/state/product/product.factory.spec.ts, s4e-web/src/app/views/map-view/state/product/product.model.ts, s4e-web/src/app/views/map-view/state/product/product.query.ts
- add displayName to Product
- migration that add field
- change appropriate view
#229
=> [#229] Add displayName field to Product

CHANGELOG.md, s4e-web/src/app/app.configuration.spec.ts, s4e-web/src/app/app.configuration.ts, s4e-web/src/app/app.module.ts, s4e-web/src/app/utils/initializer/config.service.ts, s4e-web/src/app/utils/miscellaneous/date-utils.spec.ts, s4e-web/src/app/utils/miscellaneous/date-utils.ts, s4e-web/src/app/utils/miscellaneous/miscellaneous.ts, s4e-web/src/app/views/map-view/map.module.ts, s4e-web/src/app/views/map-view/state/product/product.service.ts, s4e-web/src/app/views/map-view/state/product/product.store.ts, s4e-web/src/app/views/map-view/state/scene/scene.service.spec.ts, s4e-web/src/app/views/map-view/state/scene/scene.service.ts, s4e-web/src/app/views/map-view/timeline/timeline.component.ts
* Add tz parameter to backend requests
* Get rid of momentum library in code
Closes #347
=> [#347] Add timezones to frontend

CHANGELOG.md, README.md, s4e-backend/src/main/java/pl/cyfronet/s4e/db/seed/SeedProducts.java
=> [#368] Dataset s4e-demo-2

CHANGELOG.md, README.md, docker-compose.yml, s4e-backend/pom.xml, s4e-backend/src/main/resources/application.properties
Also, add a FAQ entry on creating a readonly user in psql.
Part of #371.
=> Switch db to postgresql 12 with postgis 3.0

CHANGELOG.md, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/ConfigController.java, s4e-backend/src/test/java/pl/cyfronet/s4e/controller/ConfigControllerTest.java, s4e-backend/src/test/resources/application-test.properties
=> [#381] Return site-key instead of secret-key in ConfigController

CHANGELOG.md, s4e-backend/src/main/java/pl/cyfronet/s4e/config/SecurityConfig.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/AppUserController.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/ConfigController.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/GroupController.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/InstitutionController.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/LoginController.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/PasswordController.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/SavedViewController.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/ShareLinkController.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/UserRoleController.java, s4e-backend/src/test/java/pl/cyfronet/s4e/SecurityTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/controller/SavedViewControllerTest.java
- change security config
- add tests for 401 - 403 - 404 error responses
- refactor saved vied test
Responses for:
401 
- when request dont have authorization header
- when request have authorization header with bad credentials, etc 
403 
- when request have anonymous authorization header
- when request have authentication without authorization to resource
404
- when request have authentication and authoriation but there is no resource
Closes: #390.
=> #390 Rework Spring Security

CHANGELOG.md, s4e-backend/src/main/java/pl/cyfronet/s4e/config/SecurityConfig.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/AppUserController.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/GroupController.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/InstitutionController.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/LoginController.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/PasswordController.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/SavedViewController.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/ShareLinkController.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/UserRoleController.java, s4e-backend/src/test/java/pl/cyfronet/s4e/SecurityTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/controller/SavedViewControllerTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/controller/SchemaControllerTest.java
- change security config
- add tests for 401 - 403 - 404 error responses
- refactor saved vied test
- refactor @ApiResponses
Closes #390.
=> [#390] Rework Spring Security

.github/workflows/maven.yml, CHANGELOG.md
=> [#399] Separate backend and web tests workflows

CHANGELOG.md, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/GroupController.java, s4e-backend/src/main/java/pl/cyfronet/s4e/db/seed/SeedUsers.java
- add more seeds for tests - 3 levels of institutions with 3 members in each
- fix authorization condition for addMember and removeMember endpoints
Closes: #411.
=> [#411] Add more seeds for tests

CHANGELOG.md, s4e-backend/src/main/java/pl/cyfronet/s4e/bean/Product.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/ProductController.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/response/BasicProductResponse.java, s4e-backend/src/main/java/pl/cyfronet/s4e/data/repository/ProductRepository.java, s4e-backend/src/main/java/pl/cyfronet/s4e/service/ProductService.java, s4e-backend/src/main/java/pl/cyfronet/s4e/util/SecurityHelper.java, s4e-backend/src/main/resources/db/migration/V31__add_favourite_product_app_users_table.sql, s4e-backend/src/test/java/pl/cyfronet/s4e/controller/ProductControllerTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/service/ProductServiceTest.java
- migration that add product_app_users join table
- isFavourite in BasicProductResponse
- cd for favourite Products
- tests for new endpoints and extra data in responses
Closes: #403
=> [#403] Add favourite Products

CHANGELOG.md, s4e-web/cypress/integration/product-navigation.spec.ts, s4e-web/src/app/views/map-view/state/search-results/search-results.service.ts, s4e-web/src/app/views/map-view/view-manager/view-manager.component.html, s4e-web/src/app/views/map-view/view-manager/view-manager.component.ts
* keep state of places input on location choosing
Closes: #427
=> [#427] [Bugfix] places input should keep state

.gitignore, CHANGELOG.md, s4e-web/.gitignore, s4e-web/cypress/integration/product-navigation.spec.ts, s4e-web/cypress/integration/profile.spec.ts, s4e-web/package.json, s4e-web/src/app/state/form/form.model.ts, s4e-web/src/app/state/profile/profile.model.ts, s4e-web/src/app/state/profile/profile.service.ts, s4e-web/src/app/views/login/login.component.html, s4e-web/src/app/views/login/login.component.ts, s4e-web/src/app/views/map-view/state/product/product.service.ts, s4e-web/src/app/views/map-view/view-manager/layer-picker/layer-picker.component.html, s4e-web/src/app/views/map-view/view-manager/layer-picker/layer-picker.component.spec.ts, s4e-web/src/app/views/map-view/view-manager/layer-picker/layer-picker.component.ts, s4e-web/src/app/views/map-view/view-manager/view-manager.component.html, s4e-web/src/app/views/map-view/view-manager/view-manager.component.ts, s4e-web/src/app/views/settings/profile/profile.component.html, s4e-web/src/app/views/settings/profile/profile.component.scss, s4e-web/src/app/views/settings/profile/profile.component.spec.ts, s4e-web/src/app/views/settings/profile/profile.component.ts
* Add password change form in settings/profile
* Unit tests of form
* E2e test of password change
Closes: #158
=> [#158] Password change front

CHANGELOG.md, pom.xml, s4e-backend/pom.xml, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/GroupController.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/InstitutionController.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/PlaceController.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/SavedViewController.java
@danielkryska: I updated the openapi plugin, which updated the way Pageable documentation is generated, so you may want to verify it is generated fine.
=> Backend dependencies update - 2020.05

.github/workflows/maven.yml, CHANGELOG.md, README.md, pom.xml, s4e-backend/pom.xml, s4e-web/pom.xml
=> [#461] Include commit SHA in project.version and pass it to npm

CHANGELOG.md, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/InstitutionController.java, s4e-backend/src/main/java/pl/cyfronet/s4e/data/repository/InstitutionRepository.java, s4e-backend/src/main/java/pl/cyfronet/s4e/service/InstitutionService.java, s4e-backend/src/test/java/pl/cyfronet/s4e/controller/InstitutionControllerTest.java
- return all institutions where user has any permissions
Closes #457.
=> [#457] Improve institutions endpoint

CHANGELOG.md, s4e-web/src/app/app.module.ts, s4e-web/src/app/components/tiles-dashboard/tile/tile.component.html, s4e-web/src/app/components/tiles-dashboard/tile/tile.component.scss, s4e-web/src/app/components/tiles-dashboard/tile/tile.component.spec.ts, s4e-web/src/app/components/tiles-dashboard/tile/tile.component.ts, s4e-web/src/app/components/tiles-dashboard/tiles-dashboard.component.html, s4e-web/src/app/components/tiles-dashboard/tiles-dashboard.component.scss, s4e-web/src/app/components/tiles-dashboard/tiles-dashboard.component.spec.ts, s4e-web/src/app/components/tiles-dashboard/tiles-dashboard.component.ts, s4e-web/src/app/components/tiles-dashboard/tiles-dashboard.module.ts, s4e-web/src/app/modal/components/generic-modal/generic-modal.component.html, s4e-web/src/app/modal/components/generic-modal/generic-modal.component.spec.ts, s4e-web/src/app/state/profile/profile.query.ts, s4e-web/src/app/state/session/session.service.ts, s4e-web/src/app/utils.ts, s4e-web/src/app/views/settings/admin-dashboard/admin-dashboard.component.html, s4e-web/src/app/views/settings/admin-dashboard/admin-dashboard.component.scss, s4e-web/src/app/views/settings/admin-dashboard/admin-dashboard.component.spec.ts, s4e-web/src/app/views/settings/admin-dashboard/admin-dashboard.component.ts, s4e-web/src/app/views/settings/admin-dashboard/admin-dashboard.module.ts, s4e-web/src/app/views/settings/dashboard/dashboard.component.html, s4e-web/src/app/views/settings/dashboard/dashboard.component.ts, s4e-web/src/app/views/settings/guards/is-manager/is-manager.guard.spec.ts, s4e-web/src/app/views/settings/guards/is-manager/is-manager.guard.ts, s4e-web/src/app/views/settings/settings.module.ts, s4e-web/src/app/views/settings/settings.routes.ts
**IMPORTANT!!! For now tiles images/icons aren't available until @abacz update view.**
- Admin dashboard available on `zkAdmin@mail.pl` account (after going to `settings/profile` - `Panel główny` page)
https://projects.invisionapp.com/share/S9RJNE8WXUB#/screens/414649284_Ustawienia
- Super admin dashboard is available on `admin@mail.pl` (after going to `settings/profile` - `Panel główny` page)
https://projects.invisionapp.com/share/S9RJNE8WXUB#/screens/414671409_Ustawienia_-_Uberadmin
=> [#450] Generic Tile View for admin and superadmin

CHANGELOG.md, s4e-backend/src/main/java/pl/cyfronet/s4e/bean/Scene.java, s4e-backend/src/main/java/pl/cyfronet/s4e/config/QueryConfig.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/SceneController.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/SchemaController.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/SearchController.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/response/SearchResponse.java, s4e-backend/src/main/java/pl/cyfronet/s4e/data/repository/SceneRepository.java, s4e-backend/src/main/java/pl/cyfronet/s4e/data/repository/SceneRepositoryExt.java, s4e-backend/src/main/java/pl/cyfronet/s4e/data/repository/SceneRepositoryImpl.java, s4e-backend/src/main/java/pl/cyfronet/s4e/data/repository/query/PreparedStatementBuilder.java, s4e-backend/src/main/java/pl/cyfronet/s4e/data/repository/query/QueryBuilder.java, s4e-backend/src/main/java/pl/cyfronet/s4e/data/repository/query/QueryBuilderImpl.java, s4e-backend/src/main/java/pl/cyfronet/s4e/data/repository/query/QueryDecorator.java, s4e-backend/src/main/java/pl/cyfronet/s4e/data/repository/query/QueryEnding.java, s4e-backend/src/main/java/pl/cyfronet/s4e/data/repository/query/QueryNumber.java, s4e-backend/src/main/java/pl/cyfronet/s4e/data/repository/query/QueryText.java, s4e-backend/src/main/java/pl/cyfronet/s4e/data/repository/query/QueryTime.java, s4e-backend/src/main/java/pl/cyfronet/s4e/service/SearchService.java, s4e-backend/src/main/resources/application.properties, s4e-backend/src/main/resources/db/migration/V35__add_indexes_metadata_scene.sql, s4e-backend/src/test/java/pl/cyfronet/s4e/controller/SceneControllerTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/data/repository/query/QueryBuilderTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/service/SearchServiceTest.java, s4e-web/src/app/views/map-view/state/product/product.service.ts, s4e-web/src/app/views/map-view/state/scene/scene.service.spec.ts, s4e-web/src/app/views/map-view/state/scene/scene.service.ts
GET /search
@RequestParam Map<String, Object> params
params:
- limit
- offset
- orderBy
- sortBy
- tz -> ZoneParameter [client time]
--------------
- sensingFrom 
- sensingTo
- ingestionFrom
- ingestionTo
- satellitePlatform
- productType
- polarisation
- cloudCover [FLOAT]
- processingLevel
- sensorMode
- collection
- timeliness
- instrument
- productLevel
- relativeOrbitNumber
- absoluteOrbitNumber
Closes #422
=> [#422] Scene metadata search

CHANGELOG.md, s4e-web/src/app/modal/components/confirm-modal/confirm-modal.model.ts, s4e-web/src/app/modal/components/dummy-modal/dummy-modal.component.ts, s4e-web/src/app/modal/components/modal-outlet/modal-outlet.component.scss, s4e-web/src/app/state/form/form.model.ts, s4e-web/src/app/views/map-view/map-view.component.ts, s4e-web/src/app/views/map-view/zk/report-modal/report-modal.component.ts, s4e-web/src/app/views/settings/manage-institutions/parent-institution-modal/parent-institution-modal.component.html, s4e-web/src/app/views/settings/manage-institutions/parent-institution-modal/parent-institution-modal.component.spec.ts, s4e-web/src/app/views/settings/manage-institutions/parent-institution-modal/parent-institution-modal.component.ts, s4e-web/src/app/views/settings/manage-institutions/parent-institution-modal/parent-institution-modal.model.ts, s4e-web/src/app/views/settings/manage-institutions/parent-institution-modal/parent-institution-modal.module.ts, s4e-web/src/app/views/settings/settings.component.html, s4e-web/src/app/views/settings/settings.component.ts, s4e-web/src/app/views/settings/settings.module.ts, s4e-web/src/app/views/settings/state/institution.service.ts
**IMPORTANT!!! Can be run by going to `settings` page and clicking first `Dashboard` tab on sidebar**
[Preview](https://projects.invisionapp.com/share/S9RJNE8WXUB#/screens/416623692)
* Modal with institution selection
* Search institution
* Show filtered institutions
Closes: #471
=> [#471] Select parent institution modal

CHANGELOG.md, s4e-backend/src/main/java/pl/cyfronet/s4e/service/InstitutionService.java, s4e-backend/src/test/java/pl/cyfronet/s4e/controller/InstitutionControllerTest.java
-fix and test refactor for /institutions endpoint
=> [#472] Fix for /institutions endpoint

CHANGELOG.md, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/request/CreateChildInstitutionRequest.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/request/CreateInstitutionRequest.java, s4e-backend/src/main/java/pl/cyfronet/s4e/service/InstitutionService.java, s4e-backend/src/test/java/pl/cyfronet/s4e/controller/InstitutionControllerIntegrationTest.java
- removed @NotEmpty annotation for adminEmail field
- add test that check requirement of emblem being in the request
- refactor
=> Change requirement of admin institution email

CHANGELOG.md, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/response/BasicInstitutionResponse.java, s4e-backend/src/main/java/pl/cyfronet/s4e/service/InstitutionService.java, s4e-backend/src/test/java/pl/cyfronet/s4e/service/InstitutionServiceTest.java
- add parentName to BasicInstitutionResponse
- add test to service methods getParentNameBy and getParentSlugBy
=> Add parentName to basic institution response

CHANGELOG.md, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/InstitutionController.java, s4e-backend/src/main/java/pl/cyfronet/s4e/service/InstitutionService.java, s4e-backend/src/test/java/pl/cyfronet/s4e/controller/InstitutionControllerIntegrationTest.java
=> [#500] Fix PUT endpoint for Institutions

CHANGELOG.md, s4e-backend/src/main/java/pl/cyfronet/s4e/bean/Scene.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/SearchController.java, s4e-backend/src/main/java/pl/cyfronet/s4e/data/repository/SceneRepositoryImpl.java, s4e-backend/src/main/java/pl/cyfronet/s4e/data/repository/query/QueryBuilderImpl.java, s4e-backend/src/main/java/pl/cyfronet/s4e/data/repository/query/QueryDecorator.java, s4e-backend/src/main/java/pl/cyfronet/s4e/data/repository/query/QueryEnding.java, s4e-backend/src/main/java/pl/cyfronet/s4e/data/repository/query/QueryTime.java, s4e-backend/src/main/java/pl/cyfronet/s4e/ex/ErrorHandler.java, s4e-backend/src/test/java/pl/cyfronet/s4e/SceneTestHelper.java, s4e-backend/src/test/java/pl/cyfronet/s4e/controller/SearchControllerTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/data/repository/query/QueryBuilderTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/service/SearchServiceTest.java
- add tests for SearchController
- refactor tests
- fix search
=> Fix search scenes endpoint

CHANGELOG.md, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/ConfigController.java, s4e-backend/src/main/java/pl/cyfronet/s4e/data/repository/query/QueryEnding.java, s4e-backend/src/main/java/pl/cyfronet/s4e/data/repository/query/QueryNumber.java, s4e-backend/src/main/java/pl/cyfronet/s4e/data/repository/query/QueryText.java, s4e-backend/src/main/java/pl/cyfronet/s4e/data/repository/query/QueryTime.java, s4e-backend/src/main/java/pl/cyfronet/s4e/search/SearchQueryParams.java, s4e-backend/src/main/java/pl/cyfronet/s4e/search/SentinelSearchConfig.java, s4e-backend/src/main/java/pl/cyfronet/s4e/search/SentinelSearchConfigSupplier.java, s4e-backend/src/test/java/pl/cyfronet/s4e/controller/ConfigControllerTest.java
Use SearchQueryParams constants in data.repository.query too.
Fixes: #485.
=> [#485] Add sentinel search config endpoint /config/sentinel-search

CHANGELOG.md, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/AppUserController.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/GroupController.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/InstitutionController.java, s4e-backend/src/main/java/pl/cyfronet/s4e/security/CustomMethodSecurityExpressionRoot.java
=> [#522] Remove dependence on Groups in PreAuthorized methods

CHANGELOG.md, s4e-web/src/app/form/form-control/form-control.component.html, s4e-web/src/app/form/form-control/form-control.component.ts, s4e-web/src/app/form/form-input-errors/form-input-errors.component.html, s4e-web/src/app/form/general-input/general-input.ts, s4e-web/src/app/form/input/input.component.ts, s4e-web/src/app/state/profile/profile.service.ts, s4e-web/src/app/views/settings/manage-institutions/institution-form/institution-form.component.html, s4e-web/src/app/views/settings/manage-institutions/institution-form/institution-form.component.spec.ts, s4e-web/src/app/views/settings/manage-institutions/institution-form/institution-form.component.ts, s4e-web/src/app/views/settings/profile/change-password/change-password.component.html, s4e-web/src/app/views/settings/profile/change-password/change-password.component.scss, s4e-web/src/app/views/settings/profile/change-password/change-password.component.spec.ts, s4e-web/src/app/views/settings/profile/change-password/change-password.component.ts, s4e-web/src/app/views/settings/profile/profile.component.html, s4e-web/src/app/views/settings/profile/profile.component.spec.ts, s4e-web/src/app/views/settings/profile/profile.component.ts, s4e-web/src/app/views/settings/profile/profile.module.ts, s4e-web/src/app/views/settings/settings.routes.ts
* change required fields flags for instition form [#510]
* create separated page for change password
Closes #511 #510
=> [#511] Create separate change password page

CHANGELOG.md, s4e-web/src/app/common/store.util.ts, s4e-web/src/app/views/settings/groups/group-form/group-form-modal.model.ts, s4e-web/src/app/views/settings/groups/group-form/group-form.component.html, s4e-web/src/app/views/settings/groups/group-form/group-form.component.spec.ts, s4e-web/src/app/views/settings/groups/group-form/group-form.component.ts, s4e-web/src/app/views/settings/groups/group-list/group-list.component.html, s4e-web/src/app/views/settings/groups/group-list/group-list.component.spec.ts, s4e-web/src/app/views/settings/groups/group-list/group-list.component.ts, s4e-web/src/app/views/settings/groups/groups.module.ts, s4e-web/src/app/views/settings/groups/state/group.model.ts, s4e-web/src/app/views/settings/groups/state/group.service.ts, s4e-web/src/app/views/settings/manage-institutions/institution-form/institution-form.component.spec.ts, s4e-web/src/app/views/settings/manage-institutions/institution-form/institution-form.component.ts, s4e-web/src/app/views/settings/people/people.module.ts, s4e-web/src/app/views/settings/people/person-form/person-form-modal.model.ts, s4e-web/src/app/views/settings/people/person-form/person-form.component.html, s4e-web/src/app/views/settings/people/person-form/person-form.component.spec.ts, s4e-web/src/app/views/settings/people/person-form/person-form.component.ts, s4e-web/src/app/views/settings/people/person-list/person-list.component.spec.ts, s4e-web/src/app/views/settings/people/person-list/person-list.component.ts, s4e-web/src/app/views/settings/people/state/person.factory.spec.ts, s4e-web/src/app/views/settings/people/state/person.service.ts, s4e-web/src/app/views/settings/settings.component.ts, s4e-web/src/app/views/settings/settings.module.ts, s4e-web/src/app/views/settings/settings.routes.ts, s4e-web/src/app/views/settings/state/institutions-search/institutions-search-results.query.spec.ts
=> [#508] Change add group and add person to modal

CHANGELOG.md, s4e-web/package-lock.json, s4e-web/package.json, s4e-web/src/app/app.module.ts, s4e-web/src/app/components/root/root.component.html, s4e-web/src/app/views/map-view/map-view.component.html, s4e-web/src/app/views/map-view/map.module.ts, s4e-web/src/app/views/map-view/map/map.component.html, s4e-web/src/app/views/map-view/map/map.component.ts, s4e-web/src/app/views/map-view/state/utils/layers-loader.util.ts, s4e-web/src/app/views/settings/settings.module.ts
* Add generic loader for HTTP requests
* Add navigation events loader 
* Add `open layer` map loading on `/map/products` site
Closes #217
Test case
1. choose product
2. choose date 04.10.2018 (active)
3. choose any hour
4. Expecting loader will appear
=> [#217] Generic loader for HTTP requests, navigation events and `open layer` map loading on `/map/products` site

CHANGELOG.md, s4e-web/cypress/integration/product-navigation.spec.ts, s4e-web/cypress/page-objects/map/map.po.ts, s4e-web/src/app/views/map-view/map-view.component.html, s4e-web/src/app/views/map-view/map.module.ts, s4e-web/src/app/views/map-view/map.routes.module.ts, s4e-web/src/app/views/map-view/state/common.model.ts, s4e-web/src/app/views/map-view/state/map/map.query.spec.ts, s4e-web/src/app/views/map-view/state/map/map.store.spec.ts, s4e-web/src/app/views/map-view/state/overlay/overlay.model.ts, s4e-web/src/app/views/map-view/state/overlay/overlay.query.spec.ts, s4e-web/src/app/views/map-view/state/product/product.model.ts, s4e-web/src/app/views/map-view/state/product/product.query.spec.ts, s4e-web/src/app/views/map-view/state/product/product.query.ts, s4e-web/src/app/views/map-view/state/product/product.service.spec.ts, s4e-web/src/app/views/map-view/state/product/product.service.ts, s4e-web/src/app/views/map-view/state/product/product.store.ts, s4e-web/src/app/views/map-view/state/view-configuration/view-configuration.store.ts, s4e-web/src/app/views/map-view/view-manager/layer-picker/layer-picker.component.html, s4e-web/src/app/views/map-view/view-manager/layer-picker/layer-picker.component.scss, s4e-web/src/app/views/map-view/view-manager/layer-picker/layer-picker.component.spec.ts, s4e-web/src/app/views/map-view/view-manager/view-manager.component.html, s4e-web/src/app/views/map-view/view-manager/view-manager.component.scss, s4e-web/src/app/views/map-view/view-manager/view-manager.component.ts, s4e-web/src/app/views/map-view/zk/configuration/state/configuration.service.spec.ts
Add favourites tab in sidebar tab in sidebar on /map/products site
* Add counter for favourite products
* Return to all products
Closes #539
=> [#539] Add favourites tab in sidebar tab in sidebar on /map/products site

CHANGELOG.md, s4e-web/src/app/views/register/register.component.html, s4e-web/src/app/views/register/register.component.spec.ts, s4e-web/src/app/views/register/register.component.ts, s4e-web/src/app/views/register/register.factory.spec.ts, s4e-web/src/app/views/register/state/register.model.ts, s4e-web/src/app/views/register/state/register.service.spec.ts, s4e-web/src/app/views/register/state/register.service.ts
* Add name and surname fields to form
* Update post request method
Closes #537
=> [#537] Fix registration form payload

CHANGELOG.md, s4e-web/cypress/integration/settings/institutions.spec.ts, s4e-web/cypress/page-objects/settings/institution-list.po.ts, s4e-web/src/app/state/profile/profile.query.ts, s4e-web/src/app/utils.ts, s4e-web/src/app/views/settings/breadcrumb/breadcrumb.component.html, s4e-web/src/app/views/settings/breadcrumb/breadcrumb.component.spec.ts, s4e-web/src/app/views/settings/breadcrumb/breadcrumb.component.ts, s4e-web/src/app/views/settings/breadcrumb/breadcrumb.model.ts, s4e-web/src/app/views/settings/breadcrumb/breadcrumb.module.ts, s4e-web/src/app/views/settings/breadcrumb/breadcrumb.service.spec.ts, s4e-web/src/app/views/settings/breadcrumb/breadcrumb.service.ts, s4e-web/src/app/views/settings/dashboards.routes.ts, s4e-web/src/app/views/settings/groups/group-list/group-list.component.ts, s4e-web/src/app/views/settings/people/person-list/person-list.component.ts, s4e-web/src/app/views/settings/profile/profile.component.html, s4e-web/src/app/views/settings/settings.component.html, s4e-web/src/app/views/settings/settings.component.ts, s4e-web/src/app/views/settings/settings.module.ts, s4e-web/src/app/views/settings/settings.routes.ts
[#503] Create dynamic breadcrumbs and add general breadcrumb in /settings
* Create a dynamic breadcrumb component loading breadcrumbs from activated route
* Add breadcrumbs to route data param
* Add general breadcrumb to /settings/*
Closes #503
=> [#503] Create dynamic breadcrumbs and add general breadcrumb in /settings

CHANGELOG.md, s4e-backend/src/main/java/pl/cyfronet/s4e/search/SentinelSearchConfigSupplier.java, s4e-web/src/app/state/profile/profile.query.ts, s4e-web/src/app/utils/miscellaneous/miscellaneous.ts, s4e-web/src/app/views/map-view/sentinel-search/sentinel-form/sentinel-form.component.ts, s4e-web/src/app/views/map-view/state/sentinel-search/sentinel-search.metadata.model.spec.ts, s4e-web/src/app/views/map-view/state/sentinel-search/sentinel-search.metadata.model.ts, s4e-web/src/app/views/settings/admin-dashboard/admin-dashboard.component.ts, s4e-web/src/app/views/settings/settings.component.ts, s4e-web/src/app/views/settings/state/institutions-search/institutions-search-results.service.ts
* Fix issue when clicking search bar for institutions
generated console error
=> [HOTFIX] Filtering institutions

CHANGELOG.md, pom.xml, s4e-backend/src/main/java/pl/cyfronet/s4e/bean/Product.java, s4e-backend/src/main/java/pl/cyfronet/s4e/bean/SavedView.java, s4e-backend/src/main/java/pl/cyfronet/s4e/bean/Scene.java, s4e-backend/src/main/java/pl/cyfronet/s4e/bean/package-info.java, s4e-backend/src/main/resources/application.properties
Disable default swagger url.
Move jsonb hibernate type declaration to interested classes, as keeping
it in package-info.java started causing static initialization issues
when starting an application from IntelliJ configuration.
=> Backend dependencies update - 2020.07

CHANGELOG.md, pom.xml, s4e-backend/pom.xml, s4e-backend/src/main/java/pl/cyfronet/s4e/api/ODataController.java, s4e-backend/src/main/java/pl/cyfronet/s4e/api/OSearchController.java, s4e-backend/src/main/java/pl/cyfronet/s4e/api/SearchApiParams.java, s4e-backend/src/main/java/pl/cyfronet/s4e/api/SearchConverter.java, s4e-backend/src/main/java/pl/cyfronet/s4e/config/QueryConfig.java, s4e-backend/src/main/java/pl/cyfronet/s4e/config/SecurityConfig.java, s4e-backend/src/main/java/pl/cyfronet/s4e/data/repository/query/QueryEnding.java, s4e-backend/src/main/java/pl/cyfronet/s4e/data/repository/query/QueryGeometry.java, s4e-backend/src/main/java/pl/cyfronet/s4e/data/repository/query/QueryText.java, s4e-backend/src/main/java/pl/cyfronet/s4e/search/SearchQueryParams.java, s4e-backend/src/main/java/pl/cyfronet/s4e/service/SceneFileStorageService.java, s4e-backend/src/main/java/pl/cyfronet/s4e/service/SceneStorage.java, s4e-backend/src/main/java/pl/cyfronet/s4e/service/SearchService.java, s4e-backend/src/main/java/pl/cyfronet/s4e/util/GeometryUtil.java, s4e-backend/src/main/resources/db/migration/V38__add_gist_index_footprint_scene_table.sql, s4e-backend/src/test/java/pl/cyfronet/s4e/SceneTestHelper.java, s4e-backend/src/test/java/pl/cyfronet/s4e/api/ODataControllerTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/api/OSearchControllerTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/api/SearchConverterTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/controller/SearchControllerTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/service/SceneFileStorageServiceTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/service/SearchServiceTest.java
https://docs.cyfronet.pl/display/FID/API+Sentinel
search API:
- search endpoint for OpenSearch API
- tests for new search endpoint
- parser for search query
- search by geometry polygon and point
download API:
- download -> odata zip and any type.
consideration:
- multiple conditions search
- metadata endpoint in scihub style
Closes #67.
=> 67 api search

CHANGELOG.md, s4e-backend/src/main/java/pl/cyfronet/s4e/db/seed/SeedUsers.java
- add required fields to institutions seeds
send ziped emblems to @wziajka to be added to minio docker image and s3 static/emblems bucket for instances where we will seed institution.
Closes #496.
=> [#496] Fix institutions seeds

s4e-web/src/app/views/settings/intitution-profile/institution-profile.component.html, s4e-web/src/app/views/settings/intitution-profile/institution-profile.component.ts, s4e-web/src/app/views/settings/intitution-profile/institution-profile.module.ts, s4e-web/src/app/views/settings/manage-institutions/institution-form/institution-form.component.spec.ts, s4e-web/src/app/views/settings/manage-institutions/institution-form/institution-form.component.ts, s4e-web/src/app/views/settings/state/institution/institution.service.spec.ts, s4e-web/src/app/views/settings/state/institution/institution.service.ts, s4e-web/src/app/views/settings/state/institutions-search/institutions-search-results.query.ts
* Create children tree list in
* Display list of institutions as a tree in `settings-institution-profile`
**IMPORTANT!!! In case of an insufficient probe of institutions, add children to chosen `institution profile` to see list of them.**
Closes #573
=> [#573] Create children tree list in settings institution-profile

CHANGELOG.md, s4e-web/package-lock.json, s4e-web/package.json, s4e-web/src/app/components/search/search.component.html, s4e-web/src/app/components/search/search.component.spec.ts, s4e-web/src/app/views/login/login.component.html, s4e-web/src/app/views/map-view/map-view.component.html, s4e-web/src/app/views/map-view/map.module.ts, s4e-web/src/app/views/map-view/view-manager/layer-picker/layer-picker.component.scss, s4e-web/src/app/views/map-view/view-manager/view-manager.component.html, s4e-web/src/app/views/map-view/view-manager/view-manager.component.ts, s4e-web/src/app/views/map-view/zk/configuration/share-configuration-modal/share-configuration-modal.component.ts, s4e-web/src/app/views/map-view/zk/report-modal/report-modal.component.html, s4e-web/src/app/views/map-view/zk/report-modal/report-modal.component.ts, s4e-web/src/app/views/map-view/zk/save-config-modal/save-config-modal.component.html, s4e-web/src/app/views/settings/manage-institutions/institution-form/institution-form.component.ts
Source: #515 
**It's build-in functionality and changing it will be more diffcult than outcome of fix**
Source: #552
Source: #547
Closes #566
=> [#566] resize `Warstwy` segment in `/map` sidebar, [Fix] Update UI messages

CHANGELOG.md, README.md, gsg-dataset-s4e-sync-1.env, s4e-backend/src/main/java/pl/cyfronet/s4e/db/seed/SeedProducts.java
Add products which were uploaded to the s4e-sync-1 bucket since the dataset's creation.
Closes #578.
=> [#578] Update s4e-sync-1 dataset

CHANGELOG.md, s4e-backend/src/main/java/pl/cyfronet/s4e/api/MappedScene.java, s4e-backend/src/main/java/pl/cyfronet/s4e/api/OSearchController.java, s4e-backend/src/main/java/pl/cyfronet/s4e/api/ResponseExtender.java, s4e-backend/src/main/java/pl/cyfronet/s4e/bean/Scene.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/SearchController.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/response/SearchResponse.java, s4e-backend/src/main/java/pl/cyfronet/s4e/data/repository/SceneRepositoryExt.java, s4e-backend/src/main/java/pl/cyfronet/s4e/data/repository/SceneRepositoryImpl.java, s4e-backend/src/main/java/pl/cyfronet/s4e/data/repository/SceneRowMapper.java, s4e-backend/src/main/java/pl/cyfronet/s4e/data/repository/query/QueryBuilderImpl.java, s4e-backend/src/main/java/pl/cyfronet/s4e/service/SearchService.java, s4e-backend/src/main/java/pl/cyfronet/s4e/util/GeometryUtil.java, s4e-backend/src/test/java/pl/cyfronet/s4e/api/OSearchControllerTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/controller/SearchControllerTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/data/repository/query/QueryBuilderTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/service/SearchServiceTest.java
=> [#581] Add fields to search response

CHANGELOG.md, s4e-web/src/app/views/map-view/sentinel-search/sentinel-section/sentinel-section.component.spec.ts, s4e-web/src/app/views/map-view/sentinel-search/sentinel-section/sentinel-section.component.ts
Fix query formation when searching sentinel (see steps to reproduce in issue description)
Closes: #568
=> [#568] Fix sentinel search (query formation)

s4e-web/src/app/components/tiles-dashboard/tile/tile.component.html, s4e-web/src/app/components/tiles-dashboard/tiles-dashboard.component.html, s4e-web/src/app/components/tiles-dashboard/tiles-dashboard.component.spec.ts, s4e-web/src/app/views/settings/components/generic-list-view/generic-list-view.component.html, s4e-web/src/app/views/settings/dashboard/dashboard.component.html, s4e-web/src/app/views/settings/intitution-profile/institution-profile.component.html, s4e-web/src/app/views/settings/manage-institutions/institution-list/institution-list.component.html, s4e-web/src/app/views/settings/settings.component.html, s4e-web/src/scss/_settings.scss
=> [#584] Dashboard improvement

.github/workflows/maven.yml, CHANGELOG.md, docker-compose-test.yml, docker-compose.yml, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/AuthController.java, s4e-backend/src/test/java/pl/cyfronet/s4e/controller/AuthControllerTest.java, s4e-web/nginx-e2e.conf, s4e-web/nginx.conf
=> [#589] Set secure flag in token cookie and configure nginx certificate

s4e-web/src/app/views/map-view/map/map.component.ts, s4e-web/src/app/views/map-view/state/overlay/overlay.service.ts
=> [#595] Timestamp limits in scenes GET request

CHANGELOG.md, s4e-web/src/app/components/root/root.component.ts, s4e-web/src/app/components/search/search.component.html, s4e-web/src/app/components/search/search.component.spec.ts, s4e-web/src/app/components/search/search.module.ts, s4e-web/src/app/utils.ts, s4e-web/src/app/utils/dropdown/events.directive.spec.ts, s4e-web/src/app/utils/dropdown/events.directive.ts, s4e-web/src/app/utils/dropdown/events.module.ts, s4e-web/src/app/views/map-view/map-view.component.html, s4e-web/src/app/views/map-view/map-view.component.ts, s4e-web/src/app/views/map-view/map.module.ts, s4e-web/src/app/views/map-view/view-manager/view-manager.component.html, s4e-web/src/app/views/map-view/view-manager/view-manager.component.ts, s4e-web/src/app/views/settings/admin-dashboard/admin-dashboard.component.html, s4e-web/src/app/views/settings/admin-dashboard/admin-dashboard.component.spec.ts, s4e-web/src/app/views/settings/admin-dashboard/admin-dashboard.component.ts, s4e-web/src/app/views/settings/admin-dashboard/admin-dashboard.module.ts, s4e-web/src/app/views/settings/settings.component.html, s4e-web/src/app/views/settings/settings.component.ts, s4e-web/src/app/views/settings/settings.module.ts
* extend dropdowns in code with `EventsDirective`
* events should handle
- inside click
- outside click
- router change
Closes #592
=> [#592] Create events directive

CHANGELOG.md, s4e-web/package.json, s4e-web/src/app/test.utils.spec.ts, s4e-web/src/app/views/map-view/sentinel-search/sentinel-search.component.html, s4e-web/src/app/views/map-view/sentinel-search/sentinel-search.component.spec.ts, s4e-web/src/app/views/map-view/sentinel-search/sentinel-search.component.ts, s4e-web/src/app/views/map-view/state/sentinel-search/sentinel-search.factory.spec.ts
Fix bug with 'Brak wyników' being show regardless of whether sentinel search results were present.
Added unit test coverage to prevent regression.
Closes: #601
=> [#601] No Search Result is showing even when results are found

CHANGELOG.md, s4e-backend/src/main/java/pl/cyfronet/s4e/api/OSearchController.java, s4e-backend/src/main/java/pl/cyfronet/s4e/api/SearchConverter.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/SearchController.java, s4e-backend/src/main/java/pl/cyfronet/s4e/data/repository/SceneRepositoryExt.java, s4e-backend/src/main/java/pl/cyfronet/s4e/data/repository/SceneRepositoryImpl.java, s4e-backend/src/main/java/pl/cyfronet/s4e/data/repository/query/PreparedStatementBuilder.java, s4e-backend/src/main/java/pl/cyfronet/s4e/data/repository/query/QueryBuilder.java, s4e-backend/src/main/java/pl/cyfronet/s4e/data/repository/query/QueryBuilderImpl.java, s4e-backend/src/main/java/pl/cyfronet/s4e/data/repository/query/QueryDecorator.java, s4e-backend/src/main/java/pl/cyfronet/s4e/data/repository/query/QueryEnding.java, s4e-backend/src/main/java/pl/cyfronet/s4e/data/repository/query/QueryGeometry.java, s4e-backend/src/main/java/pl/cyfronet/s4e/data/repository/query/QueryNumber.java, s4e-backend/src/main/java/pl/cyfronet/s4e/data/repository/query/QueryText.java, s4e-backend/src/main/java/pl/cyfronet/s4e/data/repository/query/QueryTime.java, s4e-backend/src/main/java/pl/cyfronet/s4e/ex/ErrorHandler.java, s4e-backend/src/main/java/pl/cyfronet/s4e/ex/ErrorHandlerHelper.java, s4e-backend/src/main/java/pl/cyfronet/s4e/ex/QueryException.java, s4e-backend/src/main/java/pl/cyfronet/s4e/search/SearchQueryParams.java, s4e-backend/src/main/java/pl/cyfronet/s4e/service/SearchService.java, s4e-backend/src/main/resources/messages_pl_PL.properties, s4e-backend/src/test/java/pl/cyfronet/s4e/SceneTestHelper.java, s4e-backend/src/test/java/pl/cyfronet/s4e/api/OSearchControllerTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/controller/SearchControllerTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/data/repository/query/QueryBuilderTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/service/SearchServiceTest.java
=> [#512] Query param handling in search endpoint

CHANGELOG.md, s4e-backend/src/main/java/pl/cyfronet/s4e/db/seed/SeedProducts.java, s4e-backend/src/main/resources/db/migration/V41__add_product_trigger.sql
Before, views were created in SeedProducts, however, this could lead to
inconsistencies, were the product.layer_name modified.
=> [#622] Trigger view creation on product modification

CHANGELOG.md, s4e-backend/src/main/java/pl/cyfronet/s4e/config/SecurityConfig.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/InstitutionController.java, s4e-backend/src/test/java/pl/cyfronet/s4e/controller/InstitutionControllerTest.java
fix condition on getAll for admin endpoint
fix security rule for access to /institutions/{institution} to let through super admin
Closes #551
=> [#551] Super admin security issues

CHANGELOG.md, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/InvitationController.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/request/InvitationRequest.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/response/BasicInvitationResponse.java, s4e-backend/src/main/java/pl/cyfronet/s4e/event/OnDeleteInvitationEvent.java, s4e-backend/src/main/java/pl/cyfronet/s4e/ex/ErrorHandler.java, s4e-backend/src/main/java/pl/cyfronet/s4e/ex/InvitationInvalidInstitutionException.java, s4e-backend/src/main/java/pl/cyfronet/s4e/listener/InvitationListener.java, s4e-backend/src/main/java/pl/cyfronet/s4e/service/InvitationService.java, s4e-backend/src/main/resources/mail/delete-invitation-email.html, s4e-backend/src/main/resources/mail/delete-invitation-email.txt, s4e-backend/src/main/resources/messages_pl_PL.properties, s4e-backend/src/test/java/pl/cyfronet/s4e/InvitationHelper.java, s4e-backend/src/test/java/pl/cyfronet/s4e/controller/InvitationControllerTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/listener/InvitationListenerTest.java
- GET invitations
- DELETE inviation by token
- PUT invitation = remove old and send new invitation
Closes #641
=> [#641] Create endpoints for existing invitations

CHANGELOG.md, s4e-backend/src/main/java/pl/cyfronet/s4e/config/SecurityConfig.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/SceneController.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/response/MostRecentSceneResponse.java, s4e-backend/src/main/java/pl/cyfronet/s4e/data/repository/SceneRepository.java, s4e-backend/src/main/java/pl/cyfronet/s4e/service/SceneService.java, s4e-backend/src/test/java/pl/cyfronet/s4e/controller/SceneControllerTest.java
@kmarszalek: Have a look at the code in general
@michal-szostak: Is the response sufficient? I include both id of the scene and it's timestamp there.
Closes: #680.
=> [#680] Create endpoint returning most recent Scene for a Product

CHANGELOG.md, s4e-backend/src/scripts/seed.sh
=> [#696] Don't use deprecated temporary file name generator

CHANGELOG.md, README.md, backend-production.env.template, gs-gateway/pom.xml, gs-gateway/src/main/resources/log4j2.properties, gs-gateway/src/main/resources/sentry.properties, pom.xml, s4e-backend/pom.xml, s4e-backend/src/main/resources/log4j2.properties, s4e-backend/src/main/resources/sentry.properties
=> [#687] Add Sentry

CHANGELOG.md, restart-core-containers.sh, s4e-backend/src/main/java/pl/cyfronet/s4e/admin/geoserver/AdminGeoserverController.java, s4e-backend/src/main/java/pl/cyfronet/s4e/bean/WMSOverlay.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/OverlayController.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/request/OverlayRequest.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/response/OverlayResponse.java, s4e-backend/src/main/java/pl/cyfronet/s4e/data/repository/WMSOverlayRepository.java, s4e-backend/src/main/java/pl/cyfronet/s4e/service/OverlayService.java, s4e-backend/src/main/resources/db/migration/V46__add_global_personal_and_institution_overlay.sql, s4e-backend/src/scripts/seed.sh, s4e-backend/src/test/java/pl/cyfronet/s4e/OverlayHelper.java, s4e-backend/src/test/java/pl/cyfronet/s4e/controller/OverlayControllerTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/service/GeoServerServiceIntegrationTest.java, s4e-web/src/app/views/map-view/map-view.component.ts, s4e-web/src/app/views/map-view/map/map.component.ts, s4e-web/src/app/views/map-view/state/overlay/overlay.factory.spec.ts, s4e-web/src/app/views/map-view/state/overlay/overlay.model.ts, s4e-web/src/app/views/map-view/state/overlay/overlay.query.spec.ts, s4e-web/src/app/views/map-view/state/overlay/overlay.query.ts, s4e-web/src/app/views/map-view/state/overlay/overlay.service.ts, s4e-web/src/app/views/map-view/view-manager/overlay-list-modal/overlay-list-modal.component.html, s4e-web/src/app/views/map-view/view-manager/overlay-list-modal/overlay-list-modal.component.ts
- fix url to previous form ../wms=?...LAYERS=<layer_name>
- fix `nazwa warstwy` should be saved and displayed
=> [Hotfix] PRG URL Overlays

CHANGELOG.md, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/InstitutionController.java, s4e-backend/src/main/java/pl/cyfronet/s4e/service/InstitutionService.java, s4e-backend/src/test/java/pl/cyfronet/s4e/controller/InstitutionControllerIntegrationTest.java, s4e-web/cypress/integration/settings/settings-institution-profile.spec.ts, s4e-web/cypress/integration/settings/settings-institutions-list.spec.ts, s4e-web/cypress/page-objects/settings/settings-institution-list.po.ts, s4e-web/cypress/page-objects/settings/settings-institution-search.po.ts, s4e-web/src/app/components/search/search.component.ts, s4e-web/src/app/views/settings/manage-institutions/institution-form/institution-form.component.spec.ts, s4e-web/src/app/views/settings/manage-institutions/institution-form/institution-form.component.ts, s4e-web/src/app/views/settings/manage-institutions/institution-list/institution-list.component.html, s4e-web/src/app/views/settings/profile/profile.component.html, s4e-web/src/app/views/settings/settings.component.html, s4e-web/src/app/views/settings/settings.component.ts, s4e-web/src/app/views/settings/state/institution/institution.service.ts
=> [#683] fix add institution with form

CHANGELOG.md, s4e-backend/src/main/java/pl/cyfronet/s4e/config/SecurityConfig.java, s4e-backend/src/main/resources/db/migration/V49__add_constraint_parent_institution.sql, s4e-backend/src/test/java/pl/cyfronet/s4e/controller/InstitutionControllerTest.java
- add ON DELETE CASCADE for fk key to parent Institution
- add tests for DELETE endpoint
- add security for DELETE institution endpoint
Closes #709.
=> [#709] Fix DELETE on institution in API

CHANGELOG.md, s4e-web/cypress/integration/map/map-get-jwt-token.spec.ts, s4e-web/cypress/page-objects/map/map-jwt-token-modal.po.ts, s4e-web/cypress/page-objects/map/map.po.ts, s4e-web/src/app/state/form/form.model.ts, s4e-web/src/app/state/session/session.service.ts, s4e-web/src/app/views/map-view/jwt-token-modal/jwt-token-modal.component.html, s4e-web/src/app/views/map-view/jwt-token-modal/jwt-token-modal.component.spec.ts, s4e-web/src/app/views/map-view/jwt-token-modal/jwt-token-modal.component.ts, s4e-web/src/app/views/map-view/jwt-token-modal/jwt-token-modal.model.ts, s4e-web/src/app/views/map-view/map-view.component.html, s4e-web/src/app/views/map-view/map-view.component.ts, s4e-web/src/app/views/map-view/map.module.ts
- add modal to copy jwt token after authentication
Closes #713
=> [#713] Copy JWT token to clipboard on map in user floating button

CHANGELOG.md, s4e-backend/src/main/java/pl/cyfronet/s4e/api/MappedScene.java, s4e-backend/src/main/java/pl/cyfronet/s4e/bean/Scene.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/response/SearchResponse.java, s4e-backend/src/main/java/pl/cyfronet/s4e/data/repository/SceneRowMapper.java, s4e-backend/src/main/java/pl/cyfronet/s4e/data/repository/query/QueryBuilderImpl.java, s4e-backend/src/test/java/pl/cyfronet/s4e/controller/SearchControllerTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/data/repository/query/QueryBuilderTest.java
@michal-szostak: You can display the name part of the key in the front-end search results, instead of the mocked value in a separate ticket.
Closes: #743.
=> [#743] Add scene key to SearchResponse

CHANGELOG.md, s4e-backend/src/main/java/pl/cyfronet/s4e/bean/AppRole.java, s4e-backend/src/main/java/pl/cyfronet/s4e/config/InstitutionSecurityHelper.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/InstitutionController.java, s4e-backend/src/main/java/pl/cyfronet/s4e/db/seed/SeedUsers.java, s4e-backend/src/main/java/pl/cyfronet/s4e/service/InstitutionService.java, s4e-backend/src/main/java/pl/cyfronet/s4e/service/InvitationService.java, s4e-backend/src/main/java/pl/cyfronet/s4e/service/OverlayService.java, s4e-backend/src/main/java/pl/cyfronet/s4e/service/UserRoleService.java, s4e-backend/src/main/resources/db/migration/V51__remove_obsolete_app_roles_from_user_role_table.sql, s4e-backend/src/test/java/pl/cyfronet/s4e/controller/AppUserControllerTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/controller/InstitutionControllerIntegrationTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/controller/InstitutionControllerTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/controller/InvitationControllerTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/controller/OverlayControllerTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/data/repository/AppUserRepositoryTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/service/InstitutionServiceTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/service/UserRoleServiceTest.java, s4e-web/src/app/state/session/session.model.ts, s4e-web/src/app/state/session/session.query.spec.ts
Remove roles which are no longer used: INST_MANAGER and GROUP_MANAGER.
Moreover, make GROUP_MEMBER name more accurate by renaming to
INST_MEMBER, as there are no groups anymore.
Closes: #746
=> [#746] Remove obsolete AppRoles

CHANGELOG.md, s4e-web/src/app/views/login/login.component.ts, s4e-web/src/app/views/map-view/jwt-token-modal/jwt-token-modal.component.ts, s4e-web/src/app/views/map-view/map/map.component.ts, s4e-web/src/app/views/settings/people/invitation-form/invitation-form.component.ts, s4e-web/src/app/views/settings/people/state/invitation/invitation.service.ts, s4e-web/src/app/views/settings/profile/change-password/change-password.component.ts
FIx imports of notification service to have it work correctly.
Closes: #651
=> [#651] Fix notifications

CHANGELOG.md, s4e-web/cypress/integration/map/map-products.spec.ts, s4e-web/cypress/page-objects/map/map.po.ts, s4e-web/src/app/utils/rxjs/observable.ts, s4e-web/src/app/utils/time/hour.pipe.ts, s4e-web/src/app/views/map-view/state/scene/scene.factory.spec.ts, s4e-web/src/app/views/map-view/timeline/timeline.component.html, s4e-web/src/app/views/map-view/timeline/timeline.component.spec.ts, s4e-web/src/app/views/map-view/timeline/timeline.component.ts, s4e-web/src/scss/_timeline.scss
@michal-szostak - I've taken over this PR, and updated code so that functionality does work correctly.
Closes: #726
=> [#726] Elements for handling close datapoints

CHANGELOG.md, gs-gateway/src/main/java/pl/cyfronet/gsg/GsGatewayApplication.java, gs-gateway/src/main/java/pl/cyfronet/gsg/counter/GetMapRequestCounterFilter.java, gs-gateway/src/main/java/pl/cyfronet/gsg/security/LayerSecurityGatewayFilter.java, gs-gateway/src/test/java/pl/cyfronet/gsg/counter/GetMapRequestCounterFilterTest.java, gs-gateway/src/test/java/pl/cyfronet/gsg/security/LayerSecurityGatewayFilterTest.java
- add mapRequestCounter metric
- add GetCapabilities section in LayerSecurityGatewayFilter
Closes #699
=> [#699] GS-Gateway mapRequestCounter metric

CHANGELOG.md, s4e-web/package-lock.json, s4e-web/package.json, s4e-web/src/app/views/map-view/map-view.component.ts, s4e-web/src/app/views/map-view/zk/report-modal/report-generator.spec.ts, s4e-web/src/app/views/map-view/zk/report-modal/report-generator.ts, s4e-web/src/app/views/map-view/zk/report-modal/report-modal.component.html, s4e-web/src/app/views/map-view/zk/report-modal/report-modal.component.ts, s4e-web/src/app/views/map-view/zk/report-modal/report-modal.model.ts, s4e-web/src/scss/styles.scss
* Map zoop / move refinement when generating PDF report for zk.
Closes: #657
=> [#657] Map zoom / pan in report modal

CHANGELOG.md, s4e-backend/src/main/resources/mail/share-link.html, s4e-backend/src/main/resources/mail/share-link.txt
=> [#790] New text for sharing view mail

CHANGELOG.md, s4e-web/src/app/app.routes.ts, s4e-web/src/app/views/register/register-confirmation/register-confirmation.component.html, s4e-web/src/app/views/register/register-confirmation/register-confirmation.component.scss, s4e-web/src/app/views/register/register-confirmation/register-confirmation.component.spec.ts, s4e-web/src/app/views/register/register-confirmation/register-confirmation.component.ts, s4e-web/src/app/views/register/register.module.ts, s4e-web/src/app/views/register/state/register.service.ts, s4e-web/src/scss/_auth.scss
=> [#769] Add `Potwierdzenie rejestracji` page and go to it after successful register

CHANGELOG.md, s4e-web/src/app/views/settings/people/invitation-form/invitation-form.component.html
Content added to invitation form
=> [#629] Content for invitation form

s4e-backend/src/main/java/pl/cyfronet/s4e/db/seed/SeedUsers.java, s4e-web/cypress/integration/settings/settings-institutions-list.spec.ts
- fix user roles in zk tree
@wziajka this will fix roles for users from seed in zk instituion tree. master should be reseeded and pr populated with new db.
@Marcelinna this PR can be tested here http://pr-784-sok.docker-fid.grid.cyf-kr.edu.pl/ only after Wojtek will use newly seeded db.
Closes #783
=> [#783] Fix users seed

s4e-web/src/app/views/map-view/state/map/map.service.spec.ts, s4e-web/src/app/views/map-view/state/overlay/overlay.model.ts, s4e-web/src/app/views/map-view/state/overlay/overlay.query.spec.ts
Closes #765 
Description:
Show loader on map site when choosing overlay
=> [#765] [Fix] Show overlay loading indicator

.github/workflows/maven.yml, s4e-web/cypress.json, s4e-web/cypress/integration/map/map-favorite-products.spec.ts, s4e-web/cypress/integration/map/map-layers.spec.ts, s4e-web/cypress/integration/map/map-locations-search.spec.ts, s4e-web/cypress/integration/map/map-products.spec.ts, s4e-web/cypress/integration/settings/settings-invitations-list.spec.ts, s4e-web/cypress/page-objects/core.po.ts, s4e-web/cypress/page-objects/login/login.po.ts, s4e-web/cypress/page-objects/map/map-layers.po.ts, s4e-web/cypress/page-objects/map/map-locations-search.po.ts, s4e-web/cypress/page-objects/map/map-products.po.ts, s4e-web/cypress/page-objects/map/map-views.po.ts, s4e-web/cypress/page-objects/map/map.po.ts, s4e-web/cypress/page-objects/modal/general-modal.po.ts, s4e-web/cypress/page-objects/settings/settings-add-institution-form.po.ts, s4e-web/cypress/page-objects/settings/settings-dashboard.po.ts, s4e-web/cypress/page-objects/settings/settings-institution-list.po.ts, s4e-web/cypress/page-objects/settings/settings-institution-people.po.ts, s4e-web/cypress/page-objects/settings/settings-institution-profile.po.ts, s4e-web/cypress/page-objects/settings/settings-institution-search.po.ts, s4e-web/cypress/page-objects/settings/settings-parent-institution-modal.po.ts, s4e-web/cypress/page-objects/settings/settings-side-nav.po.ts, s4e-web/cypress/page-objects/settings/settings-user-profile.po.ts, s4e-web/package-lock.json, s4e-web/package.json
- turn off video recording
- fix inconsistency in the behavior of .goTo function while sending element to it (dispatching of async tasks in cypress could provide inconsistency)
- remove unnecessary .should('be.visible') to achieve less logs in browser
- clear store before login (force logout on application)
- upgrade of cypress to 4.12.1
=> [Fix] E2e optimization and longer timeout

s4e-backend/src/main/java/pl/cyfronet/s4e/data/repository/InstitutionRepository.java, s4e-backend/src/main/java/pl/cyfronet/s4e/service/InvitationService.java, s4e-backend/src/test/java/pl/cyfronet/s4e/controller/InvitationControllerTest.java
- add check if user is not a member
- add InvitationControllerTest.createShouldntCreateForMember
Closes #827
=> [#827] Secure multiple invitation for one email

s4e-backend/src/main/java/pl/cyfronet/s4e/api/SearchConverter.java, s4e-backend/src/main/resources/application.properties, s4e-backend/src/test/java/pl/cyfronet/s4e/api/OSearchControllerTest.java
- add brackets handling in params for tomcat
Closes #838
=> [#838] Fix date handling in search API

s4e-backend/seed-configs/seed-1/schema/Sentinel-1.scene.v1.json, s4e-backend/seed-configs/seed-1/schema/Sentinel-2.scene.v1.json
=> [#848] Add thumbnail artifact to Sentinel schemas

s4e-web/src/app/views/settings/intitution-profile/institution-profile.component.html, s4e-web/src/app/views/settings/intitution-profile/institution-profile.component.ts, s4e-web/src/app/views/settings/manage-institutions/institution-form/institution-form.component.ts, s4e-web/src/app/views/settings/people/invitation-form/invitation-form.component.ts, s4e-web/src/app/views/settings/people/person-list/person-list.component.html, s4e-web/src/app/views/settings/people/person-list/person-list.component.ts, s4e-web/src/app/views/settings/people/state/invitation/invitation.service.spec.ts, s4e-web/src/app/views/settings/people/state/invitation/invitation.service.ts, s4e-web/src/app/views/settings/people/state/person/person.service.ts
=> [#842, #834 #802, #853] Miscellaneous settings fixes

s4e-web/src/app/views/map-view/state/sentinel-search/sentinel-search.model.ts
=> Fix search product URL id

s4e-backend/src/main/java/pl/cyfronet/s4e/api/ODataController.java, s4e-backend/src/main/java/pl/cyfronet/s4e/config/SecurityConfig.java, s4e-backend/src/main/java/pl/cyfronet/s4e/service/SceneStorage.java, s4e-backend/src/main/java/pl/cyfronet/s4e/util/SceneArtifactsHelper.java, s4e-backend/src/main/resources/application.properties, s4e-backend/src/test/java/pl/cyfronet/s4e/api/ODataControllerTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/controller/SceneControllerTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/util/SceneArtifactsHelperTest.java
=> [#868] Make sure download endpoints require authenticated user

s4e-backend/src/main/resources/mail/account-activated.html, s4e-backend/src/main/resources/mail/confirm-email.html, s4e-backend/src/main/resources/mail/confirm-invitation-email.html, s4e-backend/src/main/resources/mail/delete-invitation-email.html, s4e-backend/src/main/resources/mail/duplicate-registration.html, s4e-backend/src/main/resources/mail/expert-help-sending-confirmation.html, s4e-backend/src/main/resources/mail/expert-help.html, s4e-backend/src/main/resources/mail/institution-add-member.html, s4e-backend/src/main/resources/mail/institution-remove-member.html, s4e-backend/src/main/resources/mail/invitation-email.html, s4e-backend/src/main/resources/mail/password-reset.html, s4e-backend/src/main/resources/mail/reject-invitation-email.html, s4e-backend/src/main/resources/mail/share-link.html, s4e-web/src/app/views/map-view/view-manager/view-manager.component.html, s4e-web/src/app/views/map-view/zk/expert-help-modal/expert-help-modal.component.html, s4e-web/src/app/views/map-view/zk/save-config-modal/save-config-modal.component.html
=> [#869] - Content improvement in emails

s4e-web/src/app/app.module.ts, s4e-web/src/app/app.providers.ts, s4e-web/src/app/views/apihowto/apihowto.component.html, s4e-web/src/app/views/apihowto/apihowto.component.ts
FIX] Add info and proper examples to apihowto.component
- add dynamic hostname to apihowto.component
- add info section
- add wget examples
- fix curl examples
=> [FIX] Add dynamic hostname to apihowto.component

s4e-web/src/app/views/map-view/map-view.component.ts, s4e-web/src/app/views/map-view/map/map.component.ts, s4e-web/src/app/views/map-view/state/overlay/overlay.model.ts, s4e-web/src/app/views/map-view/state/overlay/overlay.utils.ts, s4e-web/src/app/views/map-view/state/scene/scene.service.ts, s4e-web/src/app/views/map-view/state/utils/layers-loader.util.ts, s4e-web/src/app/views/map-view/zk/save-config-modal/save-config-modal.component.ts
- Change Image Wms to Tile Wms loading handling
Closes #786
=> [#786] OL Loading indicator should only be affected by last OL request

.github/workflows/e2e.yml, .github/workflows/test.yml
Split the front-end tests into two jobs: one for unit tests and the
second for e2e tests.
Fixes: #883.
=> [#883] GH-actions improvement

s4e-backend/src/main/java/pl/cyfronet/s4e/controller/request/PasswordChangeRequest.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/request/PasswordResetRequest.java
=> [#797] Add password length validation when changing it

s4e-backend/src/main/java/pl/cyfronet/s4e/controller/InvitationController.java, s4e-backend/src/main/java/pl/cyfronet/s4e/listener/InvitationListener.java, s4e-backend/src/main/java/pl/cyfronet/s4e/service/InvitationService.java, s4e-backend/src/test/java/pl/cyfronet/s4e/listener/InvitationListenerTest.java
=> [#826] Fix resend invitation

s4e-backend/src/main/java/pl/cyfronet/s4e/controller/AppUserController.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/InvitationController.java, s4e-backend/src/main/java/pl/cyfronet/s4e/service/InvitationService.java, s4e-backend/src/test/java/pl/cyfronet/s4e/controller/AppUserControllerTest.java, s4e-web/cypress/integration/map/map-views.spec.ts, s4e-web/src/app/state/session/session.service.ts, s4e-web/src/app/utils/auth-guard/auth-guard.service.ts, s4e-web/src/app/views/login/login.component.html, s4e-web/src/app/views/login/login.component.spec.ts, s4e-web/src/app/views/login/login.component.ts, s4e-web/src/app/views/register/register.component.html, s4e-web/src/app/views/register/register.component.spec.ts, s4e-web/src/app/views/register/register.component.ts, s4e-web/src/app/views/register/state/register.service.spec.ts, s4e-web/src/app/views/register/state/register.service.ts, s4e-web/src/app/views/settings/manage-institutions/institution-form/institution-form.component.spec.ts, s4e-web/src/app/views/settings/people/state/invitation/invitation.service.ts, s4e-web/src/app/views/settings/state/institution/institution.service.ts
- [Fix] After declining the invitation, the link leads to page 404 #833
- [Fix] Fix adding a user to an institution on invitation acceptance #836
=> [#833][#836] Fix invitation flow

s4e-web/src/app/views/settings/profile/profile.component.html, s4e-web/src/app/views/settings/profile/profile.component.ts
- Chaneg static name and surname to dynamic one using session store
=> [Fix] User details in profile

s4e-backend/src/main/java/pl/cyfronet/s4e/controller/response/SceneResponse.java, s4e-backend/src/test/java/pl/cyfronet/s4e/controller/SceneControllerTest.java
=> [#918] Extend SceneResponse with artifacts and metadata

s4e-web/src/app/views/map-view/map-view.component.ts, s4e-web/src/app/views/map-view/state/view-configuration/view-configuration.service.ts, s4e-web/src/app/views/map-view/zk/list-configs-modal/list-configs-modal.component.html, s4e-web/src/app/views/map-view/zk/list-configs-modal/list-configs-modal.component.ts
- On send view load overlay, product and open send view modal
=> Load map and open modal on send view

s4e-backend/src/main/java/pl/cyfronet/s4e/bean/audit/CreationAndModificationAudited.java, s4e-backend/src/main/java/pl/cyfronet/s4e/bean/audit/CreationAudited.java, s4e-backend/src/main/java/pl/cyfronet/s4e/config/PersistenceConfig.java, s4e-backend/src/main/java/pl/cyfronet/s4e/config/SecurityConfig.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/AppUserController.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/request/ForgetUserRequest.java, s4e-backend/src/main/java/pl/cyfronet/s4e/data/repository/InvitationRepository.java, s4e-backend/src/main/java/pl/cyfronet/s4e/security/AppUserDetails.java, s4e-backend/src/main/java/pl/cyfronet/s4e/security/AppUserDetailsService.java, s4e-backend/src/main/java/pl/cyfronet/s4e/service/AppUserMapper.java, s4e-backend/src/main/java/pl/cyfronet/s4e/service/AppUserService.java, s4e-backend/src/main/resources/db/migration/V62__modify_audit_fields.sql, s4e-backend/src/test/java/pl/cyfronet/s4e/SecurityTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/TestJwtUtil.java, s4e-backend/src/test/java/pl/cyfronet/s4e/controller/AppUserControllerTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/db/AuditingTest.java
- add id to userDetails
- change AuditorAware to id
- add endpoints forget-me that anonymise data
Closes #918
=> [#918] Add endpoint forget-me to anonymise data

s4e-web/src/app/views/map-view/map/map.component.ts, s4e-web/src/app/views/map-view/sentinel-search/search-results/search-results.component.html, s4e-web/src/app/views/map-view/sentinel-search/search-results/search-results.component.ts, s4e-web/src/app/views/map-view/sentinel-search/sentinel-search.component.html, s4e-web/src/app/views/map-view/sentinel-search/sentinel-search.component.ts, s4e-web/src/app/views/map-view/state/sentinel-search/sentinel-search.model.ts, s4e-web/src/app/views/map-view/state/sentinel-search/sentinel-search.query.ts, s4e-web/src/app/views/map-view/state/sentinel-search/sentinel-search.service.ts
How to find feature?
1. Go to `sentinel search` on `map`
2. Search for any result
3. Hover on result
=> [#916] Show polygon on map on sentinel search result hover

s4e-web/src/app/views/apihowto/apihowto.component.html, s4e-web/src/app/views/apihowto/apihowto.component.ts
add section WMS API to apihowto page
Closes #940
=> [#940] Add WMS API description to apihowto

s4e-backend/src/main/java/pl/cyfronet/s4e/controller/request/RegisterRequest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/controller/AppUserControllerTest.java
Add the validation, as the front-end form is now implemented.
Closes: #950.
=> [#950] Require scientific domain fields on register

s4e-web/cypress/integration/auth/auth-login.spec.ts, s4e-web/src/app/app.module.ts, s4e-web/src/app/state/session/session.service.ts, s4e-web/src/app/utils/initializer/config.service.ts, s4e-web/src/app/views/settings/manage-institutions/institution-form/institution-form.component.ts, s4e-web/src/app/views/settings/people/state/invitation/invitation.service.ts
=> [#903] Prevent logged in user to access /login page

s4e-web/src/app/views/map-view/map.module.ts, s4e-web/src/app/views/map-view/sentinel-search/search-result-modal/search-result-modal.component.ts, s4e-web/src/app/views/map-view/sentinel-search/search-results/search-results.component.html, s4e-web/src/app/views/map-view/sentinel-search/search-results/search-results.component.spec.ts, s4e-web/src/app/views/map-view/sentinel-search/search-results/search-results.component.ts, s4e-web/src/app/views/map-view/sentinel-search/sentinel-search.component.html, s4e-web/src/app/views/map-view/sentinel-search/sentinel-search.component.ts, s4e-web/src/app/views/map-view/state/sentinel-search/sentinel-search.factory.spec.ts, s4e-web/src/app/views/map-view/state/sentinel-search/sentinel-search.model.ts, s4e-web/src/app/views/map-view/state/sentinel-search/sentinel-search.query.ts, s4e-web/src/app/views/map-view/state/sentinel-search/sentinel-search.service.spec.ts, s4e-web/src/app/views/map-view/state/sentinel-search/sentinel-search.service.ts, s4e-web/src/app/views/map-view/state/sentinel-search/sentinel-search.store.ts, s4e-web/src/scss/_common.scss, s4e-web/src/scss/_modal.scss, s4e-web/src/scss/_sidebar.scss, s4e-web/src/scss/_variables.scss
* Add pagination to sentinel search results and show total result's count
Closes: #937
=> [#937] Sentinel Search Result Pagination

s4e-web/src/app/state/form/form.model.ts, s4e-web/src/app/state/session/session.service.spec.ts, s4e-web/src/app/state/session/session.service.ts, s4e-web/src/app/views/register/register.component.html, s4e-web/src/app/views/settings/components/generic-list-view/generic-list-view.component.html, s4e-web/src/app/views/settings/intitution-profile/institution-profile.component.html, s4e-web/src/app/views/settings/profile/change-password/change-password.component.html, s4e-web/src/app/views/settings/profile/profile.component.html, s4e-web/src/app/views/settings/profile/profile.component.spec.ts, s4e-web/src/app/views/settings/profile/profile.component.ts, s4e-web/src/app/views/settings/profile/profile.module.ts, s4e-web/src/scss/_auth.scss, s4e-web/src/scss/_common.scss, s4e-web/src/scss/_modal.scss, s4e-web/src/scss/_settings.scss
=> Change user profile view

s4e-web/src/app/views/map-view/map-view.component.html, s4e-web/src/app/views/map-view/map/map.component.spec.ts, s4e-web/src/app/views/map-view/map/map.component.ts, s4e-web/src/app/views/map-view/sentinel-search/sentinel-search.component.html, s4e-web/src/app/views/map-view/state/sentinel-search/sentinel-search.model.ts, s4e-web/src/app/views/map-view/state/sentinel-search/sentinel-search.service.ts, s4e-web/src/app/views/map-view/state/sentinel-search/sentinel-search.store.ts
Where to find feature?
Login
Go to sentinel search on map
Click on map and move mouse
- Draw polygon (as closed form) to search sentinels
- Start drawing new one by clicking on map
Closes #922
=> [#922] Search sentinels by polygon drawing

s4e-web/src/app/state/session/session.model.ts, s4e-web/src/app/state/session/session.query.ts, s4e-web/src/app/views/settings/manage-authorities/manage-authorities.component.html, s4e-web/src/app/views/settings/manage-authorities/manage-authorities.component.ts, s4e-web/src/app/views/settings/manage-institutions/institution-list/institution-list.component.html, s4e-web/src/app/views/settings/manage-institutions/institution-list/institution-list.component.ts, s4e-web/src/app/views/settings/people/person-list/person-list.component.html, s4e-web/src/app/views/settings/people/state/person/person.model.ts, s4e-web/src/app/views/settings/people/state/person/person.query.ts, s4e-web/src/app/views/settings/people/state/person/person.service.ts, s4e-web/src/app/views/settings/settings.component.html, s4e-web/src/app/views/settings/settings.component.ts, s4e-web/src/app/views/settings/settings.module.ts, s4e-web/src/app/views/settings/settings.routes.ts
=> Add ability to remove institutions

s4e-web/src/app/views/map-view/map-view.component.html, s4e-web/src/app/views/map-view/map-view.component.spec.ts, s4e-web/src/app/views/map-view/map-view.component.ts, s4e-web/src/app/views/map-view/sentinel-search/search-result-modal/search-result-modal.component.html, s4e-web/src/app/views/map-view/sentinel-search/search-result-modal/search-result-modal.component.spec.ts, s4e-web/src/app/views/map-view/sentinel-search/search-result-modal/search-result-modal.component.ts, s4e-web/src/app/views/map-view/sentinel-search/search-result-modal/search-result-modal.model.ts, s4e-web/src/app/views/map-view/state/scene/scene.factory.spec.ts, s4e-web/src/app/views/map-view/state/scene/scene.model.ts, s4e-web/src/app/views/map-view/state/scene/scene.service.spec.ts, s4e-web/src/app/views/map-view/state/scene/scene.service.ts, s4e-web/src/app/views/map-view/state/sentinel-search/sentinel-search.model.ts, s4e-web/src/app/views/map-view/state/sentinel-search/sentinel-search.service.spec.ts, s4e-web/src/app/views/map-view/state/sentinel-search/sentinel-search.service.ts, s4e-web/src/scss/_common.scss
Change behavior after clicking 'download files' for selected scene - now modal is opened where user can see details and download selected artifacts.
Closes #880 #863
=> [#880, #863] Show details for scene and allow artifact download

s4e-backend/src/main/resources/db/migration/V63__remove_name_unique_constraint_from_wms_overlay_table.sql
=> [#967] Remove unique name constraint from wms_overlay

s4e-web/src/app/views/map-view/state/legend/legend.query.spec.ts, s4e-web/src/app/views/map-view/state/view-configuration/view-configuration.model.ts, s4e-web/src/app/views/map-view/state/view-configuration/view-configuration.service.ts, s4e-web/src/app/views/map-view/state/view-configuration/view-configuration.store.spec.ts, s4e-web/src/app/views/map-view/state/view-configuration/view-configuration.store.ts
Preserve HC / Large font setting between page reloads (save in local storage)
1. Change settings to HC / Large Font
2. Refresh page
3. The setting should be preserved
=> [FIX] Persist HC / LargeFont settings

s4e-web/src/app/views/register/register.component.spec.ts, s4e-web/src/app/views/register/register.component.ts, s4e-web/src/app/views/settings/intitution-profile/institution-profile.component.html, s4e-web/src/app/views/settings/settings.component.html
=> [Fix] registartion fields, remove breadcrumb in institution profile, hide add global wms

s4e-web/src/app/state/session/session.query.ts, s4e-web/src/app/state/session/session.service.ts, s4e-web/src/app/views/login/login.component.ts, s4e-web/src/app/views/settings/people/state/invitation/invitation.service.ts
- replace switch map to finalize for route navigation while login and logout
=> [Fix] Confirm invitation on login

s4e-web/src/app/state/session/session.service.ts, s4e-web/src/app/utils/error-interceptor/error.interceptor.ts, s4e-web/src/main.ts
All stores are reset after user logs out
Closes #806
=> [#806] Clear store after logout

s4e-backend/seed-configs/seed-1/products.json
=> Update product descriptions

s4e-web/cypress/integration/auth/auth-login.spec.ts, s4e-web/cypress/integration/map/map-products.spec.ts, s4e-web/src/app/components/overlay-list/overlay-list.component.ts, s4e-web/src/app/views/map-view/state/product/product.model.ts, s4e-web/src/app/views/map-view/state/product/product.service.ts, s4e-web/src/app/views/settings/intitution-profile/institution-profile.component.html, s4e-web/src/app/views/settings/manage-products/manage-products.component.html, s4e-web/src/app/views/settings/manage-products/manage-products.component.ts, s4e-web/src/app/views/settings/people/person-list/person-list.component.html, s4e-web/src/app/views/settings/settings.module.ts, s4e-web/src/app/views/settings/settings.routes.ts, s4e-web/src/app/views/settings/wms-overlays/wms-overlays.component.html
IMPORTANT!!! Due to missing mock examples of products bind with specific institutions, manual tests can't be done
=> Manage institution licence products

s4e-web/src/app/views/settings/manage-institutions/institution-form/files.utils.ts, s4e-web/src/app/views/settings/manage-institutions/institution-form/institution-form.component.ts
- Allow user to upload files with larger images then 500 x 500 and lesser then 130 x 130 by scaling then up and down
=> Resize institution emblem on upload

s4e-web/src/app/views/apihowto/apihowto.component.html, s4e-web/src/app/views/map-view/user-dropdown/user-dropdown.component.html, s4e-web/src/app/views/map-view/zk/expert-help-modal/expert-help-modal.component.html, s4e-web/src/app/views/map-view/zk/report-modal/report-modal.component.html, s4e-web/src/app/views/register/register.component.html, s4e-web/src/app/views/settings/intitution-profile/institution-profile.component.html, s4e-web/src/app/views/settings/profile/profile.component.html
Minor updates in various texts. Typos or grammar corrected
=> Proofreading

s4e-backend/src/test/java/pl/cyfronet/s4e/BasicTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/IntegrationTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/TestAwaitilityConfiguration.java, s4e-backend/src/test/java/pl/cyfronet/s4e/admin/sync/task/ChunkedRunnerTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/admin/sync/task/SyncJobManagerTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/controller/AppUserControllerTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/controller/ExpertHelpControllerTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/controller/ShareLinkControllerTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/sync/QueueReceiverIntegrationTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/sync/SceneAcceptorIntegrationTest.java
- add configuration
- remove unnecessary code `atMost()`
Closes #995
=> [#995] Awaitility test configuration

s4e-web/src/app/views/map-view/map-view.component.ts, s4e-web/src/app/views/map-view/state/map/map.query.ts, s4e-web/src/app/views/map-view/state/map/map.service.ts, s4e-web/src/app/views/map-view/state/product/product.model.ts, s4e-web/src/app/views/map-view/state/product/product.service.ts, s4e-web/src/app/views/map-view/state/product/product.store.ts, s4e-web/src/app/views/map-view/state/scene/scene.service.ts, s4e-web/src/app/views/map-view/state/view-configuration/view-configuration.model.ts
* Auto select last scene when loading product
* Try to match closest (time wise) scene when switching between products (after setting date manually)
Closes #993
=> [#993] Scene auto select

s4e-web/src/app/state/session/session.query.ts, s4e-web/src/app/views/map-view/map-view.component.html, s4e-web/src/app/views/map-view/map-view.component.ts
- show funcitonalitites in map dropdown to pak user
=> [#986] Show zk memebr functionalities to pak user

s4e-web/src/app/components/overlay-list/overlay-list.component.html, s4e-web/src/app/components/overlay-list/overlay-list.component.ts, s4e-web/src/app/components/overlay-list/wms-url.utils.ts, s4e-web/src/app/views/map-view/state/overlay/image-wms.utils.ts
- Set fixed image WMS size while loading it (in URL)
- Decode openlayers src URL
- [Fix] Show loading indicator on submit
=> [Fix] Overlays loading indicator and url formatting

s4e-backend/seed-configs/seed-1/products.json, s4e-web/src/app/views/map-view/legend/legend.component.html, s4e-web/src/app/views/map-view/legend/legend.component.scss, s4e-web/src/app/views/map-view/legend/legend.component.spec.ts, s4e-web/src/app/views/settings/settings.component.html, s4e-web/src/assets/legends_json/legend_108.json, s4e-web/src/assets/legends_json/legend_ZK_daily_fire.json, s4e-web/src/assets/legends_json/legend_charakterystykapowierzhcni.json, s4e-web/src/assets/legends_json/legend_dwutlenekazotu.json, s4e-web/src/assets/legends_json/legend_intensywnoscopadu.json, s4e-web/src/assets/legends_json/legend_ozon.json, s4e-web/src/assets/legends_json/legend_polewiatrunamorzu.json, s4e-web/src/assets/legends_json/legend_pylwatmosferze.json, s4e-web/src/assets/legends_json/legend_stabilnoscatmosfery.json, s4e-web/src/assets/legends_json/legend_sumaopadu.json, s4e-web/src/assets/legends_json/legend_wilgotnoscgleby.json, s4e-web/src/scss/_auth.scss, s4e-web/src/scss/_common.scss, s4e-web/src/scss/_map.scss, s4e-web/src/scss/_rwd_phone.scss, s4e-web/src/scss/_rwd_tablet.scss, s4e-web/src/scss/_rwd_varia.scss, s4e-web/src/scss/_settings.scss, s4e-web/src/scss/_sidebar.scss, s4e-web/src/scss/_timeline.scss, s4e-web/src/scss/styles.scss
- RWD sidebar fixed when desktop sidebar is collapsed
- scaled legend when max-height 700px and in mobile view
- Info box about poligon appeard in sentinel search
- map and timeline have now fixed position
- legends unit
=> UI fixes (legend, sidebar, various)

s4e-backend/src/main/java/pl/cyfronet/s4e/listener/ExpertHelpListener.java, s4e-backend/src/main/resources/messages_pl_PL.properties
=> [#978] Fix type of request for expert mail

s4e-web/src/app/components/search/search.component.html, s4e-web/src/app/components/search/search.component.scss, s4e-web/src/app/components/search/search.component.ts, s4e-web/src/app/errors/errors.component.html, s4e-web/src/app/state/session/session.service.ts, s4e-web/src/app/views/map-view/jwt-token-modal/jwt-token-modal.component.ts, s4e-web/src/app/views/map-view/map-view.component.html, s4e-web/src/app/views/map-view/map-view.component.ts, s4e-web/src/app/views/map-view/map/map.component.ts, s4e-web/src/app/views/map-view/state/map/map.query.ts, s4e-web/src/app/views/map-view/state/map/map.service.ts, s4e-web/src/app/views/map-view/view-manager/overlay-list-modal/overlay-list-modal.component.html, s4e-web/src/app/views/map-view/view-manager/overlay-list-modal/overlay-list-modal.component.ts, s4e-web/src/app/views/settings/manage-institutions/institution-form/files.utils.ts, s4e-web/src/app/views/settings/manage-institutions/institution-form/institution-form.component.ts, s4e-web/src/app/views/settings/people/invitation-form/invitation-form.component.ts, s4e-web/src/app/views/settings/people/state/invitation/invitation.model.ts, s4e-web/src/app/views/settings/profile/change-password/change-password.component.ts, s4e-web/src/app/views/settings/wms-overlays/wms-overlays.component.ts
- Fix user password change [#788](https://github.com/cyfronet-fid/sat4envi/issues/788)
The city name is not highlighted during navigating with the arrows [#791](https://github.com/cyfronet-fid/sat4envi/issues/791)
- [FIX] In the generated report and inconsistent names [#815](https://github.com/cyfronet-fid/sat4envi/issues/815)
Confusing message when trying to generate a token [#819](https://github.com/cyfronet-fid/sat4envi/issues/819)
- [FIX] URL in dashboard and redirection after clicking on the button  <_Anuluj> in edit mode and in the mode of adding a new institution [#873](https://github.com/cyfronet-fid/sat4envi/issues/873)
- WAITING nad REJECTED near invited person should be written in polish.
- [Fix] sending invitation second time on the same mail …
=> Minor fixes: Typos, missing translations, invitation bugs, poligon map, login bug

s4e-backend/src/main/resources/db/migration/V65__performance.sql
This reverts commit a5796212.
The migration was pre-computed and can be restored to the v16.2.x branch now.
=> Restore "[#1019] Improve GetCapabilities performance"

s4e-web/src/app/views/map-view/map/map.component.ts, s4e-web/src/app/views/map-view/state/scene/scene.model.ts
On select a scene show polygon on map
=> Add an active scene polygon to the map

s4e-backend/seed-configs/seed-1/products.json, s4e-backend/src/main/java/pl/cyfronet/s4e/admin/category/AdminProductCategoryController.java, s4e-backend/src/main/java/pl/cyfronet/s4e/admin/product/AdminCreateProductRequest.java, s4e-backend/src/main/java/pl/cyfronet/s4e/admin/product/AdminProductController.java, s4e-backend/src/main/java/pl/cyfronet/s4e/admin/product/AdminProductResponse.java, s4e-backend/src/main/java/pl/cyfronet/s4e/admin/product/AdminUpdateProductRequest.java, s4e-backend/src/main/java/pl/cyfronet/s4e/bean/Product.java, s4e-backend/src/main/java/pl/cyfronet/s4e/bean/ProductCategory.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/response/BasicProductCategoryResponse.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/response/BasicProductResponse.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/response/ProductResponse.java, s4e-backend/src/main/java/pl/cyfronet/s4e/data/repository/ProductRepository.java, s4e-backend/src/main/java/pl/cyfronet/s4e/service/ProductService.java, s4e-backend/src/main/resources/db/migration/V68__add_rank_field_to_product_and_product_category.sql, s4e-backend/src/test/java/pl/cyfronet/s4e/InvitationTestHelper.java, s4e-backend/src/test/java/pl/cyfronet/s4e/OverlayTestHelper.java, s4e-backend/src/test/java/pl/cyfronet/s4e/ProductCategoryTestHelper.java, s4e-backend/src/test/java/pl/cyfronet/s4e/SceneTestHelper.java, s4e-backend/src/test/java/pl/cyfronet/s4e/admin/product/AdminProductControllerTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/controller/AppUserControllerTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/controller/ExpertHelpControllerTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/controller/InvitationControllerTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/controller/OverlayControllerTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/controller/ProductControllerTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/geoserver/op/SeedProductsTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/listener/InvitationListenerTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/service/GeoServerServiceIntegrationTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/service/GeoServerServiceTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/service/ProductServiceTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/sync/SceneAcceptorTestHelper.java
Add field rank, based on which returned product lists are sorted.
By default, current id-order is maintained.
Closes: #1041.
=> [#1041] Custom sorting of products and product categories

s4e-backend/src/main/java/pl/cyfronet/s4e/controller/ConfigController.java, s4e-backend/src/main/java/pl/cyfronet/s4e/data/repository/ProductRepository.java, s4e-backend/src/main/java/pl/cyfronet/s4e/search/SentinelSearchConfigSupplier.java, s4e-backend/src/main/java/pl/cyfronet/s4e/service/ProductService.java
Make product type a required field, and display it before platform.
Moreover, put ingestion time filters in sections, as "other" products
don't have this metadata.
The listed products are based on authorities, excluding the ones which
a user doesn't have access to.
Closes: #1040.
=> [#1040] Add search category and dynamically load product names

s4e-web/src/app/components/root/root.component.ts, s4e-web/src/app/components/search/search.component.html, s4e-web/src/app/components/search/search.component.scss, s4e-web/src/app/components/search/search.component.ts, s4e-web/src/app/utils/error-interceptor/error.interceptor.ts, s4e-web/src/app/views/login/login.component.html, s4e-web/src/app/views/map-view/map-view.component.ts, s4e-web/src/app/views/map-view/map/map.component.scss, s4e-web/src/app/views/map-view/map/map.component.ts, s4e-web/src/app/views/map-view/user-dropdown/user-dropdown.component.html, s4e-web/src/scss/_wcag.scss
- Fix fast selection of location in location search
- Fix active location color in location search
- Fix active location selection with mapa marker icon in location search
- Fix set/unset larger font
- Add map scale in map left top corner
=> Fix login backlink, fix locations search, fix redirect to settings dashboard

s4e-web/src/app/components/search/search.component.html, s4e-web/src/app/components/search/search.component.spec.ts, s4e-web/src/app/components/search/search.component.ts, s4e-web/src/app/views/map-view/view-manager/view-manager.component.ts
- check search form control value type
=> Fix locations search

s4e-web/src/app/views/map-view/map/map.component.ts
Set the tile load function, to set the withCredentials flag on the XHR
requests for product tiles.
Fixes: #1081.
=> [#1081] Send credentials with CORS image tile requests

README.md, s4e-backend/seed-configs/seed-1/license-grants.json, s4e-backend/seed-configs/seed-1/products.json, s4e-backend/seed-configs/seed-1/schema/FWI.metadata.v1.json, s4e-backend/seed-configs/seed-1/schema/FWI.scene.v1.json, s4e-backend/src/scripts/seed.sh
They have new schemas: FWI.(scene|metadata).v1.json.
Extend seed.sh to create license-grants for FWI products.
Closes: #1091.
=> [#1091] Add FWI private products

s4e-web/src/scss/_common.scss, s4e-web/src/scss/_settings.scss, s4e-web/src/scss/_sidebar.scss, s4e-web/src/scss/_timeline.scss, s4e-web/src/scss/_wcag.scss
- table cells and paragraphs are bigger
- search results fixed
- timeline has bigger dots
=> [#1068] Fixed wcag-fontSize bugs

s4e-web/src/app/views/map-view/map-view.component.html, s4e-web/src/app/views/map-view/map-view.component.ts, s4e-web/src/app/views/map-view/map.module.ts, s4e-web/src/app/views/map-view/timeline/mobile-scene-selector-modal/mobile-scene-selector-modal.component.html, s4e-web/src/app/views/map-view/timeline/mobile-scene-selector-modal/mobile-scene-selector-modal.component.scss, s4e-web/src/app/views/map-view/timeline/mobile-scene-selector-modal/mobile-scene-selector-modal.component.spec.ts, s4e-web/src/app/views/map-view/timeline/mobile-scene-selector-modal/mobile-scene-selector-modal.component.ts, s4e-web/src/app/views/map-view/timeline/mobile-scene-selector-modal/mobile-scene-selector-modal.model.ts, s4e-web/src/app/views/map-view/timeline/timeline.component.html, s4e-web/src/app/views/map-view/timeline/timeline.component.ts, s4e-web/src/assets/images/ico_clock.svg, s4e-web/src/scss/_modal.scss, s4e-web/src/scss/_rwd_tablet.scss, s4e-web/src/scss/_timeline.scss
=> [#1003] Add mobile scene selection modal

s4e-web/src/app/errors/errors.component.html, s4e-web/src/app/errors/errors.component.scss, s4e-web/src/app/views/map-view/sentinel-search/search-results/search-results.component.scss, s4e-web/src/app/views/map-view/timeline/timeline.component.scss, s4e-web/src/app/views/map-view/user-dropdown/user-dropdown.component.html, s4e-web/src/app/views/map-view/view-manager/view-manager.component.html, s4e-web/src/scss/_auth.scss, s4e-web/src/scss/_common.scss, s4e-web/src/scss/_rwd_phone.scss, s4e-web/src/scss/_rwd_tablet.scss, s4e-web/src/scss/_rwd_varia.scss, s4e-web/src/scss/_sidebar.scss, s4e-web/src/scss/_timeline.scss
#840 
- fixed product loader. Now z-index is set to 1 (instead 9999)
- added infobox about more products under products list
=> Front fixes

s4e-web/src/scss/_wcag.scss
In wcag mode legend chart was inverted. This PR fixes this.
=> Wcag legend fix

gs-gateway/src/main/java/pl/cyfronet/gsg/GsGatewayApplication.java, gs-gateway/src/main/java/pl/cyfronet/gsg/counter/GetMapRequestCounterFilter.java, gs-gateway/src/main/java/pl/cyfronet/gsg/counter/MetricService.java, gs-gateway/src/test/java/pl/cyfronet/gsg/counter/GetMapRequestCounterFilterTest.java, s4e-backend/src/main/java/pl/cyfronet/s4e/api/ODataController.java, s4e-backend/src/main/java/pl/cyfronet/s4e/config/CounterConfig.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/SceneController.java, s4e-backend/src/main/java/pl/cyfronet/s4e/service/MetricService.java
Click on map and choose sentinel -> GSG mapCounter + specificSentinelCounter
Click on download or api download -> Backend specificSentinelCounter
Closes #1128
=> 1128 metric download

s4e-web/src/app/views/map-view/user-dropdown/user-dropdown.component.html
=> Tutorial link

s4e-backend/src/main/java/pl/cyfronet/s4e/Application.java, s4e-backend/src/main/java/pl/cyfronet/s4e/config/OpenApiConfig.java, s4e-backend/src/main/java/pl/cyfronet/s4e/config/SecurityConfig.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/SceneController.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/SearchController.java, s4e-backend/src/main/java/pl/cyfronet/s4e/search/SearchQueryParams.java, s4e-backend/src/main/resources/application-production.properties, s4e-backend/src/main/resources/application.properties, s4e-backend/src/test/java/pl/cyfronet/s4e/SwaggerTest.java, s4e-web/src/app/views/apihowto/apihowto.component.html
Add security information to OpenAPI description and how-to.
Correct description of a few endpoints.
Group API endpoints and expose their definitions to selected authorities.
Add search endpoint query parameters to OpenAPI.
=> Improve API description

s4e-web/src/app/views/map-view/timeline/timeline.component.ts
- All scenes should be still time sorted
- Duplicated time scenes should be sorted by map coordinates from top to down and right to left
=> [#1158] Sort timeline buckets scenes top to down and right to left

s4e-backend/src/main/java/pl/cyfronet/s4e/api/OSearchController.java, s4e-backend/src/main/java/pl/cyfronet/s4e/config/LicenseConfig.java, s4e-backend/src/main/java/pl/cyfronet/s4e/config/QueryConfig.java, s4e-backend/src/main/java/pl/cyfronet/s4e/config/TimeConfig.java, s4e-backend/src/main/java/pl/cyfronet/s4e/controller/SearchController.java, s4e-backend/src/main/java/pl/cyfronet/s4e/data/repository/query/QueryTime.java, s4e-backend/src/main/java/pl/cyfronet/s4e/search/SearchQueryParams.java, s4e-backend/src/main/java/pl/cyfronet/s4e/service/SearchService.java, s4e-backend/src/main/java/pl/cyfronet/s4e/sync/ScenePersister.java, s4e-backend/src/main/java/pl/cyfronet/s4e/util/GeometryUtil.java, s4e-backend/src/test/java/pl/cyfronet/s4e/InvitationTestHelper.java, s4e-backend/src/test/java/pl/cyfronet/s4e/OverlayTestHelper.java, s4e-backend/src/test/java/pl/cyfronet/s4e/ProductCategoryTestHelper.java, s4e-backend/src/test/java/pl/cyfronet/s4e/SceneTestHelper.java, s4e-backend/src/test/java/pl/cyfronet/s4e/api/OSearchControllerTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/controller/SearchControllerTest.java, s4e-backend/src/test/java/pl/cyfronet/s4e/service/SearchServiceTest.java, s4e-web/src/app/views/apihowto/apihowto.component.html
28 records, 2 with eumetsat license, one with a full hour.
Search for Eumetsat license product for anonymous:
Search for Eumetsat license product for zkMember
Closes #1140
=> [#1140] Fix license handling in search endpoints

s4e-backend/src/main/java/pl/cyfronet/s4e/search/SearchPanelConfig.java, s4e-backend/src/test/java/pl/cyfronet/s4e/controller/ConfigControllerTest.java
=> Map "noaa.metadata.v1.json" schema to "Satelity polarne" label in search

s4e-web/src/app/views/map-view/user-dropdown/user-dropdown.component.html
=> Add link to copernicus.imgw.pl

s4e-web/src/assets/images/legend_cbk_floods.svg, s4e-web/src/assets/legends_json/legend_cbk_floods.json
=> Add legend for cbk floods

gs-gateway/Dockerfile, s4e-backend/Dockerfile
- change openjdk to eclipse-temurin due to removing support for openjdk after 17.0.2
=> Change docker images
